# -*- coding: utf-8 -*-
import sys, json, glob
sys.path.insert(0, "lib")
from deck_template_teen import run
from grammar_slides import match_grammar_by_lesson_focus

_lessons = {}
for f in sorted(glob.glob("lessons/level4/lesson*.json")):
    d = json.load(open(f, encoding="utf-8"))
    _lessons[d["number"]] = d
GRAMMAR_UNITS = match_grammar_by_lesson_focus("level4", _lessons)

DIALOGUES = {
  1: [("Does she even sleep? She's always studying!", "هل تنام حتى؟ إنها دائما تدرس!"),
      ("Does she wake up early too?", "هل تستيقظ باكرا أيضا؟"),
      ("Yes, but do you ever relax?", "نعم، لكن هل تسترخي أبدا؟"),
      ("I do! I chill every weekend.", "بالفعل! أسترخي كل عطلة أسبوع.")],
  2: [("What's your schedule like today?", "كيف هو جدولك اليوم؟"),
      ("Busy! I have a workout, then homework.", "مزدحم! لدي تمرين رياضي، ثم واجب منزلي."),
      ("Do you have a deadline too?", "هل لديك موعد نهائي أيضا؟"),
      ("Yes, and my bedtime is still 10 pm!", "نعم، ووقت نومي لا يزال العاشرة مساء!")],
  3: [("How often do you check your messages?", "كم مرة تتحقق من رسائلك؟"),
      ("Constantly, honestly!", "باستمرار، بصراحة!"),
      ("I rarely check mine.", "أنا نادرا ما أتحقق من رسائلي."),
      ("I occasionally forget my phone completely.", "أحيانا أنسى هاتفي تماما.")],
  4: [("Do you have an appointment before the weekend?", "هل لديك موعد قبل عطلة نهاية الأسبوع؟"),
      ("Yes, right after school.", "نعم، بعد المدرسة مباشرة."),
      ("Is your deadline before the holiday?", "هل موعدك النهائي قبل العطلة؟"),
      ("Yes, everything is due before the break.", "نعم، كل شيء مستحق قبل الاستراحة.")],
  5: [("Send it to me when you're done.", "أرسلها لي عندما تنتهي."),
      ("I'll call him first, then reply to her.", "سأتصل به أولا، ثم أرد عليها."),
      ("Let's invite them to video chat.", "لندعوهم لمكالمة فيديو."),
      ("Good idea, let's meet them online tonight.", "فكرة جيدة، لنقابلهم عبر الإنترنت الليلة.")],
  6: [("Are these earbuds yours?", "هل سماعات الأذن هذه لك؟"),
      ("No, that jacket is mine, not the earbuds.", "لا، تلك السترة لي، وليست السماعات."),
      ("Is this notebook hers?", "هل هذا الدفتر لها؟"),
      ("Yes, and that wallet is his.", "نعم، وتلك المحفظة له.")],
  7: [("Do we have any snacks left?", "هل لدينا أي وجبات خفيفة متبقية؟"),
      ("There are some leftovers in the fridge.", "هناك بعض بقايا الطعام في الثلاجة."),
      ("Do we need any groceries?", "هل نحتاج أي مشتريات؟"),
      ("Yes, we need some ingredients for dinner.", "نعم، نحتاج بعض المكونات للعشاء.")],
  8: [("How much is your allowance?", "كم مصروفك؟"),
      ("Not much, so I check every price tag.", "ليس كثيرا، لذا أتحقق من كل بطاقة سعر."),
      ("Is there a discount today?", "هل يوجد خصم اليوم؟"),
      ("Yes! Keep the receipt for your budget.", "نعم! احتفظ بالإيصال لميزانيتك.")],
  9: [("How do you save money?", "كيف تدخر المال؟"),
      ("I earn some doing chores, then I save it.", "أكسب بعضه من الأعمال المنزلية، ثم أدخره."),
      ("Do you ever spend it all?", "هل تنفقه كله أبدا؟"),
      ("Rarely -- I'd rather lend it to my sister!", "نادرا -- أفضل أن أقرضه لأختي!")],
  10: [("Who's the most talented singer you know?", "من أكثر مغني موهوب تعرفه؟"),
       ("My cousin -- she's the most skilled too.", "ابنة عمي -- وهي الأكثر مهارة أيضا."),
       ("That was the most impressive performance!", "كان ذلك الأداء الأكثر إبهارا!"),
       ("She's definitely the most popular singer at school.", "إنها بالتأكيد أكثر مغنية شهرة في المدرسة.")],
  11: [("What would you like to order?", "ماذا تريد أن تطلب؟"),
       ("I'd like a pizza, please. What do you recommend?", "أريد بيتزا من فضلك. بماذا توصي؟"),
       ("I prefer the pasta, actually.", "أفضل المعكرونة في الحقيقة."),
       ("Good choice! I suggest we share both.", "خيار جيد! أقترح أن نتشارك الاثنين.")],
  12: [("Can I give you some advice?", "هل يمكنني إعطاؤك نصيحة؟"),
       ("Sure, what's your suggestion?", "بالتأكيد، ما اقتراحك؟"),
       ("You should practice a little every day.", "يجب أن تتمرن قليلا كل يوم."),
       ("That's a great tip, thank you!", "هذه نصيحة رائعة، شكرا لك!")],
  13: [("Did you see her new post?", "هل رأيت منشورها الجديد؟"),
       ("Yes, I left a comment on it.", "نعم، تركت تعليقا عليه."),
       ("I shared it too. Are you online now?", "شاركته أيضا. هل أنت متصل الآن؟"),
       ("Yes, I just got a notification about it!", "نعم، وصلني إشعار بشأنه للتو!")],
  14: [("We should cooperate more on this project.", "يجب أن نتعاون أكثر في هذا المشروع."),
       ("I agree. Everyone should contribute.", "أوافق. يجب أن يساهم الجميع."),
       ("Let's support and encourage each other.", "لندعم ونشجع بعضنا."),
       ("Great teamwork makes a great leader!", "العمل الجماعي الرائع يصنع قائدا رائعا!")],
  15: [("I need to decide soon. There are two options.", "أحتاج أن أقرر قريبا. هناك خياران."),
       ("Consider the consequence of each one.", "فكر في نتيجة كل خيار."),
       ("Maybe we can find a compromise.", "ربما نستطيع إيجاد حل وسط."),
       ("Good idea. It's a big choice either way.", "فكرة جيدة. إنه خيار كبير على أي حال.")],
  16: [("I always feel nervous before a test.", "أشعر دائما بالتوتر قبل الاختبار."),
       ("I usually feel confident, but sometimes anxious.", "أشعر عادة بالثقة، لكن أحيانا بالقلق."),
       ("Try to stay calm under pressure.", "حاول أن تبقى هادئا تحت الضغط."),
       ("I feel relieved and proud after it's over!", "أشعر بالارتياح والفخر بعد انتهائه!")],
  17: [("What's your goal for the future?", "ما هدفك للمستقبل؟"),
       ("My dream is to have a career in art.", "حلمي أن أحصل على مهنة في الفن."),
       ("That's a great ambition. Art is your passion?", "هذا طموح رائع. الفن شغفك؟"),
       ("Yes, and I want to achieve it!", "نعم، وأريد تحقيقه!")],
  18: [("Every country has its own culture.", "لكل دولة ثقافتها الخاصة."),
       ("And its own traditions and language.", "وتقاليدها ولغتها الخاصة."),
       ("I want to explore new places and customs.", "أريد استكشاف أماكن وعادات جديدة."),
       ("It would be an amazing journey!", "ستكون رحلة مذهلة!")],
  19: [("Our group project deadline is Friday.", "الموعد النهائي لمشروعنا الجماعي هو الجمعة."),
       ("At first, we disagree about the plan.", "في البداية، نختلف حول الخطة."),
       ("But then we find a compromise.", "لكننا نجد حلا وسطا بعد ذلك."),
       ("Teamwork saves the day -- we're so proud!", "العمل الجماعي ينقذ الموقف -- نحن فخورون جدا!")],
  20: [("What are your plans for next year?", "ما خططك للعام القادم؟"),
       ("I want to save more and try new things.", "أريد أن أدخر أكثر وأجرب أشياء جديدة."),
       ("Let's write down our future goals.", "لنكتب أهدافنا المستقبلية."),
       ("This has been an amazing journey together!", "كانت هذه رحلة مذهلة معا!")],
}

run("level4", DIALOGUES, GRAMMAR_UNITS)
