# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "lib")
from deck_template_v2 import run
import json

phonics_data = json.load(open("phonics-hub/level2.json", encoding="utf-8"))
PHONICS_UNITS = {2 * i - 1: u for i, u in enumerate(phonics_data["units"], 1)}

DIALOGUES = {
  1: [("L", "Hello! Nice to meet you!", "مرحبا! تشرفنا!"),
      ("R", "Nice to meet you too! What's your name?", "تشرفنا أيضا! ما اسمك؟"),
      ("L", "My name is Omar. Thank you for saying hello!", "اسمي عمر. شكرا لك على الترحيب!"),
      ("R", "You're welcome! Goodbye for now!", "عفوا! مع السلامة الآن!")],
  2: [("L", "How old are you?", "كم عمرك؟"),
      ("R", "I am eight years old. How old are you?", "عمري ثماني سنوات. كم عمرك أنت؟"),
      ("L", "I am seven years old. My birthday is in May.", "عمري سبع سنوات. عيد ميلادي في مايو."),
      ("R", "Happy early birthday!", "عيد ميلاد سعيد مقدما!")],
  3: [("L", "This is my family tree. These are my grandparents.", "هذه شجرة عائلتي. هؤلاء أجدادي."),
      ("R", "Who is this?", "من هذا؟"),
      ("L", "This is my uncle, and this is my aunt.", "هذا عمي، وهذه عمتي."),
      ("R", "You have a big family!", "لديك عائلة كبيرة!")],
  4: [("L", "Look, who is that?", "انظر، من ذلك؟"),
      ("R", "He is my brother. He is funny.", "هو أخي. هو مضحك."),
      ("L", "And who is she?", "ومن هي؟"),
      ("R", "She is my sister. She is smart.", "هي أختي. هي ذكية.")],
  5: [("L", "Is this your bag?", "هل هذه حقيبتك؟"),
      ("R", "No, that is not my bag. This is my bag.", "لا، تلك ليست حقيبتي. هذه حقيبتي."),
      ("L", "Whose bag is that, then?", "حقيبة من تلك إذن؟"),
      ("R", "That is her bag, I think.", "تلك حقيبتها على ما أظن.")],
  6: [("L", "Have you got a phone?", "هل لديك هاتف؟"),
      ("R", "Yes, I have got a new phone. Have you got a watch?", "نعم، لدي هاتف جديد. هل لديك ساعة؟"),
      ("L", "I have got a watch and an umbrella too!", "لدي ساعة ومظلة أيضا!"),
      ("R", "Wow, you have got a lot of things!", "واو، لديك أشياء كثيرة!")],
  7: [("L", "My cheek hurts a little.", "خدي يؤلمني قليلا."),
      ("R", "Oh no! Is your chin okay?", "يا للأسف! هل ذقنك بخير؟"),
      ("L", "Yes, my chin is fine. My elbow hurts too.", "نعم، ذقني بخير. مرفقي يؤلمني أيضا."),
      ("R", "Let's ask the teacher for help.", "لنسأل المعلمة للمساعدة.")],
  8: [("L", "There is a big board in our classroom.", "هناك سبورة كبيرة في فصلنا."),
      ("R", "Is there a playground too?", "هل هناك ملعب أيضا؟"),
      ("L", "Yes! There is a playground next to the classroom.", "نعم! هناك ملعب بجانب الفصل."),
      ("R", "I love our classroom and playground!", "أحب فصلنا وملعبنا!")],
  9: [("L", "Please stand up, everyone.", "من فضلكم، قفوا جميعا."),
      ("R", "Okay! Now what?", "حسنا! والآن؟"),
      ("L", "Now sit down and listen carefully.", "الآن اجلسوا واستمعوا بانتباه."),
      ("R", "Should we open our books too?", "هل نفتح كتبنا أيضا؟")],
  10: [("L", "Can you count to a hundred?", "هل تستطيع العد إلى مئة؟"),
      ("R", "I can count by tens: twenty, thirty, forty...", "أستطيع العد بالعشرات: عشرون، ثلاثون، أربعون..."),
      ("L", "Great! What comes after eighty?", "رائع! ماذا يأتي بعد الثمانين؟"),
      ("R", "Ninety, then one hundred!", "تسعون، ثم مئة!")],
  11: [("L", "When is your birthday?", "متى عيد ميلادك؟"),
      ("R", "My birthday is in January. What month is it now?", "عيد ميلادي في يناير. ما الشهر الآن؟"),
      ("L", "It is September. School just started.", "إنه سبتمبر. بدأت المدرسة للتو."),
      ("R", "My favorite month is June, no school!", "شهري المفضل هو يونيو، لا مدرسة!")],
  12: [("L", "We are having a birthday party today!", "لدينا حفلة عيد ميلاد اليوم!"),
      ("R", "Wonderful! Are there balloons and a cake?", "رائع! هل هناك بالونات وكعكة؟"),
      ("L", "Yes, and candles too! Every guest gets a present.", "نعم، وشموع أيضا! كل ضيف يحصل على هدية."),
      ("R", "I can't wait for the cake!", "لا أستطيع الانتظار للكعكة!")],
  13: [("L", "What time is it?", "كم الساعة؟"),
      ("R", "It is three o'clock. Look at the clock!", "الساعة الثالثة تماما. انظر إلى الساعة!"),
      ("L", "Is it afternoon or evening?", "هل هو بعد الظهر أم المساء؟"),
      ("R", "It is the afternoon. School ends soon.", "إنه بعد الظهر. تنتهي المدرسة قريبا.")],
  14: [("L", "What do you do every morning?", "ماذا تفعل كل صباح؟"),
      ("R", "I wake up, then I brush my teeth.", "أستيقظ، ثم أنظف أسناني."),
      ("L", "Do you have breakfast before school?", "هل تتناول الفطور قبل المدرسة؟"),
      ("R", "Yes, I have breakfast, then I go to school.", "نعم، أتناول الفطور، ثم أذهب إلى المدرسة.")],
  15: [("L", "What do you do in the evening?", "ماذا تفعل في المساء؟"),
      ("R", "I come home, then I do my homework.", "أعود إلى المنزل، ثم أؤدي واجبي."),
      ("L", "Do you read before bed?", "هل تقرأ قبل النوم؟"),
      ("R", "Yes, I read a book, then I go to bed.", "نعم، أقرأ كتابا، ثم أذهب إلى النوم.")],
  16: [("L", "What do you eat for breakfast?", "ماذا تأكل في الفطور؟"),
      ("R", "I eat eggs for breakfast. What about lunch?", "آكل بيضا في الفطور. ماذا عن الغداء؟"),
      ("L", "I eat healthy food for lunch, like vegetables.", "آكل طعاما صحيا في الغداء، مثل الخضار."),
      ("R", "I drink a lot of water every day too.", "أشرب الكثير من الماء كل يوم أيضا.")],
  17: [("L", "Do you like drawing?", "هل تحب الرسم؟"),
      ("R", "Yes, I do! I like drawing and painting.", "نعم، أحب! أحب الرسم والتلوين."),
      ("L", "Do you like singing?", "هل تحب الغناء؟"),
      ("R", "No, I don't. But I like dancing!", "لا، لا أحب. لكن أحب الرقص!")],
  18: [("L", "This is my pencil. What is that?", "هذا قلمي. ما ذلك؟"),
      ("R", "That is your bag, over there.", "تلك حقيبتك، هناك."),
      ("L", "And these are my books!", "وهذه كتبي!"),
      ("R", "Those are nice books!", "تلك كتب جميلة!")],
  19: [("L", "I have two boxes here.", "لدي صندوقان هنا."),
      ("R", "How many children are playing outside?", "كم طفلا يلعبون في الخارج؟"),
      ("L", "Three children are playing. Look, two babies are sleeping.", "ثلاثة أطفال يلعبون. انظر، طفلان رضيعان نائمان."),
      ("R", "And two men are watching them.", "ورجلان يراقبانهم.")],
  20: [("L", "Hello! Let's talk about my family and my classroom.", "مرحبا! دعنا نتحدث عن عائلتي وفصلي."),
      ("R", "What do you eat for breakfast?", "ماذا تأكل في الفطور؟"),
      ("L", "I eat breakfast, then I like drawing before school.", "آكل الفطور، ثم أحب الرسم قبل المدرسة."),
      ("R", "Happy birthday, by the way! Look at the clock — time for class!", "عيد ميلاد سعيد بالمناسبة! انظر إلى الساعة — حان وقت الحصة!")],
}

# See gen_slides_prea_v2.py's THEME_MAP for the reasoning behind reusable
# themes instead of one background per lesson.
THEME_MAP = {
    1: "classroom", 2: "classroom", 3: "family-home", 4: "classroom", 5: "classroom",
    6: "playroom", 7: "bedroom", 8: "school", 9: "school", 10: "classroom",
    11: "classroom", 12: "party", 13: "bedroom", 14: "bedroom", 15: "bedroom",
    16: "kitchen", 17: "market", 18: "classroom", 19: "classroom", 20: "classroom",
}

# Real character-scene images illustrating this lesson's most important
# words, shown right before the sentence-building slides. See
# assets/vocab-scenes/level2/<NN>.jpg for the actual images.
SCENE_DATA = [
    (1, 1, ["Hello", "Goodbye"], "Hello! Goodbye, see you later!"),
    (1, 2, ["Please", "Thank you"], "Please! Thank you very much!"),
    (1, 3, ["Sorry", "Nice to meet you"], "Sorry! Nice to meet you!"),
    (2, 4, ["old", "young"], "Grandpa is old. The baby is young."),
    (2, 5, ["birthday", "years old"], "It's my birthday! I am seven years old."),
    (2, 6, ["grow up"], "I grow up every year."),
    (3, 7, ["parents", "grandparents"], "These are my parents. These are my grandparents."),
    (3, 8, ["uncle", "aunt"], "This is my uncle. This is my aunt."),
    (3, 9, ["cousin", "twins"], "This is my cousin. They are twins!"),
    (4, 10, ["He", "man", "She", "woman"], "He is a man. She is a woman."),
    (4, 11, ["brother", "sister"], "He is my brother. She is my sister."),
    (5, 12, ["my", "your"], "This is my bag. Is this your pencil?"),
    (5, 13, ["his", "her"], "This is his book. This is her doll."),
    (5, 14, ["our", "their"], "This is our classroom. This is their house."),
    (6, 15, ["phone", "watch"], "I have got a phone. I have got a watch."),
    (6, 16, ["glasses", "wallet"], "I have got glasses. I have got a wallet."),
    (6, 17, ["key", "umbrella", "camera"], "I have got a key, an umbrella, and a camera."),
    (7, 18, ["eyebrow", "chin"], "This is my eyebrow. This is my chin."),
    (7, 19, ["cheek", "neck"], "This is my cheek. This is my neck."),
    (7, 20, ["elbow", "knee"], "This is my elbow. This is my knee."),
    (8, 21, ["classroom", "board"], "This is my classroom. This is the board."),
    (8, 22, ["playground", "student"], "This is the playground. I am a student."),
    (8, 23, ["principal", "lesson"], "This is the principal. We are in a lesson."),
    (9, 24, ["Stand up", "Sit down"], "Stand up, please. Sit down, please."),
    (9, 25, ["Listen", "Look"], "Listen to the teacher. Look at the board."),
    (9, 26, ["Open your book", "Raise your hand"], "Open your book. Raise your hand."),
    (10, 27, ["Twenty", "Thirty"], "Twenty balloons! Thirty stars!"),
    (10, 28, ["Fifty", "Eighty"], "Fifty flowers! Eighty blocks!"),
    (10, 29, ["hundred"], "One hundred! Hooray!"),
    (11, 30, ["January", "month"], "January is the first month."),
    (11, 31, ["June", "September"], "June is warm. September is back to school."),
    (11, 32, ["December"], "December is a festive month."),
    (12, 33, ["birthday party", "cake"], "It's a birthday party! Here is the cake."),
    (12, 34, ["candle", "present"], "Blow out the candles! Open your present!"),
    (12, 35, ["balloon", "guest"], "Balloons everywhere! Welcome, guests!"),
    (13, 36, ["clock", "o'clock"], "Look at the clock. It is three o'clock."),
    (13, 37, ["half past", "morning"], "It is half past seven in the morning."),
    (13, 38, ["afternoon", "night"], "Afternoon is for playing. Night is for sleeping."),
    (14, 39, ["wake up", "alarm clock"], "My alarm clock rings. I wake up."),
    (14, 40, ["brush my teeth", "get dressed"], "I brush my teeth. I get dressed."),
    (14, 41, ["have breakfast", "go to school"], "I have breakfast. I go to school."),
    (15, 42, ["come home", "do my homework"], "I come home. I do my homework."),
    (15, 43, ["take a shower", "have dinner"], "I take a shower. I have dinner."),
    (15, 44, ["read a book", "go to bed"], "I read a book in my pajamas. I go to bed."),
    (16, 45, ["breakfast", "lunch"], "I eat breakfast. I eat lunch."),
    (16, 46, ["dinner", "snack"], "We eat dinner. I eat a snack."),
    (16, 47, ["healthy food", "water"], "I eat healthy food. I drink water."),
    (17, 48, ["drawing", "painting"], "I like drawing. I like painting."),
    (17, 49, ["singing", "dancing"], "I like singing. I like dancing."),
    (17, 50, ["reading", "cooking"], "I like reading. I like cooking."),
    (18, 51, ["This", "That"], "This is my pencil. That is your bag."),
    (18, 52, ["These", "Those"], "These are my books. Those are yours."),
    (18, 53, ["here", "there"], "Come here! The ball is over there."),
    (19, 54, ["boxes", "watches"], "I have two boxes. He has two watches."),
    (19, 55, ["children", "babies"], "The children play. The babies sleep."),
    (19, 56, ["feet", "men"], "Wash your feet. Two men are talking."),
]
SCENE_MAP = {}
for lesson_num, img_num, bold_words, sentence in SCENE_DATA:
    SCENE_MAP.setdefault(lesson_num, []).append(
        (f"assets/vocab-scenes/level2/{img_num:02d}.jpg", sentence, bold_words)
    )


# Grammar explanation + practice slide pairs (plus optional in-class MCQs),
# inserted after each lesson's vocab and before its dialogue. Defined here,
# not in grammar-hub/level2.json, for the same reason as Level 1: that file
# is what switches on the Hub's Grammar tab, and Grammar is documented as
# starting at Level 3.
GRAMMAR_UNITS = {
    4: {
        "title": "He is / She is",
        "titleAr": "هو... / هي...",
        "explanation": "We use \"he\" for a boy or a man, and \"she\" for a girl or a woman. Both use \"is\": He is... / She is...",
        "explanationAr": "نستخدم he للولد أو الرجل، وshe للبنت أو المرأة. كلاهما يأتي معه is: هو... / هي...",
        "examples": [
            {"en": "He is a man.", "ar": "هو رجل."},
            {"en": "She is a woman.", "ar": "هي امرأة."},
            {"en": "He is my brother.", "ar": "هو أخي."},
            {"en": "She is my sister.", "ar": "هي أختي."},
        ],
    },
    5: {
        "title": "Possessive Adjectives: my, your, his, her, our, their",
        "titleAr": "صفات الملكية: my, your, his, her, our, their",
        "explanation": "A possessive adjective tells us who something belongs to. It always comes before a noun: my book, your bag, his hat, her cat, our house, their car.",
        "explanationAr": "صفة الملكية تخبرنا لمن الشيء. تأتي دائماً قبل الاسم: my كتابي، your كتابك، his كتابه، her كتابها، our كتابنا، their كتابهم. لماذا هذا الدرس مهم؟ لأننا نحتاجه في كل جملة نصف فيها أشياءنا وعائلتنا وأصدقاءنا — بدونه لا نستطيع أن نقول ما هو لنا وما هو للآخرين.",
        "examples": [
            {"en": "This is my school bag.", "ar": "هذه حقيبتي المدرسية."},
            {"en": "Is this your pencil?", "ar": "هل هذا قلمك؟"},
            {"en": "His shirt is blue. Her dress is pink.", "ar": "قميصه أزرق. فستانها وردي."},
            {"en": "Our house is big. Their car is red.", "ar": "بيتنا كبير. سيارتهم حمراء."},
        ],
    },
    6: {
        "title": "Have got (I have...)",
        "titleAr": "أملك / عندي (have got)",
        "explanation": "We use \"have got\" to say what belongs to us: I have got a phone. To ask, we say: Have you got...? Yes, I have. / No, I haven't.",
        "explanationAr": "نستخدم have got لنقول ماذا نملك: I have got a phone (عندي هاتف). وللسؤال نقول: Have you got...? (هل عندك...؟) والإجابة: Yes, I have. / No, I haven't.",
        "examples": [
            {"en": "I have got a watch.", "ar": "عندي ساعة."},
            {"en": "I have got glasses.", "ar": "عندي نظارة."},
            {"en": "Have you got a key?", "ar": "هل عندك مفتاح؟"},
            {"en": "Yes, I have. / No, I haven't.", "ar": "نعم، عندي. / لا، ليس عندي."},
        ],
    },
    13: {
        "title": "Telling Time",
        "titleAr": "قراءة الساعة",
        "explanation": "Ask: What time is it? The short hand shows the hour. When the long hand points to 12, we say o'clock. At 6 we say half past. At 3 we say quarter past. At 9 we say quarter to (the next hour).",
        "explanationAr": "نسأل: What time is it? (كم الساعة؟). العقرب القصير يشير إلى الساعة. عندما يشير العقرب الطويل إلى 12 نقول o'clock (تمام الساعة). عند 6 نقول half past (والنصف). عند 3 نقول quarter past (والربع). عند 9 نقول quarter to (إلا ربع) مع الساعة التالية.",
        "examples": [
            {"en": "It's three o'clock.", "ar": "الساعة الثالثة تماماً."},
            {"en": "It's half past two.", "ar": "الساعة الثانية والنصف."},
            {"en": "It's quarter past four.", "ar": "الساعة الرابعة والربع."},
            {"en": "It's quarter to five.", "ar": "الساعة الخامسة إلا ربع."},
        ],
        "mcq": [
            {"q": "Short hand on 3, long hand on 12. What time is it?", "qAr": "العقرب القصير على 3 والطويل على 12. كم الساعة؟", "options": ["It's three o'clock.", "It's half past three.", "It's quarter past three.", "It's twelve o'clock."], "answer": "It's three o'clock."},
            {"q": "The long hand points to 6. Which phrase do we use?", "qAr": "العقرب الطويل على 6. أي عبارة نستخدم؟", "options": ["half past", "o'clock", "quarter past", "quarter to"], "answer": "half past"},
            {"q": "The long hand points to 3. Which phrase do we use?", "qAr": "العقرب الطويل على 3. أي عبارة نستخدم؟", "options": ["quarter past", "quarter to", "half past", "o'clock"], "answer": "quarter past"},
            {"q": "The long hand points to 9. Which phrase do we use?", "qAr": "العقرب الطويل على 9. أي عبارة نستخدم؟", "options": ["quarter to", "quarter past", "half past", "o'clock"], "answer": "quarter to"},
            {"q": "Short hand on 7, long hand on 6. What time is it?", "qAr": "القصير على 7 والطويل على 6. كم الساعة؟", "options": ["It's half past seven.", "It's seven o'clock.", "It's half past six.", "It's quarter to seven."], "answer": "It's half past seven."},
            {"q": "How many minutes are in one hour?", "qAr": "كم دقيقة في الساعة الواحدة؟", "options": ["sixty", "thirty", "fifteen", "one hundred"], "answer": "sixty"},
            {"q": "How many minutes is 'quarter past'?", "qAr": "كم دقيقة تعني quarter past؟", "options": ["fifteen", "thirty", "forty-five", "sixty"], "answer": "fifteen"},
            {"q": "What do we call twelve o'clock in the day?", "qAr": "ماذا نسمي الساعة 12 في النهار؟", "options": ["noon", "midnight", "evening", "morning"], "answer": "noon"},
            {"q": "What do we call twelve o'clock at night?", "qAr": "ماذا نسمي الساعة 12 في الليل؟", "options": ["midnight", "noon", "afternoon", "morning"], "answer": "midnight"},
            {"q": "Which question asks for the time?", "qAr": "أي سؤال يسأل عن الوقت؟", "options": ["What time is it?", "How old are you?", "Where is the clock?", "What day is it?"], "answer": "What time is it?"},
        ],
    },
    17: {
        "title": "Verb + -ing = a noun (an activity)",
        "titleAr": "الفعل + ing = اسم (نشاط)",
        "explanation": "Add -ing to a verb and it becomes the NAME of an activity, so we can use it like a noun: draw -> drawing, sing -> singing. That's why we say \"I like drawing\" (not \"I like draw\"). Spelling: run -> running (double the last letter), dance -> dancing (drop the e).",
        "explanationAr": "عندما نضيف ing إلى الفعل يصبح اسماً للنشاط، فنستخدمه مثل الاسم: draw (يرسم) → drawing (الرسم)، sing (يغني) → singing (الغناء). لذلك نقول I like drawing وليس I like draw. الإملاء: run → running (نضاعف الحرف الأخير)، dance → dancing (نحذف e).",
        "examples": [
            {"en": "I like drawing.", "ar": "أحب الرسم."},
            {"en": "Do you like singing?", "ar": "هل تحب الغناء؟"},
            {"en": "Reading is fun.", "ar": "القراءة ممتعة."},
            {"en": "Cooking is my favorite.", "ar": "الطبخ هو المفضل لدي."},
        ],
        "mcq": [
            {"q": "draw -> ?", "qAr": "draw → ؟", "options": ["drawing", "drawe", "drawin", "drawwing"], "answer": "drawing"},
            {"q": "sing -> ?", "qAr": "sing → ؟", "options": ["singing", "singe", "sining", "singng"], "answer": "singing"},
            {"q": "dance -> ?", "qAr": "dance → ؟ (نحذف e)", "options": ["dancing", "danceing", "dancng", "danceng"], "answer": "dancing"},
            {"q": "run -> ?", "qAr": "run → ؟ (نضاعف الحرف الأخير)", "options": ["running", "runing", "runng", "runnig"], "answer": "running"},
            {"q": "swim -> ?", "qAr": "swim → ؟", "options": ["swimming", "swiming", "swimng", "swimeing"], "answer": "swimming"},
            {"q": "I like ___ .", "qAr": "أحب ___ .", "options": ["reading", "read", "reads", "readed"], "answer": "reading"},
            {"q": "___ is fun!", "qAr": "___ ممتع!", "options": ["Painting", "Paint", "Paints", "Painted"], "answer": "Painting"},
            {"q": "Do you like ___ ?", "qAr": "هل تحب ___ ؟", "options": ["cooking", "cook", "cooks", "cooked"], "answer": "cooking"},
            {"q": "Which word is an activity (a noun)?", "qAr": "أي كلمة اسم نشاط؟", "options": ["swimming", "swim", "swims", "swam"], "answer": "swimming"},
            {"q": "write -> ?", "qAr": "write → ؟ (نحذف e)", "options": ["writing", "writeing", "writng", "writting"], "answer": "writing"},
        ],
    },
    18: {
        "title": "This / That / These / Those",
        "titleAr": "هذا / ذلك / هؤلاء / أولئك",
        "explanation": "This = one thing near me. That = one thing far from me. These = many things near me. Those = many things far from me. Near: this / these. Far: that / those. One: this / that. Many: these / those.",
        "explanationAr": "This = شيء واحد قريب مني. That = شيء واحد بعيد عني. These = أشياء كثيرة قريبة. Those = أشياء كثيرة بعيدة. القريب: this / these. البعيد: that / those. المفرد: this / that. الجمع: these / those.",
        "examples": [
            {"en": "This is my book. (near, one)", "ar": "هذا كتابي. (قريب، واحد)"},
            {"en": "That is your book. (far, one)", "ar": "ذلك كتابك. (بعيد، واحد)"},
            {"en": "These are my pens. (near, many)", "ar": "هذه أقلامي. (قريب، كثير)"},
            {"en": "Those are your pens. (far, many)", "ar": "تلك أقلامك. (بعيد، كثير)"},
        ],
        "mcq": [
            {"q": "One apple in my hand: ___ is an apple.", "qAr": "تفاحة واحدة في يدي:", "options": ["This", "That", "These", "Those"], "answer": "This"},
            {"q": "One bird far in the sky: ___ is a bird.", "qAr": "طائر واحد بعيد في السماء:", "options": ["That", "This", "These", "Those"], "answer": "That"},
            {"q": "Two books on my desk: ___ are my books.", "qAr": "كتابان على مكتبي:", "options": ["These", "Those", "This", "That"], "answer": "These"},
            {"q": "Many stars far away: ___ are stars.", "qAr": "نجوم كثيرة بعيدة:", "options": ["Those", "These", "This", "That"], "answer": "Those"},
            {"q": "Near + many = ?", "qAr": "قريب + جمع = ؟", "options": ["these", "those", "this", "that"], "answer": "these"},
            {"q": "Far + one = ?", "qAr": "بعيد + مفرد = ؟", "options": ["that", "this", "these", "those"], "answer": "that"},
        ],
    },
    19: {
        "title": "Plurals: one -> many",
        "titleAr": "الجمع: من المفرد إلى الجمع",
        "explanation": "To talk about more than one, we change the noun. Most nouns add -s. Some add -es. Some change -y to -ies. And a few irregular nouns change completely.",
        "explanationAr": "للحديث عن أكثر من واحد نغير الاسم. معظم الأسماء تأخذ s. بعضها يأخذ es. بعضها تتحول فيه y إلى ies. وقليل منها شاذ يتغير كلياً.",
        "rules": [
            {"en": "Most nouns: add -s", "ar": "معظم الأسماء: نضيف s", "examples": ["cat -> cats", "book -> books", "car -> cars"]},
            {"en": "Ends in -s, -x, -ch, -sh: add -es", "ar": "ينتهي بـ s أو x أو ch أو sh: نضيف es", "examples": ["box -> boxes", "watch -> watches", "bus -> buses", "dish -> dishes"]},
            {"en": "Consonant + y: change y -> ies", "ar": "حرف ساكن + y: نحول y إلى ies", "examples": ["baby -> babies", "city -> cities", "fly -> flies"]},
            {"en": "Vowel + y: just add -s", "ar": "حرف علة + y: نضيف s فقط", "examples": ["boy -> boys", "day -> days", "key -> keys"]},
            {"en": "Irregular: the word changes", "ar": "شاذ: الكلمة تتغير", "examples": ["child -> children", "man -> men", "foot -> feet", "tooth -> teeth", "mouse -> mice"]},
            {"en": "Same word for one and many", "ar": "نفس الكلمة للمفرد والجمع", "examples": ["sheep -> sheep", "fish -> fish"]},
        ],
        "examples": [
            {"en": "I have two cats and three boxes.", "ar": "عندي قطتان وثلاثة صناديق."},
            {"en": "The babies are sleeping.", "ar": "الأطفال الرضع نائمون."},
            {"en": "The children have two feet.", "ar": "الأطفال لديهم قدمان."},
            {"en": "Three men and two women are here.", "ar": "ثلاثة رجال وامرأتان هنا."},
        ],
        "mcq": [
            {"q": "box -> ?", "options": ["boxes", "boxs", "boxies", "box"], "answer": "boxes"},
            {"q": "baby -> ?", "options": ["babies", "babys", "babyes", "baby"], "answer": "babies"},
            {"q": "boy -> ?", "options": ["boys", "boies", "boyes", "boy"], "answer": "boys"},
            {"q": "child -> ?", "options": ["children", "childs", "childes", "childies"], "answer": "children"},
            {"q": "foot -> ?", "options": ["feet", "foots", "footes", "feets"], "answer": "feet"},
            {"q": "watch -> ?", "options": ["watches", "watchs", "watchies", "watch"], "answer": "watches"},
            {"q": "man -> ?", "options": ["men", "mans", "manes", "mens"], "answer": "men"},
            {"q": "sheep -> ?", "options": ["sheep", "sheeps", "sheepes", "shep"], "answer": "sheep"},
        ],
    },
}

run("level2", DIALOGUES, PHONICS_UNITS, grammar_units=GRAMMAR_UNITS, theme_map=THEME_MAP, scene_map=SCENE_MAP)
