# -*- coding: utf-8 -*-
import json, os

LESSONS = [
  {"title": "Does She Even Sleep?", "titleAr": "هل تنام حتى؟",
   "goal": "I can ask and answer yes/no questions about routines.",
   "grammarFocus": "Present Simple Questions (Do/Does)",
   "vocab": [
     {"en": "wake up", "ar": "يستيقظ", "example": "Does he wake up early?"},
     {"en": "study", "ar": "يدرس", "example": "Do you study every night?"},
     {"en": "practice", "ar": "يتمرن", "example": "Does she practice every day?"},
     {"en": "hang out", "ar": "يقضي وقتا مع الأصدقاء", "example": "Do they hang out on weekends?"},
     {"en": "relax", "ar": "يسترخي", "example": "Does he ever relax?"},
     {"en": "chill", "ar": "يسترخي (عامية)", "example": "Do you like to chill after school?"},
   ]},
  {"title": "My Routine, My Rules", "titleAr": "روتيني، قواعدي",
   "goal": "I can describe my own daily routine.",
   "grammarFocus": "Present Simple for Routines",
   "vocab": [
     {"en": "schedule", "ar": "جدول", "example": "My schedule is full today."},
     {"en": "deadline", "ar": "موعد نهائي", "example": "I have a deadline tomorrow."},
     {"en": "workout", "ar": "تمرين رياضي", "example": "I do a workout every morning."},
     {"en": "homework", "ar": "واجب منزلي", "example": "I finish my homework after dinner."},
     {"en": "screen time", "ar": "وقت الشاشة", "example": "My screen time is limited."},
     {"en": "bedtime", "ar": "وقت النوم", "example": "My bedtime is 10 pm."},
   ]},
  {"title": "How Often Do You...?", "titleAr": "كم مرة تفعل...؟",
   "goal": "I can say how often I do things.",
   "grammarFocus": "Adverbs of Frequency",
   "vocab": [
     {"en": "daily", "ar": "يوميا", "example": "I check messages daily."},
     {"en": "weekly", "ar": "أسبوعيا", "example": "We have a test weekly."},
     {"en": "rarely", "ar": "نادرا", "example": "I rarely watch TV."},
     {"en": "constantly", "ar": "باستمرار", "example": "She is constantly texting."},
     {"en": "occasionally", "ar": "أحيانا", "example": "I occasionally play video games."},
     {"en": "never", "ar": "أبدا", "example": "He never skips practice."},
   ]},
  {"title": "Before and After", "titleAr": "قبل وبعد",
   "goal": "I can talk about when things happen.",
   "grammarFocus": "Prepositions of Time",
   "vocab": [
     {"en": "appointment", "ar": "موعد", "example": "I have an appointment at 5."},
     {"en": "deadline", "ar": "موعد نهائي", "example": "The deadline is on Friday."},
     {"en": "weekend", "ar": "عطلة نهاية الأسبوع", "example": "We're free on the weekend."},
     {"en": "holiday", "ar": "عطلة", "example": "School starts after the holiday."},
     {"en": "semester", "ar": "فصل دراسي", "example": "This semester is busy."},
     {"en": "break", "ar": "استراحة", "example": "We have a short break at 10."},
   ]},
  {"title": "Text Me", "titleAr": "راسلني",
   "goal": "I can talk about staying in touch with friends.",
   "grammarFocus": "Object Pronouns",
   "vocab": [
     {"en": "message", "ar": "رسالة", "example": "Send it to me."},
     {"en": "reply", "ar": "يرد", "example": "I will reply to her."},
     {"en": "call", "ar": "يتصل", "example": "Call him tonight."},
     {"en": "invite", "ar": "يدعو", "example": "Invite them to the party."},
     {"en": "meet", "ar": "يقابل", "example": "Let's meet them later."},
     {"en": "video chat", "ar": "مكالمة فيديو", "example": "I video chat with her every week."},
   ]},
  {"title": "That's Mine", "titleAr": "هذا لي",
   "goal": "I can say what belongs to me and to others.",
   "grammarFocus": "Possessive Pronouns (mine, yours, his, hers)",
   "vocab": [
     {"en": "earbuds", "ar": "سماعات أذن", "example": "Are these earbuds yours?"},
     {"en": "jacket", "ar": "سترة", "example": "That jacket is mine."},
     {"en": "notebook", "ar": "دفتر", "example": "This notebook is hers."},
     {"en": "wallet", "ar": "محفظة", "example": "Is this wallet his?"},
     {"en": "sneakers", "ar": "حذاء رياضي", "example": "Those sneakers are ours."},
     {"en": "bike", "ar": "دراجة", "example": "That bike is theirs."},
   ]},
  {"title": "Got Any Snacks?", "titleAr": "هل لديك وجبات خفيفة؟",
   "goal": "I can ask about food using some and any.",
   "grammarFocus": "Some / Any",
   "vocab": [
     {"en": "snack", "ar": "وجبة خفيفة", "example": "Do we have any snacks?"},
     {"en": "leftovers", "ar": "بقايا الطعام", "example": "There are some leftovers."},
     {"en": "groceries", "ar": "مشتريات البقالة", "example": "We need to buy some groceries."},
     {"en": "fridge", "ar": "ثلاجة", "example": "Is there any juice in the fridge?"},
     {"en": "pantry", "ar": "مخزن المؤن", "example": "There is some rice in the pantry."},
     {"en": "ingredients", "ar": "مكونات", "example": "Do we have any ingredients for pizza?"},
   ]},
  {"title": "How Much Is That?", "titleAr": "بكم هذا؟",
   "goal": "I can ask about quantity and price.",
   "grammarFocus": "Countable & Uncountable / How much, How many",
   "vocab": [
     {"en": "allowance", "ar": "مصروف", "example": "How much allowance do you get?"},
     {"en": "price tag", "ar": "بطاقة السعر", "example": "Check the price tag."},
     {"en": "discount", "ar": "خصم", "example": "There is a discount today."},
     {"en": "receipt", "ar": "إيصال", "example": "Keep the receipt."},
     {"en": "budget", "ar": "ميزانية", "example": "How much is my budget?"},
     {"en": "savings", "ar": "مدخرات", "example": "How much are your savings?"},
   ]},
  {"title": "Saving Up", "titleAr": "الادخار",
   "goal": "I can talk about earning, saving, and spending money.",
   "grammarFocus": "Countable & Uncountable (review)",
   "vocab": [
     {"en": "save", "ar": "يدخر", "example": "I save some money every week."},
     {"en": "spend", "ar": "ينفق", "example": "Don't spend it all."},
     {"en": "earn", "ar": "يكسب", "example": "I earn money doing chores."},
     {"en": "borrow", "ar": "يقترض", "example": "Can I borrow some money?"},
     {"en": "lend", "ar": "يقرض", "example": "She lent me some money."},
     {"en": "coins", "ar": "عملات معدنية", "example": "I have some coins in my pocket."},
   ]},
  {"title": "Best in Show", "titleAr": "الأفضل على الإطلاق",
   "goal": "I can describe the best of a group.",
   "grammarFocus": "Superlatives (the biggest, the best)",
   "vocab": [
     {"en": "talented", "ar": "موهوب", "example": "She is the most talented singer."},
     {"en": "skilled", "ar": "ماهر", "example": "He is the most skilled player."},
     {"en": "impressive", "ar": "مبهر", "example": "That was the most impressive goal."},
     {"en": "outstanding", "ar": "متميز", "example": "This is the most outstanding project."},
     {"en": "popular", "ar": "شهير", "example": "She is the most popular student."},
     {"en": "unique", "ar": "فريد", "example": "This is the most unique idea."},
   ]},
  {"title": "I'd Like...", "titleAr": "أريد...",
   "goal": "I can politely ask for what I want.",
   "grammarFocus": "Would like / Want (polite requests)",
   "vocab": [
     {"en": "order", "ar": "يطلب", "example": "I would like to order a pizza."},
     {"en": "request", "ar": "يطلب رسميا", "example": "I have a request."},
     {"en": "prefer", "ar": "يفضل", "example": "I prefer tea to coffee."},
     {"en": "suggest", "ar": "يقترح", "example": "I suggest we go early."},
     {"en": "recommend", "ar": "يوصي", "example": "What do you recommend?"},
     {"en": "choice", "ar": "خيار", "example": "What's your choice?"},
   ]},
  {"title": "You Should Try This", "titleAr": "يجب أن تجرب هذا",
   "goal": "I can give and receive advice.",
   "grammarFocus": "Should / Shouldn't (advice)",
   "vocab": [
     {"en": "advice", "ar": "نصيحة", "example": "Can I give you some advice?"},
     {"en": "opinion", "ar": "رأي", "example": "In my opinion, you should try it."},
     {"en": "suggestion", "ar": "اقتراح", "example": "I have a suggestion."},
     {"en": "warning", "ar": "تحذير", "example": "This is a warning, not advice."},
     {"en": "tip", "ar": "نصيحة سريعة", "example": "Here's a useful tip."},
     {"en": "habit", "ar": "عادة", "example": "You should break that habit."},
   ]},
  {"title": "Group Chat", "titleAr": "دردشة جماعية",
   "goal": "I can talk about online communication.",
   "grammarFocus": "Present Simple (review, online habits)",
   "vocab": [
     {"en": "post", "ar": "منشور", "example": "She posts every day."},
     {"en": "comment", "ar": "تعليق", "example": "I leave a comment."},
     {"en": "share", "ar": "يشارك", "example": "He shares funny videos."},
     {"en": "like", "ar": "إعجاب", "example": "I like her photo."},
     {"en": "notification", "ar": "إشعار", "example": "I got a notification."},
     {"en": "online", "ar": "متصل بالإنترنت", "example": "Are you online now?"},
   ]},
  {"title": "Team Player", "titleAr": "لاعب الفريق",
   "goal": "I can talk about working well with others.",
   "grammarFocus": "Should/Shouldn't (review, teamwork)",
   "vocab": [
     {"en": "cooperate", "ar": "يتعاون", "example": "We should cooperate more."},
     {"en": "contribute", "ar": "يساهم", "example": "Everyone should contribute."},
     {"en": "support", "ar": "يدعم", "example": "We support each other."},
     {"en": "encourage", "ar": "يشجع", "example": "You should encourage your teammates."},
     {"en": "teamwork", "ar": "العمل الجماعي", "example": "Teamwork is important."},
     {"en": "leader", "ar": "قائد", "example": "She is a great leader."},
   ]},
  {"title": "Big Decisions", "titleAr": "قرارات مهمة",
   "goal": "I can talk about making choices.",
   "grammarFocus": "Would like / Want (review, choices)",
   "vocab": [
     {"en": "decide", "ar": "يقرر", "example": "I need to decide soon."},
     {"en": "option", "ar": "خيار", "example": "There are two options."},
     {"en": "consider", "ar": "يفكر بجدية", "example": "I will consider it."},
     {"en": "consequence", "ar": "نتيجة", "example": "Think about the consequence."},
     {"en": "compromise", "ar": "حل وسط", "example": "Let's find a compromise."},
     {"en": "choice", "ar": "خيار", "example": "It's a big choice."},
   ]},
  {"title": "Under Pressure", "titleAr": "تحت الضغط",
   "goal": "I can talk about my feelings in stressful moments.",
   "grammarFocus": "Adverbs of Frequency (review, feelings)",
   "vocab": [
     {"en": "nervous", "ar": "متوتر", "example": "I always feel nervous before tests."},
     {"en": "confident", "ar": "واثق", "example": "She usually feels confident."},
     {"en": "calm", "ar": "هادئ", "example": "He stays calm under pressure."},
     {"en": "anxious", "ar": "قلق", "example": "I sometimes feel anxious."},
     {"en": "relieved", "ar": "مرتاح", "example": "I feel relieved after the exam."},
     {"en": "proud", "ar": "فخور", "example": "I am proud of myself."},
   ]},
  {"title": "My Future Self", "titleAr": "نفسي في المستقبل",
   "goal": "I can talk about my goals and dreams.",
   "grammarFocus": "Would like / Want (review, future goals)",
   "vocab": [
     {"en": "goal", "ar": "هدف", "example": "My goal is to learn coding."},
     {"en": "dream", "ar": "حلم", "example": "That's my biggest dream."},
     {"en": "ambition", "ar": "طموح", "example": "She has a lot of ambition."},
     {"en": "career", "ar": "مهنة", "example": "What career do you want?"},
     {"en": "passion", "ar": "شغف", "example": "Art is my passion."},
     {"en": "achieve", "ar": "يحقق", "example": "I want to achieve my goals."},
   ]},
  {"title": "Around the World", "titleAr": "حول العالم",
   "goal": "I can talk about different cultures and places.",
   "grammarFocus": "Present Simple (review, cultures)",
   "vocab": [
     {"en": "culture", "ar": "ثقافة", "example": "Every country has its own culture."},
     {"en": "tradition", "ar": "تقليد", "example": "This is an old tradition."},
     {"en": "language", "ar": "لغة", "example": "How many languages do you speak?"},
     {"en": "custom", "ar": "عادة", "example": "It's a local custom."},
     {"en": "explore", "ar": "يستكشف", "example": "I want to explore new places."},
     {"en": "journey", "ar": "رحلة", "example": "It was an amazing journey."},
   ]},
  {"title": "Reading Adventure: The Group Project", "titleAr": "مغامرة قرائية: المشروع الجماعي",
   "goal": "I can read and understand a short story about teamwork and problem-solving.",
   "grammarFocus": "Reading comprehension review",
   "vocab": [
     {"en": "project", "ar": "مشروع", "example": "We have a group project this week."},
     {"en": "deadline", "ar": "موعد نهائي", "example": "Our deadline is Friday."},
     {"en": "disagree", "ar": "يختلف", "example": "At first, they disagree."},
     {"en": "compromise", "ar": "حل وسط", "example": "They find a compromise."},
     {"en": "teamwork", "ar": "العمل الجماعي", "example": "Teamwork saves the day."},
     {"en": "proud", "ar": "فخور", "example": "The team feels proud."},
   ]},
  {"title": "Review + Future Plans Project", "titleAr": "مراجعة + مشروع خططي المستقبلية",
   "goal": "I can talk about my routine, money, friendships, and future using everything I've learned.",
   "grammarFocus": "Review of all structures from Lessons 1-19",
   "vocab": [
     {"en": "schedule", "ar": "جدول", "example": "My schedule is full today."},
     {"en": "message", "ar": "رسالة", "example": "Send it to me."},
     {"en": "budget", "ar": "ميزانية", "example": "How much is my budget?"},
     {"en": "talented", "ar": "موهوب", "example": "She is the most talented singer."},
     {"en": "advice", "ar": "نصيحة", "example": "Can I give you some advice?"},
     {"en": "teamwork", "ar": "العمل الجماعي", "example": "Teamwork is important."},
     {"en": "goal", "ar": "هدف", "example": "My goal is to learn coding."},
     {"en": "journey", "ar": "رحلة", "example": "It was an amazing journey."},
   ]},
]

OUT_DIR = "lessons/level4"
os.makedirs(OUT_DIR, exist_ok=True)
for old in os.listdir(OUT_DIR):
    os.remove(os.path.join(OUT_DIR, old))

for i, L in enumerate(LESSONS, start=1):
    num = f"{i:02d}"
    lesson = {
        "id": f"level4-{num}", "level": "level4", "number": i,
        "title": L["title"], "titleAr": L["titleAr"], "goal": L["goal"],
        "grammarFocus": L["grammarFocus"], "vocab": L["vocab"],
        "activities": [
            {"type": "vocab"}, {"type": "speak", "rounds": 3},
            {"type": "listen-choose", "rounds": 6}, {"type": "match"},
            {"type": "quiz", "rounds": 4}, {"type": "spell", "rounds": 3},
        ],
    }
    with open(os.path.join(OUT_DIR, f"lesson{num}.json"), "w", encoding="utf-8") as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)
        f.write("\n")

print(f"Wrote {len(LESSONS)} lesson files to {OUT_DIR}/")
