# -*- coding: utf-8 -*-
import json, os

LESSONS = [
  {"title": "My Plans", "titleAr": "خططي",
   "goal": "I can talk about my plans using 'going to'.",
   "grammarFocus": "Going to (Future Plans)",
   "vocab": [
     {"en": "plan", "ar": "يخطط", "example": "I'm going to plan a trip."},
     {"en": "visit", "ar": "يزور", "example": "We're going to visit my cousins."},
     {"en": "join", "ar": "ينضم", "example": "She's going to join the team."},
     {"en": "apply", "ar": "يتقدم بطلب", "example": "He's going to apply for a job."},
     {"en": "move", "ar": "ينتقل", "example": "They're going to move to a new city."},
     {"en": "start", "ar": "يبدأ", "example": "I'm going to start a new hobby."},
   ]},
  {"title": "I Think It Will...", "titleAr": "أعتقد أنه سوف...",
   "goal": "I can make predictions about the future using 'will'.",
   "grammarFocus": "Will (Future Predictions)",
   "vocab": [
     {"en": "predict", "ar": "يتنبأ", "example": "I predict it will rain."},
     {"en": "probably", "ar": "على الأرجح", "example": "It will probably be sunny."},
     {"en": "definitely", "ar": "بالتأكيد", "example": "She will definitely win."},
     {"en": "maybe", "ar": "ربما", "example": "Maybe he will come."},
     {"en": "future", "ar": "المستقبل", "example": "What will the future look like?"},
     {"en": "believe", "ar": "يعتقد", "example": "I believe it will work out."},
   ]},
  {"title": "This Weekend I'm...", "titleAr": "في نهاية هذا الأسبوع سأكون...",
   "goal": "I can talk about fixed future plans using Present Continuous.",
   "grammarFocus": "Present Continuous for Future Plans",
   "vocab": [
     {"en": "meeting", "ar": "يقابل", "example": "I'm meeting my friend on Friday."},
     {"en": "traveling", "ar": "يسافر", "example": "We're traveling next week."},
     {"en": "attending", "ar": "يحضر", "example": "She's attending a concert."},
     {"en": "leaving", "ar": "يغادر", "example": "They're leaving on Sunday."},
     {"en": "starting", "ar": "يبدأ", "example": "I'm starting school on Monday."},
     {"en": "hosting", "ar": "يستضيف", "example": "We're hosting a party this weekend."},
   ]},
  {"title": "While I Was...", "titleAr": "بينما كنت...",
   "goal": "I can describe one action interrupting another in the past.",
   "grammarFocus": "Past Continuous (full)",
   "vocab": [
     {"en": "interrupted", "ar": "قاطع", "example": "My phone rang while I was studying."},
     {"en": "noticed", "ar": "لاحظ", "example": "I noticed him while I was walking."},
     {"en": "happened", "ar": "حدث", "example": "It happened while we were talking."},
     {"en": "arrived", "ar": "وصل", "example": "She arrived while we were eating."},
     {"en": "started raining", "ar": "بدأ المطر", "example": "It started raining while we were outside."},
     {"en": "meanwhile", "ar": "في هذه الأثناء", "example": "Meanwhile, I was finishing my homework."},
   ]},
  {"title": "Rules & Duties", "titleAr": "القواعد والواجبات",
   "goal": "I can talk about what's necessary and what isn't.",
   "grammarFocus": "Have to / Don't have to",
   "vocab": [
     {"en": "have to", "ar": "يجب", "example": "I have to finish my homework."},
     {"en": "don't have to", "ar": "لا يجب", "example": "You don't have to come if you're busy."},
     {"en": "required", "ar": "مطلوب", "example": "A uniform is required at school."},
     {"en": "optional", "ar": "اختياري", "example": "The extra class is optional."},
     {"en": "responsibility", "ar": "مسؤولية", "example": "It's my responsibility to help at home."},
     {"en": "duty", "ar": "واجب", "example": "It's a student's duty to study."},
   ]},
  {"title": "How You Do It", "titleAr": "كيف تفعل ذلك",
   "goal": "I can describe how an action is done using adverbs of manner.",
   "grammarFocus": "Adverbs of Manner",
   "vocab": [
     {"en": "quickly", "ar": "بسرعة", "example": "She finished the test quickly."},
     {"en": "carefully", "ar": "بحذر", "example": "He carefully carried the box."},
     {"en": "quietly", "ar": "بهدوء", "example": "They walked in quietly."},
     {"en": "loudly", "ar": "بصوت عالٍ", "example": "He spoke loudly."},
     {"en": "easily", "ar": "بسهولة", "example": "She easily solved the problem."},
     {"en": "patiently", "ar": "بصبر", "example": "The teacher waited patiently."},
   ]},
  {"title": "Even Better", "titleAr": "أفضل حتى",
   "goal": "I can compare things using longer adjectives.",
   "grammarFocus": "Comparatives & Superlatives with Long Adjectives",
   "vocab": [
     {"en": "more interesting", "ar": "أكثر إثارة", "example": "This book is more interesting than that one."},
     {"en": "more difficult", "ar": "أصعب", "example": "Math is more difficult than art for me."},
     {"en": "more expensive", "ar": "أغلى", "example": "This phone is more expensive."},
     {"en": "the most popular", "ar": "الأكثر شهرة", "example": "She's the most popular student."},
     {"en": "the most exciting", "ar": "الأكثر إثارة", "example": "That was the most exciting game."},
     {"en": "the most comfortable", "ar": "الأكثر راحة", "example": "This chair is the most comfortable."},
   ]},
  {"title": "Weekend Plans", "titleAr": "خطط نهاية الأسبوع",
   "goal": "I can compare and plan weekend activities.",
   "grammarFocus": "Going to (review)",
   "vocab": [
     {"en": "hang out", "ar": "يقضي وقتا", "example": "We're going to hang out at the mall."},
     {"en": "sleep in", "ar": "ينام متأخرا", "example": "I'm going to sleep in on Saturday."},
     {"en": "catch up", "ar": "يلحق بـ", "example": "I'm going to catch up on homework."},
     {"en": "relax", "ar": "يسترخي", "example": "We're going to relax at home."},
     {"en": "explore", "ar": "يستكشف", "example": "They're going to explore downtown."},
     {"en": "volunteer", "ar": "يتطوع", "example": "She's going to volunteer this weekend."},
   ]},
  {"title": "Predictions About Us", "titleAr": "توقعات عنا",
   "goal": "I can make predictions about my classmates and future.",
   "grammarFocus": "Will (review)",
   "vocab": [
     {"en": "succeed", "ar": "ينجح", "example": "I think he will succeed."},
     {"en": "graduate", "ar": "يتخرج", "example": "We will graduate next year."},
     {"en": "travel", "ar": "يسافر", "example": "She will probably travel a lot."},
     {"en": "invent", "ar": "يخترع", "example": "Maybe he will invent something new."},
     {"en": "achieve", "ar": "يحقق", "example": "I believe she will achieve her goals."},
     {"en": "change", "ar": "يتغير", "example": "Things will change a lot."},
   ]},
  {"title": "Rules at Home", "titleAr": "القواعد في المنزل",
   "goal": "I can talk about responsibilities at home.",
   "grammarFocus": "Have to / Don't have to (review)",
   "vocab": [
     {"en": "chores", "ar": "أعمال منزلية", "example": "I have to do my chores."},
     {"en": "curfew", "ar": "موعد العودة", "example": "I have to be home by curfew."},
     {"en": "permission", "ar": "إذن", "example": "I have to ask for permission."},
     {"en": "allowed", "ar": "مسموح", "example": "I'm allowed to go out on weekends."},
     {"en": "trust", "ar": "ثقة", "example": "My parents trust me."},
     {"en": "independent", "ar": "مستقل", "example": "I'm becoming more independent."},
   ]},
  {"title": "The Way We Talk", "titleAr": "طريقة حديثنا",
   "goal": "I can describe how people communicate using adverbs.",
   "grammarFocus": "Adverbs of Manner (review)",
   "vocab": [
     {"en": "clearly", "ar": "بوضوح", "example": "She explained it clearly."},
     {"en": "politely", "ar": "بأدب", "example": "He answered politely."},
     {"en": "honestly", "ar": "بصدق", "example": "Tell me honestly what you think."},
     {"en": "nervously", "ar": "بتوتر", "example": "She spoke nervously."},
     {"en": "confidently", "ar": "بثقة", "example": "He presented confidently."},
     {"en": "kindly", "ar": "بلطف", "example": "The teacher kindly helped me."},
   ]},
  {"title": "Which Is Better?", "titleAr": "أيهما أفضل؟",
   "goal": "I can compare options and give my opinion.",
   "grammarFocus": "Comparatives & Superlatives (review)",
   "vocab": [
     {"en": "option", "ar": "خيار", "example": "This is the more practical option."},
     {"en": "reasonable", "ar": "معقول", "example": "That price is more reasonable."},
     {"en": "convenient", "ar": "مناسب", "example": "This time is more convenient."},
     {"en": "the most useful", "ar": "الأكثر فائدة", "example": "This app is the most useful."},
     {"en": "the most reliable", "ar": "الأكثر موثوقية", "example": "This is the most reliable option."},
     {"en": "worth it", "ar": "يستحق", "example": "I think it's worth it."},
   ]},
  {"title": "Multitasking", "titleAr": "تعدد المهام",
   "goal": "I can describe two things happening in the past at once.",
   "grammarFocus": "Past Continuous (review, multitasking)",
   "vocab": [
     {"en": "was cooking", "ar": "كان يطبخ", "example": "I was cooking while listening to music."},
     {"en": "was chatting", "ar": "كان يتحدث", "example": "She was chatting while doing homework."},
     {"en": "was driving", "ar": "كان يقود", "example": "He was driving while talking on the phone."},
     {"en": "were studying", "ar": "كانوا يدرسون", "example": "We were studying while eating snacks."},
     {"en": "was scrolling", "ar": "كان يتصفح", "example": "I was scrolling while watching TV."},
     {"en": "focus", "ar": "يركز", "example": "It's hard to focus on two things."},
   ]},
  {"title": "Next Year", "titleAr": "العام القادم",
   "goal": "I can talk about my plans and predictions for next year.",
   "grammarFocus": "Going to / Will (mixed review)",
   "vocab": [
     {"en": "goal", "ar": "هدف", "example": "My goal is going to be reading more."},
     {"en": "improve", "ar": "يتحسن", "example": "I will improve my grades."},
     {"en": "challenge myself", "ar": "يتحدى نفسه", "example": "I'm going to challenge myself."},
     {"en": "expect", "ar": "يتوقع", "example": "I expect it will be a good year."},
     {"en": "hope", "ar": "يأمل", "example": "I hope things will go well."},
     {"en": "resolution", "ar": "قرار", "example": "That's my resolution for next year."},
   ]},
  {"title": "Class Debate", "titleAr": "مناظرة الصف",
   "goal": "I can compare two sides of an argument politely.",
   "grammarFocus": "Comparatives (debate context)",
   "vocab": [
     {"en": "argue", "ar": "يجادل", "example": "I would argue that this is better."},
     {"en": "point of view", "ar": "وجهة نظر", "example": "That's an interesting point of view."},
     {"en": "convince", "ar": "يقنع", "example": "Can you convince me?"},
     {"en": "evidence", "ar": "دليل", "example": "Do you have any evidence?"},
     {"en": "agree partly", "ar": "يوافق جزئيا", "example": "I agree partly with that."},
     {"en": "fair point", "ar": "نقطة عادلة", "example": "That's a fair point."},
   ]},
  {"title": "Getting Ready", "titleAr": "الاستعداد",
   "goal": "I can talk about preparing for a future event.",
   "grammarFocus": "Going to (review, preparation)",
   "vocab": [
     {"en": "prepare", "ar": "يستعد", "example": "I'm going to prepare for the exam."},
     {"en": "practice", "ar": "يتمرن", "example": "We're going to practice every day."},
     {"en": "organize", "ar": "ينظم", "example": "She's going to organize her notes."},
     {"en": "review", "ar": "يراجع", "example": "I'm going to review the whole unit."},
     {"en": "rest", "ar": "يستريح", "example": "I'm going to rest before the big day."},
     {"en": "ready", "ar": "جاهز", "example": "I'll be ready by Monday."},
   ]},
  {"title": "Doing It Right", "titleAr": "فعل الأمر بشكل صحيح",
   "goal": "I can give instructions describing how something should be done.",
   "grammarFocus": "Adverbs of Manner (instructions)",
   "vocab": [
     {"en": "properly", "ar": "بشكل صحيح", "example": "Do it properly the first time."},
     {"en": "safely", "ar": "بأمان", "example": "Cross the street safely."},
     {"en": "neatly", "ar": "بترتيب", "example": "Write your name neatly."},
     {"en": "smoothly", "ar": "بسلاسة", "example": "The project went smoothly."},
     {"en": "efficiently", "ar": "بكفاءة", "example": "She works efficiently."},
     {"en": "correctly", "ar": "بشكل صحيح", "example": "Answer correctly to get points."},
   ]},
  {"title": "Comparing Cultures", "titleAr": "مقارنة الثقافات",
   "goal": "I can compare traditions and lifestyles using long adjectives.",
   "grammarFocus": "Comparatives & Superlatives (culture)",
   "vocab": [
     {"en": "tradition", "ar": "تقليد", "example": "This tradition is more common here."},
     {"en": "custom", "ar": "عادة", "example": "That custom is more unusual to me."},
     {"en": "lifestyle", "ar": "أسلوب حياة", "example": "Their lifestyle is more relaxed."},
     {"en": "the most colorful", "ar": "الأكثر ألوانا", "example": "That festival is the most colorful."},
     {"en": "the most traditional", "ar": "الأكثر تقليدية", "example": "This is the most traditional dish."},
     {"en": "similar", "ar": "مشابه", "example": "Our cultures are similar in some ways."},
   ]},
  {"title": "Reading Adventure: The School Trip", "titleAr": "مغامرة قرائية: الرحلة المدرسية",
   "goal": "I can read and understand a story that mixes past and future plans.",
   "grammarFocus": "Reading comprehension review",
   "vocab": [
     {"en": "field trip", "ar": "رحلة ميدانية", "example": "We're going to a field trip next week."},
     {"en": "excited", "ar": "متحمس", "example": "Everyone was excited."},
     {"en": "unexpected", "ar": "غير متوقع", "example": "Something unexpected happened."},
     {"en": "handled", "ar": "تعامل مع", "example": "The teacher handled it calmly."},
     {"en": "lesson learned", "ar": "درس مستفاد", "example": "There was a lesson learned that day."},
     {"en": "memorable", "ar": "لا يُنسى", "example": "It was a memorable trip."},
   ]},
  {"title": "Review + My Future Plans Project", "titleAr": "مراجعة + مشروع خططي المستقبلية",
   "goal": "I can talk about my past experiences and future plans using everything I've learned.",
   "grammarFocus": "Review of all structures from Lessons 1-19",
   "vocab": [
     {"en": "plan", "ar": "يخطط", "example": "I'm going to plan a trip."},
     {"en": "predict", "ar": "يتنبأ", "example": "I predict it will rain."},
     {"en": "have to", "ar": "يجب", "example": "I have to finish my homework."},
     {"en": "quickly", "ar": "بسرعة", "example": "She finished the test quickly."},
     {"en": "the most exciting", "ar": "الأكثر إثارة", "example": "That was the most exciting game."},
     {"en": "goal", "ar": "هدف", "example": "My goal is going to be reading more."},
     {"en": "memorable", "ar": "لا يُنسى", "example": "It was a memorable trip."},
     {"en": "achieve", "ar": "يحقق", "example": "I believe she will achieve her goals."},
   ]},
]

OUT_DIR = "lessons/level6"
os.makedirs(OUT_DIR, exist_ok=True)
for old in os.listdir(OUT_DIR) if os.path.exists(OUT_DIR) else []:
    os.remove(os.path.join(OUT_DIR, old))

for i, L in enumerate(LESSONS, start=1):
    num = f"{i:02d}"
    lesson = {
        "id": f"level6-{num}", "level": "level6", "number": i,
        "title": L["title"], "titleAr": L["titleAr"], "goal": L["goal"],
        "grammarFocus": L["grammarFocus"], "vocab": L["vocab"],
        "activities": [
            {"type": "vocab"}, {"type": "speak", "rounds": 3},
            {"type": "listen-choose", "rounds": 6}, {"type": "match"},
            {"type": "quiz", "rounds": 4}, {"type": "spell", "rounds": 3},
        ],
    }
    with open(os.path.join(OUT_DIR, f"lesson{num}.json"), "w", encoding="utf-8") as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)
        f.write("\n")

print(f"Wrote {len(LESSONS)} lesson files to {OUT_DIR}/")
