# -*- coding: utf-8 -*-
import sys, json
sys.path.insert(0, "lib")
from deck_template_teen import run
from grammar_slides import compute_grammar_lesson_map

GRAMMAR_UNITS = compute_grammar_lesson_map("level4")

DIALOGUES = {
  1: [("What is your daily routine?", "ما هو روتينك اليومي؟"),
      ("I wake up, brush my teeth, and have breakfast.", "أستيقظ، أنظف أسناني، وأتناول الفطور."),
      ("Then I go to school. What about you?", "ثم أذهب إلى المدرسة. ماذا عنك؟"),
      ("The same! Then I come home and go to bed.", "نفس الشيء! ثم أعود للمنزل وأذهب للنوم.")],
  2: [("What does your brother do every day?", "ماذا يفعل أخوك كل يوم؟"),
      ("He wakes up early and eats breakfast fast.", "يستيقظ باكرا ويأكل الفطور بسرعة."),
      ("Does he play football?", "هل يلعب كرة القدم؟"),
      ("Yes, he plays every afternoon and reads at night.", "نعم، يلعب كل بعد ظهر ويقرأ في الليل.")],
  3: [("How often do you read?", "كم مرة تقرأ؟"),
      ("I always read before bed. What about you?", "أقرأ دائما قبل النوم. ماذا عنك؟"),
      ("I sometimes read. I usually watch TV.", "أقرأ أحيانا. أشاهد التلفاز عادة."),
      ("I rarely watch TV, but I never skip reading!", "نادرا ما أشاهد التلفاز، لكنني لا أتوقف عن القراءة أبدا!")],
  4: [("Let's go to the supermarket.", "لنذهب إلى السوبر ماركت."),
      ("Okay! I want to buy an apple.", "حسنا! أريد شراء تفاحة."),
      ("What is the price?", "ما هو السعر؟"),
      ("It's cheap, not expensive at all!", "إنها رخيصة، ليست غالية أبدا!")],
  5: [("How many apples do you want?", "كم تفاحة تريد؟"),
      ("I want five apples. How much bread do we need?", "أريد خمس تفاحات. كم رغيف خبز نحتاج؟"),
      ("We need two. Do we have any eggs?", "نحتاج اثنين. هل لدينا بيض؟"),
      ("Yes, here is your receipt!", "نعم، وهذا إيصالك!")],
  6: [("Is there any milk?", "هل يوجد حليب؟"),
      ("Yes, and we have some rice too.", "نعم، ولدينا بعض الأرز أيضا."),
      ("Do we have any juice?", "هل لدينا عصير؟"),
      ("No, we don't have any. Let's buy some water.", "لا، ليس لدينا. لنشتري بعض الماء.")],
  7: [("How much does this cost?", "كم يكلف هذا؟"),
      ("It costs one dollar. Do you have a coin?", "يكلف دولارا واحدا. هل لديك عملة معدنية؟"),
      ("Yes, here. Can I pay now?", "نعم، تفضل. هل يمكنني الدفع الآن؟"),
      ("Sure, here is your change from my wallet.", "بالتأكيد، وهذا الباقي من محفظتي.")],
  8: [("Can I see the menu, please?", "هل يمكنني رؤية قائمة الطعام من فضلك؟"),
      ("Of course! What would you like to order?", "بالطبع! ماذا تريد أن تطلب؟"),
      ("I would like pizza, please.", "أريد بيتزا من فضلك."),
      ("The waiter will bring your plate and spoon.", "سيحضر النادل طبقك وملعقتك.")],
  9: [("I am so hungry!", "أنا جائع جدا!"),
      ("Me too, and thirsty! Let's order food.", "أنا أيضا، وعطشان! لنطلب الطعام."),
      ("This food is delicious!", "هذا الطعام لذيذ!"),
      ("Can we have more, please? Then the bill.", "هل يمكننا الحصول على المزيد من فضلك؟ ثم الفاتورة.")],
  10: [("You should eat more vegetables.", "يجب أن تأكل المزيد من الخضروات."),
       ("I know, and fruit has vitamins too.", "أعرف، والفاكهة بها فيتامينات أيضا."),
       ("You shouldn't eat junk food every day.", "يجب ألا تأكل طعاما غير صحي كل يوم."),
       ("You're right, healthy food makes me strong!", "أنت محق، الطعام الصحي يجعلني قويا!")],
  11: [("What do you do on Monday?", "ماذا تفعل يوم الاثنين؟"),
       ("On Monday, I go to school. What about Friday?", "يوم الاثنين، أذهب إلى المدرسة. ماذا عن الجمعة؟"),
       ("I love Fridays! It's almost the weekend.", "أحب أيام الجمعة! إنها قريبة من عطلة نهاية الأسبوع."),
       ("What is your weekly schedule like?", "كيف هو جدولك الأسبوعي؟")],
  12: [("What do you do after school?", "ماذا تفعل بعد المدرسة؟"),
       ("I do my homework, then I practice piano.", "أؤدي واجبي، ثم أتدرب على البيانو."),
       ("I go to art club and rest a little.", "أذهب إلى نادي الفن وأستريح قليلا."),
       ("I love my free time!", "أحب وقت فراغي!")],
  13: [("Give it to me, please.", "أعطها لي من فضلك."),
       ("Here you go! I see him at school.", "تفضل! أراه في المدرسة."),
       ("I like her too. She helps us a lot.", "أحبها أيضا. تساعدنا كثيرا."),
       ("I play with them every day.", "ألعب معهم كل يوم.")],
  14: [("Whose book is this?", "لمن هذا الكتاب؟"),
       ("This book is mine. Is this pen yours?", "هذا الكتاب لي. هل هذا القلم لك؟"),
       ("Yes, it's mine. That bag is hers.", "نعم، إنه لي. تلك الحقيبة لها."),
       ("And this classroom is ours!", "وهذا الفصل لنا!")],
  15: [("I can see a bird in the tree.", "أستطيع رؤية طائر في الشجرة."),
       ("I can hear it singing too!", "أستطيع سماعه يغني أيضا!"),
       ("I can smell the flowers here.", "أستطيع شم رائحة الزهور هنا."),
       ("And I can taste this delicious cake!", "وأستطيع تذوق هذه الكعكة اللذيذة!")],
  16: [("What does your sister look like?", "كيف تبدو أختك؟"),
       ("She is tall and has curly hair.", "هي طويلة القامة ولديها شعر مجعد."),
       ("My brother is short with straight hair.", "أخي قصير القامة وشعره مستقيم."),
       ("And my grandpa has a beard!", "وجدي لديه لحية!")],
  17: [("What is your teacher like?", "كيف هي معلمتك؟"),
       ("She is kind and very smart.", "هي لطيفة وذكية جدا."),
       ("My friend is funny and friendly too.", "صديقي مضحك وودود أيضا."),
       ("Being honest and polite is important too!", "أن تكون صادقا ومؤدبا مهم أيضا!")],
  18: [("Who is your best friend?", "من هو أفضل صديق لك؟"),
       ("She is my best friend. She is very generous.", "هي أفضل صديقة لي. إنها كريمة جدا."),
       ("We share our toys and help each other.", "نتشارك ألعابنا ونساعد بعضنا."),
       ("I trust her, and we play together every day.", "أثق بها، ونلعب معا كل يوم.")],
  19: [("I read a story about Lumi today.", "قرأت قصة عن لومي اليوم."),
       ("What happens in the morning?", "ماذا يحدث في الصباح؟"),
       ("Lumi wakes up happy and plays in the afternoon.", "يستيقظ لومي سعيدا ويلعب بعد الظهر."),
       ("And reads in the evening. What a nice day!", "ويقرأ في المساء. يا له من يوم لطيف!")],
  20: [("Let's write in our week diary!", "لنكتب في مذكرات أسبوعنا!"),
       ("Good idea! I bought vegetables at the market.", "فكرة جيدة! اشتريت خضروات من السوق."),
       ("I saw the menu at a new restaurant.", "رأيت قائمة الطعام في مطعم جديد."),
       ("And I played with my best friend all weekend!", "ولعبت مع أفضل صديق لي طوال عطلة نهاية الأسبوع!")],
}

run("level4", DIALOGUES, GRAMMAR_UNITS)
