# -*- coding: utf-8 -*-
import sys, json, glob
sys.path.insert(0, "lib")
from deck_template_teen import run
from grammar_slides import match_grammar_by_lesson_focus

_lessons = {}
for f in sorted(glob.glob("lessons/level3/lesson*.json")):
    d = json.load(open(f, encoding="utf-8"))
    _lessons[d["number"]] = d
GRAMMAR_UNITS = match_grammar_by_lesson_focus("level3", _lessons)

DIALOGUES = {
  1: [("What do you and your crew do after school?", "ماذا تفعلون أنت وشلتك بعد المدرسة؟"),
      ("We hang out at the park and chat.", "نقضي وقتا في الحديقة ونتحدث."),
      ("Do you text each other a lot?", "هل تراسلون بعضكم كثيرا؟"),
      ("Yes, and we laugh at each other's jokes!", "نعم، ونضحك على نكات بعضنا!")],
  2: [("What does your best friend do on weekends?", "ماذا يفعل صديقك المقرب في العطلة؟"),
      ("She plays basketball and practices with her team.", "تلعب كرة السلة وتتمرن مع فريقها."),
      ("Does she study too?", "هل تدرس أيضا؟"),
      ("Yes, she studies every evening.", "نعم، تدرس كل مساء.")],
  3: [("Do you like reality shows?", "هل تحب برامج الواقع؟"),
      ("Not really, I don't like boring shows.", "ليس حقا، لا أحب البرامج الممل."),
      ("What do you think is cool?", "ما الذي تعتقد أنه رائع؟"),
      ("I think gaming videos are awesome!", "أعتقد أن فيديوهات الألعاب رائعة!")],
  4: [("What's in your room?", "ماذا يوجد في غرفتك؟"),
      ("There is a poster and a speaker on my shelf.", "يوجد ملصق وسماعة على رفي."),
      ("Is there a desk too?", "هل يوجد مكتب أيضا؟"),
      ("Yes, there is a lamp on my desk.", "نعم، يوجد مصباح على مكتبي.")],
  5: [("These sneakers are new. Do you like them?", "هذا الحذاء الرياضي جديد. هل يعجبك؟"),
      ("Yes! Are those headphones new too?", "نعم! هل تلك السماعات جديدة أيضا؟"),
      ("This hoodie is my favorite.", "هذه السترة هي المفضلة لدي."),
      ("That cap looks great on you!", "تلك القبعة تبدو رائعة عليك!")],
  6: [("How many teammates do you have?", "كم عدد زملاء فريقك؟"),
      ("I have ten teammates and two classmates on the team.", "لدي عشرة زملاء فريق وزميلا صف في الفريق."),
      ("Do your cousins play too?", "هل يلعب أبناء عمك أيضا؟"),
      ("Yes, and our neighbors come to watch!", "نعم، وجيراننا يأتون للمشاهدة!")],
  7: [("Whose phone is this?", "لمن هذا الهاتف؟"),
      ("It's my phone. Is this your charger?", "هذا هاتفي. هل هذا شاحنك؟"),
      ("Yes! Are these her earbuds?", "نعم! هل هذه سماعات أذنها؟"),
      ("No, those are his earbuds.", "لا، تلك سماعات أذنه.")],
  8: [("Where's the cafeteria?", "أين الكافيتيريا؟"),
      ("It's behind the gym, next to the library.", "إنها خلف الصالة الرياضية، بجانب المكتبة."),
      ("Is the playground in front of the gate?", "هل ساحة اللعب أمام البوابة؟"),
      ("Yes, it's between the gym and the gate.", "نعم، إنها بين الصالة الرياضية والبوابة.")],
  9: [("Can you skateboard?", "هل تستطيع التزلج بلوح؟"),
      ("Yes, I can! Can you dance?", "نعم أستطيع! هل تستطيع الرقص؟"),
      ("A little. I can draw really well though.", "قليلا. لكنني أستطيع الرسم بشكل جيد."),
      ("That's cool! I can bake, but I can't draw.", "هذا رائع! أستطيع الخبز، لكن لا أستطيع الرسم.")],
  10: [("I have a mystery for you. Can you guess?", "لدي لغز لك. هل تستطيع التخمين؟"),
       ("Give me a clue!", "أعطني دليلا!"),
       ("It's a riddle about school.", "إنها أحجية عن المدرسة."),
       ("Is the answer 'homework'? That's my secret guess!", "هل الإجابة 'واجب منزلي'؟ هذا تخميني السري!")],
  11: [("Let's have a race! Who's faster?", "لنتسابق! من الأسرع؟"),
       ("I think I'm faster than you.", "أعتقد أنني أسرع منك."),
       ("My score is higher than yours!", "نتيجتي أعلى من نتيجتك!"),
       ("She broke the record. She's the fastest!", "كسرت الرقم القياسي. إنها الأسرع!")],
  12: [("There's a newcomer in our class.", "هناك طالب جديد في صفنا."),
       ("She looks a little nervous.", "تبدو متوترة قليلا."),
       ("Let's welcome her and introduce ourselves.", "لنرحب بها ونعرّف بأنفسنا."),
       ("Good idea, she won't feel like a stranger anymore!", "فكرة جيدة، لن تشعر أنها غريبة بعد الآن!")],
  13: [("Remember to raise your hand in class.", "تذكر أن ترفع يدك في الصف."),
       ("And line up quietly at the door.", "واصطف بهدوء عند الباب."),
       ("Should we pay attention during the test?", "هل يجب أن ننتبه أثناء الاختبار؟"),
       ("Yes, and submit your homework on time!", "نعم، وسلّم واجبك في الوقت المحدد!")],
  14: [("What are you doing right now?", "ماذا تفعل الآن؟"),
       ("I am texting my friend. What about you?", "أراسل صديقي. ماذا عنك؟"),
       ("I am scrolling my phone and chilling.", "أتصفح هاتفي وأسترخي."),
       ("She is studying, but we are gaming!", "هي تدرس، لكننا نلعب ألعاب فيديو!")],
  15: [("Are you highlighting your notes?", "هل تبرز ملاحظاتك بالألوان؟"),
       ("Yes, and I am memorizing new words too.", "نعم، وأحفظ كلمات جديدة أيضا."),
       ("We have a quiz tomorrow. Are you making flashcards?", "لدينا اختبار قصير غدا. هل تصنع بطاقات تعليمية؟"),
       ("Yes! And I'm finishing my group project presentation.", "نعم! وأنهي عرضي التقديمي لمشروعي الجماعي.")],
  16: [("Pass me the controller, it's game night!", "أعطني ذراع التحكم، إنها ليلة الألعاب!"),
       ("I have a new strategy this time.", "لدي استراتيجية جديدة هذه المرة."),
       ("My teammate just leveled up!", "زميل فريقي وصل لمستوى جديد للتو!"),
       ("That's the high score! You're the champion!", "هذه أعلى نتيجة! أنت البطل!")],
  17: [("What genre do you want to watch?", "ما نوع الفيلم الذي تريد مشاهدته؟"),
       ("Let's get popcorn first!", "لنحضر الفشار أولا!"),
       ("This trailer looks amazing.", "هذا الإعلان يبدو مذهلا."),
       ("I can't wait for the sequel!", "لا أطيق الانتظار للجزء التالي!")],
  18: [("What's your opinion about the new rule?", "ما رأيك في القاعدة الجديدة؟"),
       ("I agree with it, actually.", "أوافق عليها في الحقيقة."),
       ("I disagree. What's your reason?", "أنا أختلف. ما سببك؟"),
       ("Let's decide together, it's our choice.", "لنقرر معا، إنه خيارنا.")],
  19: [("Are you nervous about the match today?", "هل أنت متوتر بشأن المباراة اليوم؟"),
       ("A little, but I know we can win.", "قليلا، لكنني أعلم أننا نستطيع الفوز."),
       ("Let's cheer for the team!", "لنشجع الفريق!"),
       ("The coach is so proud of our teamwork.", "المدرب فخور جدا بعملنا الجماعي.")],
  20: [("What did you learn this year?", "ماذا تعلمت هذا العام؟"),
       ("So much! My crew, my teammates, everything.", "الكثير! شلتي، زملاء فريقي، كل شيء."),
       ("Let's put it all in our time capsule.", "لنضع كل ذلك في كبسولة الزمن الخاصة بنا."),
       ("I'm proud of how far we've come!", "أنا فخور بمدى تقدمنا!")],
}

run("level3", DIALOGUES, GRAMMAR_UNITS)
