# -*- coding: utf-8 -*-
import sys, json, glob, os
sys.path.insert(0, "lib")
from deck_template_teen2 import build_deck_v2
from grammar_slides import match_grammar_by_lesson_focus

LEVEL = "level6"
_lessons = {}
for f in sorted(glob.glob(f"lessons/{LEVEL}/lesson*.json")):
    d = json.load(open(f, encoding="utf-8"))
    _lessons[d["number"]] = d
GRAMMAR_UNITS = match_grammar_by_lesson_focus(LEVEL, _lessons)

THEME_BY_LESSON = {
    1: "default", 2: "default", 3: "social", 4: "room", 5: "room",
    6: "school", 7: "money", 8: "social", 9: "default", 10: "room",
    11: "school", 12: "sport", 13: "default", 14: "room", 15: "default",
    16: "school", 17: "default", 18: "default", 19: "school", 20: "default",
}

HOOKS = {
    1: "What's one plan you already have for this weekend or next week?",
    2: "What's one thing you think will be different about your life in 5 years?",
    3: "What's already on your calendar for this week?",
    4: "Has your phone ever rung at exactly the wrong moment?",
    5: "What's one thing you have to do every single day, whether you want to or not?",
    6: "Think of someone you know who does everything really carefully. Who is it?",
    7: "Think of two things you own -- which one is more expensive?",
    8: "What are you already planning to do this weekend?",
    9: "Do you think you'll be good at your future job? Why?",
    10: "What's one chore or rule you have at home?",
    11: "Who's the most clearly-spoken person you know?",
    12: "Think of two phones, movies, or games -- which is more interesting to you?",
    13: "Have you ever done two things at the exact same time, like eating and texting?",
    14: "What's one goal you already have for next year?",
    15: "Do you ever disagree with a friend about something small? What was it about?",
    16: "What's something you're already getting ready for?",
    17: "Think of an instruction you give someone often. How should it be done?",
    18: "What's a tradition or custom from your culture that you like?",
    19: "Have you ever been on a school trip that didn't go as planned?",
    20: "What's one thing you hope is true about your life a year from now?",
}
CHALLENGES = {
    1: {"prompt": "Describe 3 plans you have using 'going to'.", "hint": "I'm going to..."},
    2: {"prompt": "Make 3 predictions about your future using 'will'.", "hint": "I will... / probably... / definitely..."},
    3: {"prompt": "Describe 3 fixed plans for this week using Present Continuous.", "hint": "I'm meeting/traveling/starting..."},
    4: {"prompt": "Describe something that interrupted you in the past.", "hint": "I was ___ when/while ___."},
    5: {"prompt": "Say 3 things you have to do and 1 you don't have to do.", "hint": "I have to... / I don't have to..."},
    6: {"prompt": "Describe how you do 3 different things using adverbs of manner.", "hint": "quickly, carefully, quietly..."},
    7: {"prompt": "Compare 3 things using long comparative adjectives.", "hint": "more interesting/difficult/expensive..."},
    8: {"prompt": "Describe your weekend plans in 3 sentences.", "hint": "Use today's vocabulary words."},
    9: {"prompt": "Make 3 predictions about your classmates' futures.", "hint": "I think she will..."},
    10: {"prompt": "Describe 3 rules or responsibilities at your home.", "hint": "I have to... / I'm allowed to..."},
    11: {"prompt": "Describe how 3 people you know talk or communicate.", "hint": "honestly, politely, confidently..."},
    12: {"prompt": "Compare 2 options and say which is better, with reasons.", "hint": "This is more ___ than that."},
    13: {"prompt": "Describe 2 things you did at the same time in the past.", "hint": "I was ___ while ___."},
    14: {"prompt": "Describe 3 goals or plans for next year.", "hint": "Mix 'going to' and 'will'."},
    15: {"prompt": "Take a side in a friendly debate and explain your point of view.", "hint": "I would argue that..."},
    16: {"prompt": "Describe how you're preparing for something coming up.", "hint": "I'm going to prepare/practice/review..."},
    17: {"prompt": "Give 3 instructions using adverbs of manner.", "hint": "Do it properly/safely/neatly..."},
    18: {"prompt": "Compare your culture to another one you know about.", "hint": "Use long comparative adjectives."},
    19: {"prompt": "Retell the school trip story in your own words.", "hint": "Use at least 2 vocabulary words from the story."},
    20: {"prompt": "Describe one past achievement and one future goal.", "hint": "Try to use words from at least 3 different lessons."},
}
REAL_LIFE = {
    1: "This week, tell someone 3 real plans using 'going to'.",
    2: "Make a real prediction about tomorrow using 'will'.",
    3: "Tell someone about a fixed plan you have this week.",
    4: "Think of a real time you were interrupted -- describe it in English.",
    5: "Tell a family member something you have to do today.",
    6: "Notice how someone does something today and describe it with an adverb.",
    7: "Compare two real things you own using a long adjective.",
    8: "Tell a friend your real weekend plans.",
    9: "Share a real prediction about your future with someone.",
    10: "Talk to your family about one responsibility you have.",
    11: "Notice how someone talks today and describe it with an adverb.",
    12: "Compare two real options you're choosing between this week.",
    13: "Describe two things you did at once today.",
    14: "Write down one real plan for next year.",
    15: "Have a friendly, polite disagreement with someone this week.",
    16: "Describe what you're really preparing for right now.",
    17: "Give someone a real instruction using an adverb of manner.",
    18: "Look up one custom from another culture and compare it to yours.",
    19: "Think about a real trip that had an unexpected moment.",
    20: "Write one real goal for the next year, in English.",
}
DISCUSSIONS = {
    1: ["Talk about a real plan you have for this year -- something you're actually going to do.",
        "Is there somewhere you're planning to visit soon?",
        "Have you ever thought about joining a club or team you haven't tried yet?",
        "Ask a partner: 'What's one thing you're planning to start doing differently?'",
        "Do you prefer planning things far in advance, or deciding at the last minute?"],
    2: ["Make a prediction about something that will probably happen this week.",
        "What do you believe the future of technology will look like in ten years?",
        "Is there something you might try, but you're not sure yet?",
        "Ask someone: 'What do you definitely think will happen by the end of this year?'",
        "Do you trust your own predictions, or are you usually wrong?"],
    3: ["Talk about your actual, real plans for this weekend.",
        "Have you ever hosted something -- a party, a study group, anything at all?",
        "Is there an event you're attending soon that you're excited about?",
        "Ask a partner: 'What time are you usually leaving the house on weekends?'",
        "Do you prefer weekends with fixed plans, or completely open ones?"],
    4: ["Talk about a time something unexpected happened while you were doing something else.",
        "Has anyone ever interrupted you at exactly the wrong moment? What happened?",
        "What's something you noticed recently that most people probably missed?",
        "Ask someone: 'What's the most annoying time it's ever started raining on you?'",
        "Do you get frustrated when your plans get interrupted, or do you just go with it?"],
    5: ["Talk about a responsibility you have that you actually don't mind.",
        "Is there a rule at home or school you think should be optional instead of required?",
        "What's something you have to do every day that you wish you didn't?",
        "Ask a partner: 'What's one responsibility you're actually proud of having?'",
        "Do you think teenagers should have more responsibilities, or fewer?"],
    6: ["Talk about something you do carefully, and something you tend to rush.",
        "Are you a patient person, or do you get frustrated easily?",
        "Is there a task that comes really easily to you but is hard for other people?",
        "Ask someone: 'Do you work better quietly alone, or with some noise around you?'",
        "Does how you do something matter as much as actually getting it done?"],
    7: ["Compare two subjects you're studying -- which is more interesting, and why?",
        "What's the most exciting thing that could realistically happen to you this year?",
        "Is the most popular choice always the best one? Discuss.",
        "Ask a partner: 'What's the most comfortable place in your house?'",
        "Would you rather have something more expensive but better, or cheaper but okay?"],
    8: ["Talk about your ideal weekend, from start to finish.",
        "Have you ever volunteered for something? Would you like to?",
        "Do you prefer sleeping in, or getting up early even on weekends?",
        "Ask someone: 'Is there somewhere nearby you'd like to explore but haven't yet?'",
        "What does 'catching up' with a friend actually look like for you?"],
    9: ["Predict one thing about your own future that you're fairly confident about.",
        "Do you think you'll travel a lot in your life, or stay closer to home?",
        "What's something about the world you think will change a lot in your lifetime?",
        "Ask a partner: 'What do you think you'll achieve in the next five years?'",
        "Do you believe people can really invent something new, or has it all been done?"],
    10: ["Talk about the chores you're responsible for at home.",
         "Do you think your curfew or house rules are fair? Why or why not?",
         "What's something you're allowed to do now that you weren't a few years ago?",
         "Ask someone: 'What does being independent actually mean to you?'",
         "Is trust something you have to earn, or something you're given automatically?"],
    11: ["Talk about someone you know who always speaks really confidently.",
         "Is it more important to be honest, or to be kind, when giving your opinion?",
         "Do you get nervous speaking in front of the class? How do you deal with it?",
         "Ask a partner: 'Do you think you speak more politely to teachers or to friends?'",
         "Can you always tell when someone is being honest with you?"],
    12: ["Compare two options for something you use every day -- which is more convenient?",
         "What's the most useful thing you own, and why?",
         "Is it worth paying more for something more reliable? Discuss.",
         "Ask someone: 'What's a reasonable price for something you'd love to buy?'",
         "Do you usually pick the most convenient option, or the best one, even if it's harder?"],
    13: ["Talk about a time you were doing two things at once and it went badly.",
         "Do you think multitasking actually works, or does it just feel like it does?",
         "What's the hardest thing for you to focus on?",
         "Ask a partner: 'What were you doing the last time someone had to repeat themselves to you?'",
         "Is it possible to really focus with your phone nearby?"],
    14: ["Talk about one real goal you have for next year.",
         "What's something about yourself you'd like to improve?",
         "Do you usually keep your resolutions, or forget about them after a few weeks?",
         "Ask someone: 'What do you hope will be different about your life next year?'",
         "Is it better to set one big goal, or a few smaller ones?"],
    15: ["Share an opinion, and see if a partner can convince you to change it.",
         "Is there a topic where you can honestly see both points of view?",
         "What makes an argument actually convincing to you -- evidence, emotion, or something else?",
         "Ask someone: 'What's a fair point someone made that changed how you think?'",
         "Is it okay to agree partly with someone, or do you have to fully agree or disagree?"],
    16: ["Talk about how you usually prepare for something important, like a test or event.",
         "Do you feel more ready after practicing a lot, or does over-preparing stress you out?",
         "Is rest actually part of getting ready, in your opinion?",
         "Ask a partner: 'What's the last big thing you had to prepare for?'",
         "Do you organize everything ahead of time, or handle things as they come?"],
    17: ["Talk about something you do very efficiently, without wasting time.",
         "Is there a task you always do neatly, and one you're careless about?",
         "Do you think doing something correctly matters more than doing it quickly?",
         "Ask someone: 'What's something you had to learn to do more safely over time?'",
         "What does a day that goes 'smoothly' actually look like for you?"],
    18: ["Talk about a tradition from your own culture and what it means to you.",
         "What's the most colorful or interesting festival you've ever seen or heard about?",
         "Is your lifestyle similar to or different from your parents' at your age?",
         "Ask a partner: 'What's the most traditional thing your family still does?'",
         "Do you think cultures around the world are becoming more similar over time?"],
    19: ["Talk about the most memorable field trip or school event you've been on.",
         "Has something unexpected ever happened on a trip? How did you handle it?",
         "What's a lesson you learned the hard way?",
         "Ask someone: 'What's a trip you're excited about that hasn't happened yet?'",
         "Do unexpected moments usually make an experience better, or worse?"],
    20: ["Looking back at this whole level, what's the most memorable thing you learned?",
         "Predict: what do you think your English will sound like a year from now?",
         "Talk about one goal you have for your English going forward.",
         "Ask a partner: 'What's the most exciting plan you have for the future?'",
         "What do you want to achieve next, now that you've finished this level?"],
}

DIALOGUES = {
  1: [("So what's your actual plan for after this year? Have you decided anything?", "إذاً ما هي خطتك الفعلية لما بعد هذا العام؟ هل قررت شيئاً؟"),
      ("Honestly, I'm thinking about applying to a program abroad, if I'm brave enough.", "بصراحة، أفكر في التقديم لبرنامج في الخارج، إن كنت شجاعاً كفاية."),
      ("That's huge. Would you actually move, or just visit for a while first?", "هذا كبير. هل ستنتقل فعلاً، أم ستزور لفترة أولاً؟"),
      ("Move eventually, I think, but I'd start by joining a summer program first.", "الانتقال في النهاية، أعتقد، لكنني سأبدأ بالانضمام لبرنامج صيفي أولاً."),
      ("That sounds smart. Testing it out before committing to something that big.", "هذا يبدو ذكياً. تجربة الأمر قبل الالتزام بشيء بهذا الحجم."),
      ("Exactly. No point diving in completely before I even know if I'll like it.", "بالضبط. لا فائدة من الانغماس تماماً قبل أن أعرف حتى إن كنت سأحبه.")],
  2: [("What do you predict will happen with technology in the next ten years?", "بماذا تتوقع أن يحدث مع التكنولوجيا في السنوات العشر القادمة؟"),
      ("Honestly, I believe it'll probably change faster than we can even imagine.", "بصراحة، أعتقد أنها ستتغير على الأرجح أسرع مما نستطيع تخيله."),
      ("Definitely. Maybe we'll have things we can't even picture right now.", "بالتأكيد. ربما سيكون لدينا أشياء لا نستطيع تخيلها الآن حتى."),
      ("That's kind of exciting, but also a little terrifying if I'm being honest.", "هذا مثير نوعاً ما، لكنه مخيف قليلاً أيضاً إن كنت صادقاً."),
      ("Same. The future is unpredictable, but I think that's what makes it interesting.", "نفس الشيء. المستقبل غير متوقع، لكن أعتقد أن هذا ما يجعله مثيراً."),
      ("Agreed. I'd rather not know everything -- surprises make life more interesting.", "متفق. أفضل ألا أعرف كل شيء -- المفاجآت تجعل الحياة أكثر إثارة.")],
  3: [("What are your actual plans this weekend? You seem busier than usual.", "ما هي خططك الفعلية هذا الأسبوع؟ تبدو أكثر انشغالاً من المعتاد."),
      ("I'm traveling Friday, then attending my cousin's graduation on Saturday.", "سأسافر الجمعة، ثم أحضر تخرج ابن عمي يوم السبت."),
      ("Wow, packed schedule. When are you even leaving to make that work?", "واو، جدول مزدحم. متى ستغادر أصلاً لينجح كل ذلك؟"),
      ("Early morning, honestly. I'm also hosting a small get-together Sunday night.", "الصباح الباكر، بصراحة. أستضيف أيضاً تجمعاً صغيراً ليلة الأحد."),
      ("That's a lot happening. Are you starting anything new after this weekend?", "هذا الكثير يحدث. هل ستبدأ شيئاً جديداً بعد هذا الأسبوع؟"),
      ("Actually yes, I'm meeting with a mentor about a project I'm starting soon.", "في الواقع نعم، سألتقي بموجه بشأن مشروع سأبدأه قريباً.")],
  4: [("You'll never guess what happened while I was walking home yesterday.", "لن تخمن أبداً ما حدث بينما كنت أمشي إلى المنزل أمس."),
      ("Tell me! Did something interrupt your walk, or did you just get soaked?", "أخبرني! هل قاطع شيء مشيك، أم أنك ابتللت فقط؟"),
      ("Both, actually. It started raining right as I noticed I forgot my umbrella.", "كلاهما، في الواقع. بدأت تمطر بالضبط عندما لاحظت أنني نسيت مظلتي."),
      ("Classic timing. What were you doing meanwhile, just running for shelter?", "توقيت كلاسيكي. ماذا كنت تفعل في تلك الأثناء، تركض للاحتماء فقط؟"),
      ("Pretty much, until I arrived at a café and just waited it out completely soaked.", "تقريباً، حتى وصلت إلى مقهى وانتظرت حتى توقفت وأنا مبتل تماماً."),
      ("That's rough, but honestly it sounds like a pretty funny story now.", "هذا صعب، لكن بصراحة تبدو قصة مضحكة جداً الآن.")],
  5: [("Do you actually have to do chores at home, or is that optional for you?", "هل يجب عليك فعلاً القيام بالأعمال المنزلية، أم أن هذا اختياري بالنسبة لك؟"),
      ("Required, unfortunately. My parents say it's part of my responsibility.", "مطلوب، للأسف. والداي يقولان إنه جزء من مسؤوليتي."),
      ("Fair enough. I don't have to do much, but I choose to out of duty, honestly.", "معقول. لا يجب علي فعل الكثير، لكنني أختار ذلك من باب الواجب، بصراحة."),
      ("That's a mature way to look at it. I usually complain before I even start.", "هذه طريقة ناضجة للنظر إليها. أنا عادة أشتكي قبل أن أبدأ حتى."),
      ("Same, honestly, but complaining doesn't actually get the dishes done either.", "نفس الشيء، بصراحة، لكن الشكوى لا تنجز الأطباق أيضاً."),
      ("True. Might as well just get it over with instead of dragging it out.", "صحيح. قد يكون من الأفضل إنهاءها بدلاً من إطالة أمدها.")],
  6: [("Do you usually work quickly, or do you take your time and go carefully?", "هل تعمل عادة بسرعة، أم تأخذ وقتك وتتصرف بحذر؟"),
      ("Carefully, always. I'd rather do something slowly than redo it because I rushed.", "بحذر، دائماً. أفضل فعل شيء ببطء على إعادته لأنني تسرعت."),
      ("That makes sense. I tend to work loudly and fast, then fix mistakes after.", "هذا منطقي. أميل للعمل بصخب وسرعة، ثم أصلح الأخطاء بعد ذلك."),
      ("Honestly, that sounds stressful. Doesn't that make things harder eventually?", "بصراحة، هذا يبدو متعباً. ألا يجعل هذا الأمور أصعب في النهاية؟"),
      ("Sometimes, but patiently redoing things quietly isn't really my style, unfortunately.", "أحياناً، لكن إعادة الأشياء بصبر وهدوء ليست أسلوبي حقاً، للأسف."),
      ("Fair enough. I guess we both get there, just in completely different ways.", "معقول. أعتقد أننا كلانا نصل إلى هناك، فقط بطرق مختلفة تماماً.")],
  7: [("Which class do you think is more difficult, math or science, honestly?", "أي حصة تعتقد أنها أصعب، الرياضيات أم العلوم، بصراحة؟"),
      ("Science, definitely, but math is way more interesting to me personally.", "العلوم، بالتأكيد، لكن الرياضيات أكثر إثارة لاهتمامي بكثير شخصياً."),
      ("Fair. What about after school -- what's the most exciting part of your day?", "معقول. ماذا عن بعد المدرسة -- ما هو أكثر جزء مثير في يومك؟"),
      ("Probably just getting home and finally sitting in the most comfortable chair I own.", "غالباً الوصول إلى المنزل والجلوس أخيراً على أكثر كرسي مريح أملكه."),
      ("Ha, relatable. Is comfort more important to you than something more expensive?", "هه، مفهوم. هل الراحة أهم بالنسبة لك من شيء أكثر غلاءً؟"),
      ("Completely. I'd choose comfortable and affordable over expensive and impressive any day.", "تماماً. سأختار المريح وبسعر معقول على الغالي والمبهر في أي يوم.")],
  8: [("What's the plan for this weekend? Please say we're actually relaxing.", "ما هي خطة هذا الأسبوع؟ أرجوك قل إننا سنسترخي فعلاً."),
      ("Mostly, yeah. I want to sleep in and just catch up on everything I've missed.", "في الغالب، نعم. أريد أن أنام متأخراً وألحق بكل ما فاتني."),
      ("Same, honestly, but I also want to explore that new part of town.", "نفس الشيء، بصراحة، لكنني أريد أيضاً استكشاف ذلك الجزء الجديد من المدينة."),
      ("We could do both, hang out there Saturday and volunteer together Sunday.", "يمكننا فعل الاثنين، نقضي وقتاً هناك السبت ونتطوع معاً الأحد."),
      ("I like that balance. Relaxing and doing something meaningful in one weekend.", "أحب هذا التوازن. الاسترخاء وفعل شيء ذي معنى في أسبوع واحد."),
      ("Exactly. Best of both worlds, without completely wasting the whole two days.", "بالضبط. أفضل ما في العالمين، دون إهدار اليومين بالكامل.")],
  9: [("Do you think we'll actually stay in touch after we graduate someday?", "هل تعتقد أننا سنبقى على تواصل فعلاً بعد أن نتخرج يوماً ما؟"),
      ("Honestly, I believe we will. I think our friendship will only change a little.", "بصراحة، أعتقد أننا سنفعل. أعتقد أن صداقتنا ستتغير قليلاً فقط."),
      ("I hope so. I predict you'll travel a lot and probably achieve something huge.", "أتمنى ذلك. أتوقع أنك ستسافر كثيراً وستحقق على الأرجح شيئاً ضخماً."),
      ("That's kind of you. I actually think you'll succeed at inventing something useful.", "هذا لطيف منك. أعتقد فعلاً أنك ستنجح في اختراع شيء مفيد."),
      ("Wow, big predictions from both of us. Let's remember this conversation someday.", "واو، توقعات كبيرة منا كلينا. لنتذكر هذا الحديث يوماً ما."),
      ("Definitely. We'll look back and see how close we actually got it right.", "بالتأكيد. سننظر للوراء ونرى كم كنا قريبين فعلاً من الصواب.")],
  10: [("Is your curfew still early, or are your parents letting you be more independent?", "هل ما زال موعد عودتك مبكراً، أم يسمح لك والداك بأن تكون أكثر استقلالية؟"),
       ("A little more independent now, honestly, since I've earned more of their trust.", "أكثر استقلالية قليلاً الآن، بصراحة، بما أنني كسبت المزيد من ثقتهما."),
       ("That's nice. Are you allowed to go out without asking permission every time?", "هذا لطيف. هل يُسمح لك بالخروج دون طلب الإذن في كل مرة؟"),
       ("Mostly, as long as I still do my chores and let them know where I am.", "في الغالب، طالما ما زلت أقوم بأعمالي المنزلية وأخبرهما أين أنا."),
       ("That sounds fair, actually. Trust seems to go both ways in your house.", "هذا يبدو عادلاً فعلاً. الثقة تبدو متبادلة في منزلك."),
       ("It does. I think that's why I don't mind the rules as much as I used to.", "هذا صحيح. أعتقد أن هذا سبب عدم انزعاجي من القواعد كما كنت من قبل.")],
  11: [("Do you usually speak confidently in front of people, or does it make you nervous?", "هل تتحدث عادة بثقة أمام الناس، أم يجعلك ذلك متوتراً؟"),
       ("Honestly, nervously at first, but I try to speak clearly no matter how I feel.", "بصراحة، بتوتر في البداية، لكنني أحاول التحدث بوضوح مهما كان شعوري."),
       ("That's smart. Do you think it's better to speak politely or just be blunt?", "هذا ذكي. هل تعتقد أنه من الأفضل التحدث بأدب أم أن تكون صريحاً فقط؟"),
       ("Politely, but still honestly. You can be kind and truthful at the same time.", "بأدب، لكن بصدق أيضاً. يمكنك أن تكون لطيفاً وصادقاً في آن واحد."),
       ("That's a good balance, actually. I struggle with saying things too bluntly sometimes.", "هذا توازن جيد فعلاً. أعاني أحياناً من قول الأشياء بصراحة مفرطة."),
       ("Practice helps. The more confidently you speak, the more naturally kindness comes through.", "التدرب يساعد. كلما تحدثت بثقة أكثر، ظهر اللطف بشكل أكثر طبيعية.")],
  12: [("Between these two options, which one do you think is actually worth it?", "بين هذين الخيارين، أيهما تعتقد أنه يستحق فعلاً؟"),
       ("Honestly, the more expensive one seems more reliable, so probably worth it.", "بصراحة، الأغلى يبدو أكثر موثوقية، فهو يستحق على الأرجح."),
       ("That's reasonable. Is convenience important to you too, or just quality?", "هذا معقول. هل الراحة مهمة بالنسبة لك أيضاً، أم الجودة فقط؟"),
       ("Both, but the most useful option usually wins for me in the end.", "كلاهما، لكن الخيار الأكثر فائدة يفوز عادة بالنسبة لي في النهاية."),
       ("Fair point. I guess it depends on what you'll actually use it for daily.", "نقطة منطقية. أعتقد أن الأمر يعتمد على ما ستستخدمه فعلاً يومياً."),
       ("Exactly. No point picking something convenient if it's not useful long-term.", "بالضبط. لا فائدة من اختيار شيء مريح إن لم يكن مفيداً على المدى الطويل.")],
  13: [("Were you actually studying earlier, or was that just background noise on a call?", "هل كنت تدرس فعلاً سابقاً، أم كان ذلك مجرد ضوضاء خلفية في مكالمة؟"),
       ("Honestly, I was studying while chatting a little, which probably wasn't smart.", "بصراحة، كنت أدرس بينما أتحدث قليلاً، وهو على الأرجح لم يكن ذكياً."),
       ("That explains it. I find it impossible to focus if I'm doing two things.", "هذا يفسر الأمر. أجد من المستحيل التركيز إن كنت أفعل شيئين."),
       ("Same, but I still try. Yesterday I was scrolling while my mom was cooking nearby.", "نفس الشيء، لكنني ما زلت أحاول. أمس كنت أتصفح بينما كانت أمي تطهو بالقرب."),
       ("That sounds distracting either way. Did you actually get anything done though?", "هذا يبدو مشتتاً على أي حال. هل أنجزت شيئاً فعلاً مع ذلك؟"),
       ("Barely, honestly. I think tomorrow I'll actually just focus on one thing at a time.", "بالكاد، بصراحة. أعتقد أنني غداً سأركز فعلاً على شيء واحد في كل مرة.")],
  14: [("Do you have an actual goal for next year, or are you not thinking that far?", "هل لديك هدف فعلي للعام القادم، أم أنك لا تفكر إلى هذا الحد؟"),
       ("I do, honestly. My resolution is to challenge myself more instead of staying comfortable.", "لدي، بصراحة. عزمي هو تحدي نفسي أكثر بدلاً من البقاء في منطقة الراحة."),
       ("That's a solid goal. What specifically do you hope to improve about yourself?", "هذا هدف قوي. ماذا تأمل تحديداً أن تحسنه في نفسك؟"),
       ("Probably my confidence, if I'm being completely honest about it.", "غالباً ثقتي بنفسي، إن كنت صادقاً تماماً بشأن ذلك."),
       ("I don't expect it to be easy, but I believe you can actually do it.", "لا أتوقع أن يكون سهلاً، لكنني أؤمن أنك تستطيع فعله فعلاً."),
       ("Thanks, honestly. That kind of support makes the goal feel a lot more real.", "شكراً، بصراحة. هذا النوع من الدعم يجعل الهدف يبدو أكثر واقعية بكثير.")],
  15: [("Can you actually convince me your point of view is right, with real evidence?", "هل تستطيع إقناعي فعلاً بأن وجهة نظرك صحيحة، بأدلة حقيقية؟"),
       ("I can try. I think I have a fair point, even if you don't fully agree.", "يمكنني المحاولة. أعتقد أن لدي نقطة منطقية، حتى لو لم توافق تماماً."),
       ("I'll agree partly, honestly, but I still think you're missing something important.", "سأوافق جزئياً، بصراحة، لكنني ما زلت أعتقد أنك تفوت شيئاً مهماً."),
       ("That's fine, I'm not trying to argue you into total agreement anyway.", "لا بأس، لا أحاول إقناعك بالموافقة التامة على أي حال."),
       ("Good, because I respect a debate way more than someone forcing their opinion.", "جيد، لأنني أحترم النقاش أكثر بكثير من شخص يفرض رأيه."),
       ("Same here. That's honestly what makes this conversation actually worth having.", "نفس الشيء هنا. هذا بصراحة ما يجعل هذا الحديث يستحق فعلاً.")],
  16: [("Do you feel ready for tomorrow, or do you still need more time to prepare?", "هل تشعر بالاستعداد للغد، أم ما زلت بحاجة لوقت أكثر للتحضير؟"),
       ("Honestly, I've practiced enough. I just need to organize my notes and rest.", "بصراحة، تدربت بما فيه الكفاية. أحتاج فقط لتنظيم ملاحظاتي والراحة."),
       ("That's smart. Rest matters just as much as reviewing everything one more time.", "هذا ذكي. الراحة تهم بقدر مراجعة كل شيء مرة أخرى."),
       ("Exactly, over-preparing without resting just makes tomorrow harder, not easier.", "بالضبط، الإفراط في التحضير دون راحة يجعل الغد أصعب فقط، لا أسهل."),
       ("I completely agree. I'm going to review quickly, then actually get real sleep.", "أوافق تماماً. سأراجع بسرعة، ثم أحصل فعلاً على نوم حقيقي."),
       ("Good plan. We'll both walk in tomorrow actually ready instead of exhausted.", "خطة جيدة. سندخل كلانا غداً مستعدين فعلاً بدلاً من منهكين.")],
  17: [("Did everything go smoothly today, or did something go wrong again?", "هل سار كل شيء بسلاسة اليوم، أم حدث خطأ مجدداً؟"),
       ("Actually, pretty smoothly. I finally did the whole process correctly and efficiently.", "في الواقع، بسلاسة كبيرة. أخيراً أنجزت العملية بأكملها بشكل صحيح وفعال."),
       ("That's great! Did you do it safely too, or did you rush through it?", "هذا رائع! هل فعلتها بأمان أيضاً، أم تسرعت خلالها؟"),
       ("Safely, properly, all of it, honestly. I even kept my notes neatly organized.", "بأمان، بشكل صحيح، كل ذلك، بصراحة. حتى حافظت على ملاحظاتي منظمة بعناية."),
       ("Look at you, doing everything right for once. What changed?", "انظر إلى نفسك، تفعل كل شيء بشكل صحيح لمرة واحدة. ماذا تغير؟"),
       ("Practice, mostly. Doing something correctly the first time saves so much stress later.", "التدرب، في الغالب. فعل شيء بشكل صحيح من المرة الأولى يوفر الكثير من التوتر لاحقاً.")],
  18: [("Is your family's lifestyle similar to your grandparents', or completely different?", "هل نمط حياة عائلتك مشابه لنمط حياة أجدادك، أم مختلف تماماً؟"),
       ("Honestly, pretty different, but we still keep the most traditional customs alive.", "بصراحة، مختلف جداً، لكننا ما زلنا نحافظ على أكثر العادات تقليدية حية."),
       ("That's nice. What's the most colorful tradition your family actually celebrates?", "هذا لطيف. ما هو أكثر تقليد ملون تحتفل به عائلتك فعلاً؟"),
       ("Probably our biggest holiday, it's genuinely the most colorful event of the year.", "غالباً أكبر أعيادنا، إنه فعلاً أكثر حدث ملون في العام."),
       ("That sounds amazing. I think traditions like that keep a culture alive, honestly.", "هذا يبدو مذهلاً. أعتقد أن تقاليد كهذه تبقي الثقافة حية، بصراحة."),
       ("Completely agree. Even small customs matter more than people usually realize.", "أوافق تماماً. حتى العادات الصغيرة تهم أكثر مما يدرك الناس عادة.")],
  19: [("Were you excited for the field trip, or were you dreading the long bus ride?", "هل كنت متحمساً للرحلة المدرسية، أم كنت تخشى ركوب الحافلة الطويل؟"),
       ("Excited, honestly, but something unexpected happened that made it even more memorable.", "متحمساً، بصراحة، لكن حدث شيء غير متوقع جعلها أكثر تميزاً."),
       ("What happened? Please tell me nobody got left behind or anything like that.", "ماذا حدث؟ أرجوك أخبرني أن أحداً لم يُترك خلفاً أو ما شابه."),
       ("Close, actually, but the teacher handled it so calmly it barely felt like a crisis.", "قريب من ذلك فعلاً، لكن المعلمة تعاملت معه بهدوء لدرجة أنه بالكاد شعر وكأنه أزمة."),
       ("That's impressive. What's the actual lesson learned from that whole experience?", "هذا مثير للإعجاب. ما هو الدرس المستفاد فعلاً من تلك التجربة كلها؟"),
       ("Probably that staying calm handles unexpected problems way better than panicking does.", "غالباً أن الهدوء يتعامل مع المشاكل غير المتوقعة بشكل أفضل بكثير من الذعر.")],
  20: [("Looking ahead, what's the most exciting goal in your actual future plan?", "بالنظر إلى الأمام، ما هو أكثر هدف مثير في خطتك المستقبلية الفعلية؟"),
       ("Honestly, I predict I'll achieve something I couldn't even imagine at the start of this level.", "بصراحة، أتوقع أنني سأحقق شيئاً لم أستطع تخيله حتى في بداية هذا المستوى."),
       ("That's a bold prediction. Do you have to work quickly toward it, or is there time?", "هذا توقع جريء. هل يجب أن تعمل بسرعة نحوه، أم أن هناك وقتاً؟"),
       ("There's time, but I don't want to waste it either, if I'm being honest.", "هناك وقت، لكنني لا أريد إهداره أيضاً، إن كنت صادقاً."),
       ("Smart. This whole level has genuinely been memorable, watching everyone grow like this.", "ذكي. هذا المستوى بأكمله كان مميزاً فعلاً، مشاهدة الجميع ينمون هكذا."),
       ("Agreed. I can't wait to see how much closer we all get to these goals next year.", "متفق. لا أطيق الانتظار لأرى كم سنقترب جميعاً من هذه الأهداف العام القادم.")],
}

def make_notice_sentences(lesson_num, grammar_topic):
    sentences = []
    if grammar_topic:
        for ex in grammar_topic.get("examples", [])[:4]:
            sentences.append(ex["en"])
    other_lesson_num = 1 if lesson_num != 1 else 2
    other = _lessons.get(other_lesson_num)
    if other and other["vocab"]:
        sentences.append(other["vocab"][0]["example"])
    return sentences

os.makedirs(f"slide-content/{LEVEL}", exist_ok=True)
manifest = {}
for num in sorted(_lessons.keys()):
    lesson = _lessons[num]
    grammar_topic = GRAMMAR_UNITS.get(num)
    dialogue = DIALOGUES.get(num, [])
    theme_key = THEME_BY_LESSON.get(num, "default")
    hook = HOOKS.get(num, f"Let's talk about {lesson['title'].lower()}.")
    challenge = CHALLENGES.get(num)
    real_life = REAL_LIFE.get(num)
    discussion = DISCUSSIONS.get(num)
    notice_sentences = make_notice_sentences(num, grammar_topic)
    notice_note = grammar_topic["title"] if grammar_topic else ""

    slides = build_deck_v2(num, lesson, grammar_topic, dialogue, hook, notice_sentences,
                            notice_note, challenge, real_life, theme_key=theme_key, level=LEVEL,
                            discussion=discussion)
    nn = f"{num:02d}"
    lesson_dir = f"slide-content/{LEVEL}/{nn}"
    os.makedirs(lesson_dir, exist_ok=True)
    for old in glob.glob(lesson_dir + "/slide-*.html"):
        os.remove(old)
    for i, html in enumerate(slides, start=1):
        with open(f"{lesson_dir}/slide-{i:02d}.html", "w", encoding="utf-8") as f:
            f.write(html)
    manifest[nn] = len(slides)
    print(f"{LEVEL} lesson {nn}: {len(slides)} slides [{theme_key}]" + (" [+grammar]" if grammar_topic else ""))

os.makedirs(f"assets/slides/{LEVEL}", exist_ok=True)
with open(f"assets/slides/{LEVEL}/manifest.json", "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=0)
print("Manifest written:", f"assets/slides/{LEVEL}/manifest.json")
