# -*- coding: utf-8 -*-
import sys, json, glob, os
sys.path.insert(0, "lib")
from deck_template_teen2 import build_deck_v2
from grammar_slides import match_grammar_by_lesson_focus

LEVEL = "level4"
_lessons = {}
for f in sorted(glob.glob(f"lessons/{LEVEL}/lesson*.json")):
    d = json.load(open(f, encoding="utf-8"))
    _lessons[d["number"]] = d
GRAMMAR_UNITS = match_grammar_by_lesson_focus(LEVEL, _lessons)

THEME_BY_LESSON = {
    1: "social", 2: "room", 3: "social", 4: "school", 5: "social", 6: "room",
    7: "room", 8: "money", 9: "money", 10: "sport", 11: "room", 12: "default",
    13: "social", 14: "sport", 15: "default", 16: "school", 17: "default",
    18: "default", 19: "school", 20: "default",
}

HOOKS = {
    1: "Do you know someone who seems busy 24/7? What do they always seem to be doing?",
    2: "What does your schedule actually look like on a normal day?",
    3: "How often do you really check your phone? Be honest.",
    4: "What's coming up on your calendar this month?",
    5: "What's your favorite way to stay in touch with friends?",
    6: "Have you ever argued about whose stuff is whose?",
    7: "What's always in your fridge or pantry at home?",
    8: "Do you check the price before you buy something? Always?",
    9: "Do you save money, spend it right away, or a bit of both?",
    10: "Who's the most talented person you know, and at what?",
    11: "Next time you're at a restaurant, what would you order?",
    12: "Has anyone ever given you advice that actually helped?",
    13: "How much of your day happens online, honestly?",
    14: "Think of a time teamwork made something way easier.",
    15: "What's the hardest decision you've made recently?",
    16: "What's something that makes you nervous, and how do you handle it?",
    17: "If you could have any career, what would it be?",
    18: "If you could visit any country, where would you go?",
    19: "Have you ever disagreed with teammates on a project? What happened?",
    20: "What's one goal you have for next year?",
}
CHALLENGES = {
    1: {"prompt": "Ask a partner 3 yes/no questions about their routine using Do/Does.", "hint": "Remember: Does + he/she/it, Do + I/you/we/they."},
    2: {"prompt": "Describe your own daily routine in 3 sentences.", "hint": "Use today's vocabulary words."},
    3: {"prompt": "Describe how often you do 3 different things.", "hint": "Daily, weekly, rarely, constantly, occasionally, never."},
    4: {"prompt": "Describe your week using 3 prepositions of time.", "hint": "Before, after, on, in, at."},
    5: {"prompt": "Describe how you'd contact 3 different people using object pronouns.", "hint": "Him, her, them, us, it."},
    6: {"prompt": "Point to 3 things and say who they belong to using possessive pronouns.", "hint": "Mine, yours, his, hers, ours, theirs."},
    7: {"prompt": "Ask a partner if they have any of 3 different foods.", "hint": "Some for yes-statements, any for questions/negatives."},
    8: {"prompt": "Ask about the price and quantity of 3 things.", "hint": "How much for uncountable, how many for countable."},
    9: {"prompt": "Describe your own saving habits in 3 sentences.", "hint": "Use today's vocabulary words."},
    10: {"prompt": "Describe the most talented person you know using superlatives.", "hint": "The most, the best, the biggest."},
    11: {"prompt": "Politely order 3 things using 'I'd like'.", "hint": "I'd like... / I would like..."},
    12: {"prompt": "Give a partner 3 pieces of advice using should/shouldn't.", "hint": "You should... / You shouldn't..."},
    13: {"prompt": "Describe your own online habits in 3 sentences.", "hint": "Use today's vocabulary words."},
    14: {"prompt": "Describe 3 ways you can be a good teammate.", "hint": "Use today's vocabulary words."},
    15: {"prompt": "Describe a real decision you need to make, in 3 sentences.", "hint": "Use today's vocabulary words."},
    16: {"prompt": "Describe how you feel before a test and why.", "hint": "Use today's feeling words."},
    17: {"prompt": "Describe your future goal in 3 sentences.", "hint": "Use today's vocabulary words."},
    18: {"prompt": "Describe a culture or country you'd like to explore.", "hint": "Use today's vocabulary words."},
    19: {"prompt": "Retell the story of the group project in your own words.", "hint": "Use at least 2 vocabulary words from the story."},
    20: {"prompt": "Describe one plan you have for next year in 3 sentences.", "hint": "Try to use words from at least 2 different lessons."},
}
REAL_LIFE = {
    1: "This week, ask someone 'Do you...?' or 'Does he/she...?' in English.",
    2: "Tonight, describe your actual routine to a family member in English.",
    3: "This week, tell someone how often you do something, in English.",
    4: "This week, describe your schedule using today's prepositions.",
    5: "Next time you message a friend, think of the sentence in English first.",
    6: "Next time something is yours or someone else's, say so in English.",
    7: "Next time you're in the kitchen, name 3 things using today's words.",
    8: "Next time you go shopping, ask 'How much is that?' in English.",
    9: "This week, talk about your own savings plan in English.",
    10: "This week, tell someone about the most talented person you know.",
    11: "Next time you order food, try using 'I'd like' in English.",
    12: "This week, give someone real advice using should/shouldn't.",
    13: "Next time you're online, describe what you're doing in English.",
    14: "This week, thank a teammate using today's vocabulary.",
    15: "Next time you face a choice, describe it in English.",
    16: "Next time you feel nervous or confident, say so in English.",
    17: "This week, tell someone about your future goal in English.",
    18: "This week, look up one fact about a culture that interests you.",
    19: "Think about your own group project experiences and describe one.",
    20: "Write down one real goal for next year, in English.",
}
DISCUSSIONS = {
    1: ["Talk about someone you know who seems busy 24/7 -- what does their day actually look like?",
        "What time do you usually wake up, and is it different on weekends?",
        "Do you think you get enough time to just relax and chill?",
        "Ask a partner: 'What's your evening routine before bed?'",
        "Is it possible to be too busy? What happens when someone never takes a break?"],
    2: ["Describe your typical daily schedule, from morning to night.",
        "Do you think you have too much screen time, or about the right amount?",
        "What's harder for you to stick to: a workout routine, or a homework routine?",
        "Ask someone: 'What time is your actual bedtime, and do you follow it?'",
        "Whose rules matter more for your daily routine -- yours, or your family's?"],
    3: ["Talk about something you do constantly, and something you almost never do.",
        "Is there a habit you do daily that you wish you could cut back on?",
        "What's something you only do occasionally that you wish you did more?",
        "Ask a partner: 'How often do you check your phone in a single hour?'",
        "Do you think most people are honest with themselves about how often they do things?"],
    4: ["Talk about your favorite holiday or break -- what do you always do?",
        "Are you someone who works right up to a deadline, or finishes early?",
        "What's the best part of the weekend for you -- Friday night, or Saturday?",
        "Ask someone: 'What are you looking forward to before this semester ends?'",
        "Do you prefer a busy schedule, or a lot of free time? Discuss."],
    5: ["Talk about how you usually stay in touch with friends -- texting, calling, or video chat?",
        "Do you reply to messages quickly, or do you take your time?",
        "Would you rather call someone or send a long message? Why?",
        "Ask a partner: 'If you could invite anyone to hang out this weekend, who would it be?'",
        "Is a video chat a good enough substitute for actually meeting in person?"],
    6: ["Talk about an item you own that you'd never lend to anyone.",
        "Have you ever lost something important, like a wallet or earbuds? What happened?",
        "Do you take good care of your things, or do you lose stuff a lot?",
        "Ask someone: 'What's the most expensive thing you personally own?'",
        "Is it rude to borrow something without asking first? Discuss."],
    7: ["Talk about your favorite snack, and why you love it.",
        "Do you prefer eating leftovers, or always having something fresh?",
        "Who does the grocery shopping in your house -- do you ever help?",
        "Ask a partner: 'What's always in your fridge, no matter what?'",
        "Would you rather cook something yourself, or have someone cook for you?"],
    8: ["Talk about how you usually get money -- allowance, gifts, or working for it?",
        "Do you check the price tag before buying something, or just grab it?",
        "Have you ever found a really good discount? What was it?",
        "Ask someone: 'Do you keep a budget, or just spend when you feel like it?'",
        "Is it more satisfying to spend money, or to save it?"],
    9: ["Talk about something you're currently saving up for.",
        "Do you find it easy or hard to save money instead of spending it?",
        "Have you ever borrowed or lent money to a friend? How did that go?",
        "Ask a partner: 'What's the last thing you spent your own money on?'",
        "If you earned extra money tomorrow, would you save it or spend it right away?"],
    10: ["Talk about someone you know who's genuinely talented at something.",
         "What's something unique about you that not many people know?",
         "Do you think being popular and being skilled are the same thing?",
         "Ask someone: 'What's the most impressive thing you've ever seen someone do?'",
         "Is talent something you're born with, or something you build? Discuss."],
    11: ["Talk about a restaurant or food you'd always recommend to a friend.",
         "Do you usually order the same thing, or try something new every time?",
         "What's the best suggestion someone has ever given you?",
         "Ask a partner: 'If you had to eat one meal for the rest of your life, what would it be?'",
         "Do you prefer making a choice yourself, or having someone else decide for you?"],
    12: ["Talk about the best piece of advice someone has ever given you.",
         "Is there a bad habit you've been trying to break?",
         "Do you usually take other people's advice, or do things your own way?",
         "Ask someone: 'What's one tip you'd give a new student at our school?'",
         "Is it easier to give advice, or to actually follow it?"],
    13: ["Talk about how much time you spend in group chats every day.",
         "Do you post a lot online, or mostly just watch what others share?",
         "Do notifications ever stress you out? How do you deal with that?",
         "Ask a partner: 'What's the last thing you commented on or liked?'",
         "Is being 'online friends' with someone the same as being real friends?"],
    14: ["Talk about a time you worked really well as part of a team.",
         "Do you usually prefer to lead, or to support someone else's lead?",
         "What does a good teammate actually do, in your opinion?",
         "Ask someone: 'Who's someone that always encourages you?'",
         "Can a team succeed if even one person doesn't contribute? Discuss."],
    15: ["Talk about a big decision you had to make recently.",
         "Do you usually think through the consequences first, or decide quickly?",
         "Have you ever had to compromise with a friend or family member? What happened?",
         "Ask a partner: 'If you had two good options, how would you choose between them?'",
         "Is it better to make your own decisions, even wrong ones, or to always ask for help?"],
    16: ["Talk about a time you felt really nervous, and how you got through it.",
         "What usually makes you feel calm when you're stressed?",
         "Do you consider yourself a confident person? Why or why not?",
         "Ask someone: 'What's something that made you feel really proud of yourself?'",
         "Is a little pressure ever a good thing, or is it always bad?"],
    17: ["Talk about a goal you really want to achieve in the next few years.",
         "What's your dream career, and why does it interest you?",
         "Is there something you're passionate about that not many people know?",
         "Ask a partner: 'Where do you see yourself in ten years?'",
         "Is it important to have a plan, or is it okay to just figure it out as you go?"],
    18: ["Talk about a tradition from your own culture that you love.",
         "If you could explore any country in the world, where would you go?",
         "Is there a custom from another culture that you find really interesting?",
         "Ask someone: 'What language would you love to learn, besides English?'",
         "Do you think traveling changes the way people think? Discuss."],
    19: ["Talk about a group project that went really well -- or really badly.",
         "What do you do when you disagree with a teammate about how to do something?",
         "Is it harder to compromise with friends, or with people you don't know well?",
         "Ask a partner: 'What's a project you're genuinely proud of?'",
         "What actually makes a group project work, in your experience?"],
    20: ["Looking back at this level, what's one thing you learned about yourself?",
         "If you had to give advice to someone starting this level, what would you say?",
         "Talk about a goal you have for your English going forward.",
         "Ask a partner: 'What's the most useful thing you learned in this level?'",
         "How do you want your daily schedule to look next year?"],
}
DIALOGUES = {
  1: [("Does your sister actually wake up at 5am every day, or is that a myth?", "هل تستيقظ أختك فعلاً الساعة الخامسة صباحاً كل يوم، أم أن هذا مجرد أسطورة؟"),
      ("It's real. She studies before school, then goes straight to practice after.", "هذا حقيقي. تدرس قبل المدرسة، ثم تذهب مباشرة للتمرين بعدها."),
      ("That's insane. Does she ever just relax, or is she always doing something?", "هذا جنوني. هل تسترخي أبداً، أم أنها دائماً تفعل شيئاً؟"),
      ("Barely. Weekends are the only time she lets herself chill for real.", "بالكاد. عطلة نهاية الأسبوع هي الوقت الوحيد الذي تسمح لنفسها فيه بالاسترخاء فعلاً."),
      ("I could never live like that. I'd rather hang out and figure life out slowly.", "لا أستطيع العيش هكذا أبداً. أفضل قضاء الوقت واكتشاف الحياة ببطء."),
      ("Honestly, same. I admire her, but that schedule would break me in a week.", "بصراحة، نفس الشيء. أنا معجب بها، لكن هذا الجدول سيرهقني في أسبوع.")],
  2: [("What does your actual schedule look like on a school night?", "كيف يبدو جدولك فعلاً في ليلة مدرسية؟"),
      ("Homework first, then a quick workout, then way too much screen time.", "الواجب أولاً، ثم تمرين سريع، ثم وقت شاشة طويل جداً."),
      ("Do you have a deadline for bedtime, or is that more of a suggestion?", "هل لديك موعد نهائي للنوم، أم أن هذا مجرد اقتراح؟"),
      ("Definitely a suggestion. My parents set one, but I always push it later.", "اقتراح بالتأكيد. والداي يحددان موعداً، لكنني دائماً أؤخره."),
      ("Same here. I always say 'five more minutes' and then it's an hour.", "نفس الشيء هنا. دائماً أقول 'خمس دقائق فقط' ثم تتحول لساعة كاملة."),
      ("Exactly. We should probably fix that before it becomes an actual problem.", "بالضبط. يجب أن نصلح هذا قبل أن يصبح مشكلة حقيقية.")],
  3: [("Be honest, how often do you actually clean your room -- daily or never?", "كن صادقاً، كم مرة تنظف غرفتك فعلاً -- يومياً أم أبداً؟"),
      ("Occasionally, if I'm being generous. Definitely not daily, that's for sure.", "أحياناً، إن كنت متساهلاً مع نفسي. بالتأكيد ليس يومياً، هذا مؤكد."),
      ("Same. I constantly say I'll do it weekly, but it rarely actually happens.", "نفس الشيء. أقول باستمرار إنني سأفعلها أسبوعياً، لكن نادراً ما يحدث ذلك فعلاً."),
      ("At least you admit it. I rarely even notice the mess anymore, honestly.", "على الأقل تعترف بذلك. أنا نادراً ما ألاحظ الفوضى بعد الآن، بصراحة."),
      ("That's concerning, but also relatable. Maybe we should make a real system.", "هذا مقلق، لكنه مفهوم أيضاً. ربما يجب أن نضع نظاماً حقيقياً."),
      ("Maybe. Or we just constantly ignore it like we've always done.", "ربما. أو نستمر في تجاهله كما فعلنا دائماً.")],
  4: [("Do you have anything going on before the weekend, or are you free?", "هل لديك شيء قبل عطلة نهاية الأسبوع، أم أنت متفرغ؟"),
      ("I have an appointment tomorrow, but after that I'm completely free.", "لدي موعد غداً، لكن بعده أنا متفرغ تماماً."),
      ("Perfect, because this semester has been exhausting and I need a break.", "ممتاز، لأن هذا الفصل الدراسي كان مرهقاً وأحتاج استراحة."),
      ("Same. I'm just counting down the days until the holiday starts.", "نفس الشيء. أعد الأيام حتى تبدأ العطلة."),
      ("Honestly, this deadline-after-deadline schedule needs to slow down.", "بصراحة، جدول المواعيد النهائية المتتالية هذا يحتاج أن يتباطأ."),
      ("Agreed. Let's actually enjoy the break this time instead of stressing about it.", "متفق. لنستمتع فعلاً بالعطلة هذه المرة بدلاً من التوتر بشأنها.")],
  5: [("Why do you never reply to my messages until like three hours later?", "لماذا لا ترد أبداً على رسائلي إلا بعد ثلاث ساعات تقريباً؟"),
      ("I'm sorry, I get so many notifications I genuinely miss half of them.", "آسف، أتلقى إشعارات كثيرة لدرجة أنني فعلاً أفوّت نصفها."),
      ("Fair enough. Should we just call instead of texting back and forth?", "معقول. هل يجب أن نتصل بدلاً من التراسل ذهاباً وإياباً؟"),
      ("Actually, let's video chat -- I want to show you something anyway.", "في الواقع، لنجري مكالمة فيديو -- أريد أن أريك شيئاً على أي حال."),
      ("Good idea. Or better, let's just meet up and skip the screens entirely.", "فكرة جيدة. أو الأفضل، لنلتقِ فقط ونتجاوز الشاشات تماماً."),
      ("Even better. I'll invite the others too, it'll be more fun in person.", "أفضل حتى. سأدعو الآخرين أيضاً، سيكون أكثر متعة شخصياً.")],
  6: [("Wait, are those my earbuds? I've been looking for them all week.", "لحظة، هل هذه سماعاتي؟ كنت أبحث عنها طوال الأسبوع."),
      ("Oh, oops, they were in my jacket pocket. Honestly, that's on me.", "أوه، آسف، كانت في جيب سترتي. بصراحة، هذا خطئي."),
      ("It's fine, but is that my notebook too, or am I imagining things?", "لا بأس، لكن هل هذا دفتري أيضاً، أم أنني أتخيل الأمور؟"),
      ("That one's actually mine, I promise. Check your wallet, maybe it's in your bag.", "هذا فعلاً دفتري، أعدك. تحقق من محفظتك، ربما هي في حقيبتك."),
      ("Found it! At least my sneakers and my bike are still where I left them.", "وجدتها! على الأقل حذائي الرياضي ودراجتي ما زالا حيث تركتهما."),
      ("For now. Give it time, something else of yours will mysteriously appear here.", "حالياً. أعطِ الأمر وقتاً، شيء آخر لك سيظهر هنا بشكل غامض.")],
  7: [("Do you have any snacks? I'm starving and my house has literally nothing.", "هل لديك وجبات خفيفة؟ أنا جائع جداً وبيتي لا يحتوي على شيء إطلاقاً."),
      ("Check the pantry, there should be something. The fridge only has leftovers.", "تحقق من المخزن، يجب أن يكون هناك شيء. الثلاجة تحتوي فقط على بقايا طعام."),
      ("Found some, but we're out of basically every good ingredient for anything real.", "وجدت بعضاً منها، لكننا نفد لدينا تقريباً كل مكون جيد لأي شيء حقيقي."),
      ("Yeah, we need groceries badly. My family keeps forgetting to go shopping.", "نعم، نحتاج البقالة بشدة. عائلتي تنسى دائماً الذهاب للتسوق."),
      ("Same here. Honestly, leftovers are starting to sound better than nothing.", "نفس الشيء هنا. بصراحة، بقايا الطعام بدأت تبدو أفضل من لا شيء."),
      ("Exactly my thinking. Let's just eat and deal with groceries tomorrow.", "بالضبط ما كنت أفكر فيه. لنأكل فقط ونتعامل مع البقالة غداً.")],
  8: [("Did you see the price tag on those shoes? That's basically my whole allowance.", "هل رأيت سعر ذلك الحذاء؟ هذا تقريباً كل مصروفي."),
      ("I know, but there's a discount this weekend, so it might actually be worth it.", "أعرف، لكن هناك خصم هذا الأسبوع، فقد يكون يستحق فعلاً."),
      ("Maybe, but that would seriously mess up my budget for the month.", "ربما، لكن هذا سيفسد ميزانيتي لهذا الشهر بشكل جدي."),
      ("True. I keep every receipt just to see where my money actually goes.", "صحيح. أحتفظ بكل إيصال فقط لأرى إلى أين يذهب مالي فعلاً."),
      ("Smart. My savings disappear and I genuinely can't explain where they went.", "ذكي. مدخراتي تختفي ولا أستطيع فعلاً تفسير أين ذهبت."),
      ("Honestly, same. Maybe we should start tracking it together, for real this time.", "بصراحة، نفس الشيء. ربما يجب أن نبدأ بتتبعها معاً، بجدية هذه المرة.")],
  9: [("How do you actually manage to save money? I spend mine the second I earn it.", "كيف تدير فعلاً توفير المال؟ أنا أنفق مالي لحظة كسبه."),
      ("Honestly, I just don't let myself touch it. Out of sight, out of mind.", "بصراحة، لا أسمح لنفسي بلمسه فقط. بعيداً عن العين بعيداً عن القلب."),
      ("That's smart. I always end up needing to borrow a little by the end of the month.", "هذا ذكي. أنا دائماً أحتاج لاقتراض القليل بنهاية الشهر."),
      ("I'd lend you some, but I'm saving every coin for something specific right now.", "كنت لأقرضك بعضاً، لكنني أوفر كل قرش لشيء محدد الآن."),
      ("Fair enough, I respect the discipline. What are you even saving for?", "معقول، أحترم هذا الانضباط. لماذا توفر أصلاً؟"),
      ("That's a secret for now. You'll find out once I actually earn enough.", "هذا سر حالياً. ستعرف بمجرد أن أكسب ما يكفي فعلاً.")],
  10: [("Okay, who's the most talented person in our entire grade, honestly?", "حسناً، من هو أكثر شخص موهوب في صفنا كله، بصراحة؟"),
       ("Probably her -- she's genuinely skilled at literally everything she tries.", "غالباً هي -- إنها ماهرة فعلاً في كل شيء تجربه."),
       ("True, that's impressive. But being popular isn't the same as being outstanding.", "صحيح، هذا مثير للإعجاب. لكن أن تكون مشهوراً ليس مثل أن تكون متميزاً."),
       ("Exactly. I'd rather be unique and good at one real thing than liked by everyone.", "بالضبط. أفضل أن أكون فريداً وجيداً في شيء واحد حقيقي على أن يحبني الجميع."),
       ("Same, honestly. Talent should matter more than just being well-known.", "نفس الشيء، بصراحة. الموهبة يجب أن تكون أهم من الشهرة فقط."),
       ("Agreed. That's basically the whole point of this conversation, isn't it?", "متفق. هذا أساساً كل مغزى هذا الحديث، أليس كذلك؟")],
  11: [("What are you going to order? I genuinely can't decide on anything.", "ماذا ستطلب؟ لا أستطيع فعلاً أن أقرر أي شيء."),
       ("I'd request whatever they recommend, honestly, I trust their choices here.", "سأطلب أياً كان ما يوصون به، بصراحة، أثق بخياراتهم هنا."),
       ("That's smart. I usually prefer picking something familiar, no surprises.", "هذا ذكي. عادة أفضل اختيار شيء مألوف، دون مفاجآت."),
       ("Fair, but can I suggest trying something new for once? Just this once.", "معقول، لكن هل يمكنني اقتراح تجربة شيء جديد لمرة واحدة؟ فقط هذه المرة."),
       ("Fine, you convinced me. What's your top choice on this whole menu?", "حسناً، أقنعتني. ما هو خيارك الأول في هذه القائمة كلها؟"),
       ("Honestly, I'd like whatever you're having. Decision made, finally.", "بصراحة، أريد أياً كان ما تطلبه أنت. القرار اتُخذ أخيراً.")],
  12: [("Can I give you some honest advice, even if it's not what you want to hear?", "هل يمكنني أن أعطيك نصيحة صادقة، حتى لو لم تكن ما تريد سماعه؟"),
       ("Sure, go ahead, I'll take your opinion seriously either way.", "بالتأكيد، تفضل، سآخذ رأيك بجدية على أي حال."),
       ("Okay, here's my suggestion: that habit of yours is going to cause problems.", "حسناً، إليك اقتراحي: تلك العادة لديك ستسبب مشاكل."),
       ("That's basically a warning, not a tip, but fair enough, you're not wrong.", "هذا أساساً تحذير، وليس نصيحة، لكن معقول، أنت لست مخطئاً."),
       ("I mean it kindly! I just think a small change now saves bigger regret later.", "أقصد ذلك بلطف! أعتقد فقط أن تغييراً صغيراً الآن يوفر ندماً أكبر لاحقاً."),
       ("You're right, honestly. I needed to hear that, even if it stung a little.", "أنت محق، بصراحة. كنت بحاجة لسماع هذا، حتى لو آلمني قليلاً.")],
  13: [("Did you see what she decided to post in the group chat this morning?", "هل رأيت ما قررت نشره في الدردشة الجماعية هذا الصباح؟"),
       ("I did, and honestly, the comments underneath were even more chaotic.", "رأيت، وبصراحة، التعليقات تحتها كانت أكثر فوضى."),
       ("I know, my notifications wouldn't stop buzzing the entire class.", "أعرف، إشعاراتي لم تتوقف عن الرنين طوال الحصة."),
       ("Same here. I had to mute it just so I could focus while online.", "نفس الشيء هنا. اضطررت لكتمها فقط لأستطيع التركيز وأنا متصل."),
       ("Smart move. I keep liking things I probably shouldn't share opinions on.", "خطوة ذكية. أستمر في الإعجاب بأشياء ربما لا يجب أن أشارك رأيي فيها."),
       ("Relatable. Group chats bring out the worst decision-making in all of us.", "مفهوم. الدردشات الجماعية تُظهر أسوأ قراراتنا جميعاً.")],
  14: [("Honestly, do you think you're more of a leader or a supporter on a team?", "بصراحة، هل تعتقد أنك أقرب لقائد أم داعم في الفريق؟"),
       ("Definitely a supporter. I'd rather encourage others than take charge myself.", "داعم بالتأكيد. أفضل تشجيع الآخرين على تولي القيادة بنفسي."),
       ("That makes sense. Real teamwork needs people who genuinely cooperate, not compete.", "هذا منطقي. العمل الجماعي الحقيقي يحتاج أشخاصاً يتعاونون فعلاً، لا يتنافسون."),
       ("Exactly. I just want to contribute something useful, credit doesn't matter to me.", "بالضبط. أريد فقط أن أساهم بشيء مفيد، الفضل لا يهمني."),
       ("That's a good mindset, honestly. Not everyone can say that and mean it.", "هذا تفكير جيد، بصراحة. ليس الجميع يستطيع قول هذا ويقصده فعلاً."),
       ("Thanks. I think teams work best when everyone supports each other equally.", "شكراً. أعتقد أن الفرق تعمل بشكل أفضل عندما يدعم الجميع بعضهم بالتساوي.")],
  15: [("I have a big decision to make and I genuinely don't know which option to pick.", "لدي قرار كبير يجب اتخاذه ولا أعرف فعلاً أي خيار أختار."),
       ("Have you actually considered the consequences of both choices carefully?", "هل فكرت فعلاً بعناية في عواقب كلا الخيارين؟"),
       ("A little, but I keep going back and forth without landing on anything solid.", "قليلاً، لكنني أستمر بالتردد دون الاستقرار على شيء واضح."),
       ("Maybe there's a compromise, some middle option you haven't thought of yet.", "ربما هناك حل وسط، خيار وسطي لم تفكر فيه بعد."),
       ("Actually, that's a really good point. I hadn't considered mixing the two.", "في الواقع، هذه نقطة جيدة جداً. لم أفكر بدمج الاثنين."),
       ("See, sometimes talking it through helps more than deciding completely alone.", "أترى، أحياناً الحديث عن الأمر يساعد أكثر من القرار بمفردك تماماً.")],
  16: [("Are you nervous about the presentation, or do you actually feel confident?", "هل أنت متوتر بشأن العرض التقديمي، أم تشعر بالثقة فعلاً؟"),
       ("Honestly, a mix. I try to stay calm, but I'm anxious right up until it starts.", "بصراحة، مزيج. أحاول أن أبقى هادئاً، لكنني قلق حتى بدايته مباشرة."),
       ("That's completely normal. Once it's over you'll probably just feel relieved.", "هذا طبيعي تماماً. بمجرد انتهائه ستشعر على الأرجح بالارتياح فقط."),
       ("I hope so. I really want to feel proud of how it goes, not just done with it.", "أتمنى ذلك. أريد فعلاً أن أفخر بكيفية سير الأمر، لا أن أشعر بالانتهاء فقط."),
       ("You will. You've prepared way more than you're giving yourself credit for.", "ستفعل. لقد استعددت أكثر بكثير مما تعطي لنفسك فضلاً عليه."),
       ("Thanks, honestly, I needed to hear that right before walking in there.", "شكراً، بصراحة، كنت بحاجة لسماع هذا قبل الدخول مباشرة.")],
  17: [("What's your actual dream career, or do you still have no idea?", "ما هي مهنة أحلامك فعلاً، أم أنك ما زلت لا تعرف؟"),
       ("Still figuring it out, honestly, but I know my passion is definitely art.", "ما زلت أكتشف ذلك، بصراحة، لكنني أعرف أن شغفي هو الفن بالتأكيد."),
       ("That's a solid start. Do you have a real goal for how to get there?", "هذه بداية جيدة. هل لديك هدف حقيقي لكيفية الوصول لذلك؟"),
       ("Kind of. My ambition is huge, but my plan is still pretty vague right now.", "نوعاً ما. طموحي كبير، لكن خطتي ما زالت غامضة جداً الآن."),
       ("That's okay, most people's plans are vague at first. You'll achieve it eventually.", "لا بأس، خطط معظم الناس غامضة في البداية. ستحققه في النهاية."),
       ("I hope so. At least talking about it out loud makes it feel more real.", "أتمنى ذلك. على الأقل الحديث عنه بصوت عالٍ يجعله يبدو أكثر واقعية.")],
  18: [("If you could explore anywhere in the world, where would your journey start?", "لو استطعت استكشاف أي مكان في العالم، أين ستبدأ رحلتك؟"),
       ("Honestly, somewhere with a totally different culture from mine, for the contrast.", "بصراحة، مكان بثقافة مختلفة تماماً عن ثقافتي، من أجل التباين."),
       ("Same. I'd love to learn a new language just by being surrounded by it daily.", "نفس الشيء. أحب أن أتعلم لغة جديدة بمجرد الانغماس فيها يومياً."),
       ("That's the best way to actually learn one. Is there a custom you'd want to experience?", "هذه أفضل طريقة لتعلمها فعلاً. هل هناك عادة تريد تجربتها؟"),
       ("Definitely a local tradition, something you can only really understand by living it.", "تقليد محلي بالتأكيد، شيء لا يمكن فهمه فعلاً إلا بعيشه."),
       ("Now I really want to plan an actual trip instead of just talking about one.", "الآن أريد فعلاً التخطيط لرحلة حقيقية بدلاً من مجرد الحديث عنها.")],
  19: [("Our project deadline is this week and we still completely disagree on the topic.", "الموعد النهائي لمشروعنا هذا الأسبوع وما زلنا نختلف تماماً حول الموضوع."),
       ("I know, but real teamwork means finding a compromise we can both live with.", "أعرف، لكن العمل الجماعي الحقيقي يعني إيجاد حل وسط يرضي كلينا."),
       ("Fair. What if we combine both our ideas instead of picking just one?", "معقول. ماذا لو دمجنا فكرتينا بدلاً من اختيار واحدة فقط؟"),
       ("Actually, that could genuinely work better than either version alone.", "في الواقع، قد ينجح هذا فعلاً بشكل أفضل من أي نسخة بمفردها."),
       ("Let's try it. I'd rather be proud of something we built together properly.", "لنجربه. أفضل أن أفخر بشيء بنيناه معاً بشكل صحيح."),
       ("Agreed. A little disagreement now beats regretting a rushed project later.", "متفق. خلاف بسيط الآن أفضل من الندم على مشروع متسرع لاحقاً.")],
  20: [("Looking back at this whole level, what's one goal you're proud you stuck to?", "بالنظر إلى هذا المستوى بأكمله، ما الهدف الذي تفخر بالتزامك به؟"),
       ("Honestly, actually sticking to a schedule instead of ignoring it completely.", "بصراحة، الالتزام فعلاً بجدول بدلاً من تجاهله تماماً."),
       ("Same, and I got better advice from you than I expected this whole journey.", "نفس الشيء، وحصلت على نصائح أفضل منك مما توقعت طوال هذه الرحلة."),
       ("Thanks, that means a lot. Teamwork really did make this level easier, honestly.", "شكراً، هذا يعني الكثير. العمل الجماعي جعل هذا المستوى أسهل فعلاً، بصراحة."),
       ("Definitely. I even started tracking my budget because of one message you sent.", "بالتأكيد. حتى بدأت بتتبع ميزانيتي بسبب رسالة واحدة أرسلتها."),
       ("That's what I like to hear. You're more talented and organized than you think.", "هذا ما أحب سماعه. أنت أكثر موهبة وتنظيماً مما تعتقد.")],
}

def make_notice_sentences(lesson_num, grammar_topic):
    sentences = []
    if grammar_topic:
        for ex in grammar_topic.get("examples", [])[:4]:
            sentences.append(ex["en"])
    other_lesson_num = 1 if lesson_num != 1 else 2
    other = _lessons.get(other_lesson_num)
    if other and other["vocab"]:
        sentences.append(other["vocab"][0]["example"])
    return sentences

os.makedirs(f"slide-content/{LEVEL}", exist_ok=True)
manifest = {}
for num in sorted(_lessons.keys()):
    lesson = _lessons[num]
    grammar_topic = GRAMMAR_UNITS.get(num)
    dialogue = DIALOGUES.get(num, [])
    theme_key = THEME_BY_LESSON.get(num, "default")
    hook = HOOKS.get(num, f"Let's talk about {lesson['title'].lower()}.")
    challenge = CHALLENGES.get(num)
    real_life = REAL_LIFE.get(num)
    discussion = DISCUSSIONS.get(num)
    notice_sentences = make_notice_sentences(num, grammar_topic)
    notice_note = grammar_topic["title"] if grammar_topic else ""

    slides = build_deck_v2(num, lesson, grammar_topic, dialogue, hook, notice_sentences,
                            notice_note, challenge, real_life, theme_key=theme_key, level=LEVEL,
                            discussion=discussion)
    nn = f"{num:02d}"
    lesson_dir = f"slide-content/{LEVEL}/{nn}"
    os.makedirs(lesson_dir, exist_ok=True)
    for old in glob.glob(lesson_dir + "/slide-*.html"):
        os.remove(old)
    for i, html in enumerate(slides, start=1):
        with open(f"{lesson_dir}/slide-{i:02d}.html", "w", encoding="utf-8") as f:
            f.write(html)
    manifest[nn] = len(slides)
    print(f"{LEVEL} lesson {nn}: {len(slides)} slides [{theme_key}]" + (" [+grammar]" if grammar_topic else ""))

os.makedirs(f"assets/slides/{LEVEL}", exist_ok=True)
with open(f"assets/slides/{LEVEL}/manifest.json", "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=0)
print("Manifest written:", f"assets/slides/{LEVEL}/manifest.json")
