# -*- coding: utf-8 -*-
import sys, json
sys.path.insert(0, "lib")
from deck_template_v2 import run

phonics_data = json.load(open("phonics-hub/level1.json", encoding="utf-8"))
# unit N is taught in lesson (2N-1): 1,3,5,7,9,11,13,15
PHONICS_UNITS = {2 * i - 1: u for i, u in enumerate(phonics_data["units"], 1)}

DIALOGUES = {
  1: [("L", "This is my friend.", "هذا صديقي."),
      ("R", "Nice to meet you! Who is this?", "تشرفنا! من هذا؟"),
      ("L", "This is my mom, and this is my dad.", "هذه أمي، وهذا أبي."),
      ("R", "Nice to meet your family!", "تشرفت بعائلتك!")],
  2: [("L", "How are you today?", "كيف حالك اليوم؟"),
      ("R", "I am happy! How are you?", "أنا سعيد! كيف حالك أنت؟"),
      ("L", "I am a little tired.", "أنا متعب قليلا."),
      ("R", "I hope you feel great soon!", "أتمنى أن تشعر بحال رائعة قريبا!")],
  3: [("L", "What is it?", "ما هذا؟"),
      ("R", "It is a cat! What is that?", "إنه قط! ما ذلك؟"),
      ("L", "It is a dog.", "إنه كلب."),
      ("R", "I like cats and dogs!", "أحب القطط والكلاب!")],
  4: [("L", "Look at that elephant!", "انظر إلى ذلك الفيل!"),
      ("R", "It is big! And look at the mouse.", "إنه كبير! وانظر إلى الفأر."),
      ("L", "It is small!", "إنه صغير!"),
      ("R", "Big and small animals are both fun.", "الحيوانات الكبيرة والصغيرة كلاهما ممتع.")],
  5: [("L", "Can you count to twenty?", "هل تستطيع العد إلى عشرين؟"),
      ("R", "Yes! Eleven, twelve, thirteen...", "نعم! أحد عشر، اثنا عشر، ثلاثة عشر..."),
      ("L", "What comes after nineteen?", "ماذا يأتي بعد التاسع عشر؟"),
      ("R", "Twenty!", "عشرون!")],
  6: [("L", "What color is it?", "ما لونه؟"),
      ("R", "It is red. What color is that?", "إنه أحمر. ما لون ذلك؟"),
      ("L", "It is blue!", "إنه أزرق!"),
      ("R", "I like blue and red.", "أحب الأزرق والأحمر.")],
  7: [("L", "Do you like apples?", "هل تحب التفاح؟"),
      ("R", "Yes, I like apples! I like juice too.", "نعم، أحب التفاح! أحب العصير أيضا."),
      ("L", "I like pizza and ice cream.", "أحب البيتزا والآيس كريم."),
      ("R", "Me too! Yummy!", "أنا أيضا! لذيذ!")],
  8: [("L", "Do you like broccoli?", "هل تحب البروكلي؟"),
      ("R", "No, I don't like broccoli.", "لا، لا أحب البروكلي."),
      ("L", "I don't like onions either.", "لا أحب البصل أيضا."),
      ("R", "What about beans?", "ماذا عن الفاصولياء؟")],
  9: [("L", "This is my house.", "هذا منزلي."),
      ("R", "Where is your bedroom?", "أين غرفة نومك؟"),
      ("L", "It is next to the kitchen.", "إنها بجانب المطبخ."),
      ("R", "I love your house!", "أحب منزلك!")],
  10: [("L", "What is in the kitchen?", "ماذا يوجد في المطبخ؟"),
      ("R", "There is a plate and a cup.", "يوجد طبق وكوب."),
      ("L", "And a spoon and a fork!", "وملعقة وشوكة!"),
      ("R", "Let's set the table!", "لنجهز الطاولة!")],
  11: [("L", "What are you wearing?", "ماذا ترتدي؟"),
      ("R", "I am wearing a shirt and pants.", "أرتدي قميصا وبنطالا."),
      ("L", "I am wearing a dress and shoes.", "أرتدي فستانا وحذاء."),
      ("R", "You look great!", "تبدو رائعا!")],
  12: [("L", "How is the weather today?", "كيف هو الطقس اليوم؟"),
      ("R", "It is sunny! How about tomorrow?", "إنه مشمس! ماذا عن الغد؟"),
      ("L", "It might be rainy and windy.", "قد يكون ممطرا وعاصفا."),
      ("R", "I hope it's not stormy!", "أتمنى ألا يكون عاصفا!")],
  13: [("L", "What day is it today?", "أي يوم اليوم؟"),
      ("R", "Today is Monday. What about tomorrow?", "اليوم الاثنين. ماذا عن الغد؟"),
      ("L", "Tomorrow is Tuesday.", "غدا الثلاثاء."),
      ("R", "I love Fridays and Saturdays!", "أحب الجمعة والسبت!")],
  14: [("L", "Can you swim?", "هل تستطيع السباحة؟"),
      ("R", "Yes, I can! Can you dance?", "نعم أستطيع! هل تستطيع الرقص؟"),
      ("L", "Yes, and I can sing too!", "نعم، وأستطيع الغناء أيضا!"),
      ("R", "Let's run and jump together!", "لنجرِ ونقفز معا!")],
  15: [("L", "Where is the ball?", "أين الكرة؟"),
      ("R", "It is under the table.", "إنها تحت الطاولة."),
      ("L", "And where is the book?", "وأين الكتاب؟"),
      ("R", "It is on the chair.", "إنه على الكرسي.")],
  16: [("L", "Do you have a pet?", "هل لديك حيوان أليف؟"),
      ("R", "Yes, I have a dog and a cat.", "نعم، لدي كلب وقطة."),
      ("L", "I have a rabbit and a turtle!", "لدي أرنب وسلحفاة!"),
      ("R", "Pets are wonderful friends.", "الحيوانات الأليفة أصدقاء رائعون.")],
  17: [("L", "Let's go to the park!", "لنذهب إلى الحديقة!"),
      ("R", "Yes! I want to play on the slide.", "نعم! أريد اللعب على الزحليقة."),
      ("L", "I want to fly my kite.", "أريد تطيير طائرتي الورقية."),
      ("R", "Let's sit on the bench after.", "لنجلس على المقعد بعد ذلك.")],
  18: [("L", "What shape is this?", "ما هذا الشكل؟"),
      ("R", "It is a circle! What is that?", "إنه دائرة! ما ذلك؟"),
      ("L", "It is a square.", "إنه مربع."),
      ("R", "I see a star and a heart too!", "أرى نجمة وقلبا أيضا!")],
  19: [("L", "Is the soup hot or cold?", "هل الحساء ساخن أم بارد؟"),
      ("R", "It is hot! Is the ice cream cold?", "إنه ساخن! هل الآيس كريم بارد؟"),
      ("L", "Yes, it's very cold!", "نعم، إنه بارد جدا!"),
      ("R", "Hot and cold, fast and slow -- opposites are fun!", "ساخن وبارد، سريع وبطيء -- الأضداد ممتعة!")],
  20: [("L", "Let's review everything we learned!", "لنراجع كل ما تعلمناه!"),
      ("R", "My friend is happy. My dog is big.", "صديقي سعيد. كلبي كبير."),
      ("L", "The apple is red. My house is sunny.", "التفاحة حمراء. منزلي مشمس."),
      ("R", "I can run in a circle! Great job, everyone!", "أستطيع الجري في دائرة! أحسنتم جميعا!")],
}

# See gen_slides_prea_v2.py's THEME_MAP for the reasoning behind reusable
# themes instead of one background per lesson.
THEME_MAP = {
    1: "classroom", 2: "classroom", 3: "classroom", 4: "playroom", 5: "classroom",
    6: "playroom", 7: "market", 8: "market", 9: "family-home", 10: "kitchen",
    11: "closet", 12: "weather-sky", 13: "classroom", 14: "park", 15: "bedroom",
    16: "animals", 17: "park", 18: "classroom", 19: "classroom", 20: "classroom",
}

# Real character-scene images illustrating this lesson's most important
# words, shown right before the sentence-building slides. See
# assets/vocab-scenes/level1/<NN>.jpg for the actual images.
SCENE_DATA = [
    (1, 1, ["boy", "girl"], "This is a boy. This is a girl."),
    (1, 2, ["teacher", "friend"], "This is my teacher. This is my friend."),
    (1, 3, ["mom", "dad"], "This is my mom. This is my dad."),
    (2, 4, ["happy", "sad"], "I am happy. You are sad."),
    (2, 5, ["fine", "tired"], "I am fine. You are tired."),
    (2, 6, ["okay", "great"], "I am okay. You are great!"),
    (3, 7, ["cat", "dog"], "It is a cat. It is a dog."),
    (3, 8, ["bird", "fish"], "It is a bird. It is a fish."),
    (3, 9, ["car", "ball"], "It is a car. It is a ball."),
    (4, 10, ["big", "elephant"], "The elephant is big!"),
    (4, 11, ["small", "mouse"], "The mouse is small!"),
    (4, 12, ["ball", "box"], "The ball is big. The box is small."),
    (5, 13, ["eleven", "twelve"], "I have eleven apples. I see twelve stars."),
    (5, 14, ["Fifteen", "Twenty"], "Fifteen balloons! Twenty balls!"),
    (5, 15, ["Thirteen", "Eighteen"], "Thirteen flowers. Eighteen books."),
    (6, 16, ["Red", "blue"], "What color is it? Red and blue!"),
    (6, 17, ["green", "yellow"], "The dress is green. The flowers are yellow."),
    (6, 18, ["pink", "orange"], "A pink balloon and an orange balloon!"),
    (7, 19, ["apples", "bananas"], "I like apples. I like bananas."),
    (7, 20, ["juice", "milk", "pizza"], "I like juice, milk, and pizza."),
    (7, 21, ["cake", "ice cream"], "I like cake. I like ice cream."),
    (8, 22, ["broccoli", "onions"], "I don't like broccoli. I don't like onions."),
    (8, 23, ["fish", "lemons"], "I don't like fish. I don't like lemons."),
    (8, 24, ["beans", "peas"], "I don't like beans. I don't like peas."),
    (9, 25, ["house", "door"], "This is my house. This is the door."),
    (9, 26, ["bedroom", "window"], "This is my bedroom. This is the window."),
    (9, 27, ["kitchen", "living room"], "The kitchen and the living room."),
    (10, 28, ["plate", "cup"], "Here is a plate. Here is a cup."),
    (10, 29, ["spoon", "fork", "knife"], "A spoon, a fork, and a knife."),
    (10, 30, ["fridge", "table", "chair"], "The fridge is next to the table and chair."),
    (11, 31, ["shirt", "pants"], "Ziad wears a shirt and pants."),
    (11, 32, ["dress", "shoes"], "Sara wears a dress and shoes."),
    (11, 33, ["hat", "jacket"], "Omar wears a hat and a jacket."),
    (12, 34, ["sunny", "hot"], "It is sunny. It is hot."),
    (12, 35, ["rainy", "cloudy"], "It is rainy. It is cloudy."),
    (12, 36, ["windy", "snowy"], "It is windy. It is snowy."),
    (13, 37, ["Monday", "Tuesday"], "Monday and Tuesday, I go to school."),
    (13, 38, ["Friday", "Saturday"], "Friday! Saturday! Time to play!"),
    (13, 39, ["Sunday"], "On Sunday, we rest together."),
    (14, 40, ["run", "jump"], "I can run. I can jump."),
    (14, 41, ["swim", "pool"], "I can swim in the pool."),
    (14, 42, ["sing", "dance"], "I can sing. I can dance."),
    (15, 43, ["in", "box"], "The toy is in the box."),
    (15, 44, ["on", "table"], "The book is on the table."),
    (15, 45, ["under", "chair"], "The ball is under the chair."),
    (16, 46, ["dog", "cat"], "My dog and my cat play together."),
    (16, 47, ["fish", "bird"], "This is my fish. This is my bird."),
    (16, 48, ["rabbit", "turtle", "hamster"], "I have a rabbit, a turtle, and a hamster."),
    (17, 49, ["slide", "swing"], "Omar plays on the slide. Ziad plays on the swing."),
    (17, 50, ["kite", "ball"], "Hamad flies a kite. Sara plays with a ball."),
    (17, 51, ["tree", "bench"], "Noor sits on a bench under the tree."),
    (18, 52, ["circle", "square"], "This is a circle. This is a square."),
    (18, 53, ["triangle", "star"], "The kite is a triangle. I see a star."),
    (18, 54, ["heart", "diamond"], "Noor draws a heart. Ziad has a diamond kite."),
    (19, 55, ["hot", "cold"], "It is hot. It is cold."),
    (19, 56, ["fast", "slow"], "Ziad is fast. The turtle is slow."),
    (19, 57, ["clean", "dirty"], "Sara's hands are clean. Hamad's hands are dirty."),
]
SCENE_MAP = {}
for lesson_num, img_num, bold_words, sentence in SCENE_DATA:
    SCENE_MAP.setdefault(lesson_num, []).append(
        (f"assets/vocab-scenes/level1/{img_num:02d}.jpg", sentence, bold_words)
    )

run("level1", DIALOGUES, PHONICS_UNITS, theme_map=THEME_MAP, scene_map=SCENE_MAP)
