# -*- coding: utf-8 -*-
import sys, json
sys.path.insert(0, "lib")
from deck_template_v2 import run

phonics_data = json.load(open("phonics-hub/level1.json", encoding="utf-8"))
# unit N is taught in lesson (2N-1): 1,3,5,7,9,11,13,15
PHONICS_UNITS = {2 * i - 1: u for i, u in enumerate(phonics_data["units"], 1)}

DIALOGUES = {
  1: [("This is my friend.", "هذا صديقي."),
      ("Nice to meet you! Who is this?", "تشرفنا! من هذا؟"),
      ("This is my mom, and this is my dad.", "هذه أمي، وهذا أبي."),
      ("Nice to meet your family!", "تشرفت بعائلتك!")],
  2: [("How are you today?", "كيف حالك اليوم؟"),
      ("I am happy! How are you?", "أنا سعيد! كيف حالك أنت؟"),
      ("I am a little tired.", "أنا متعب قليلا."),
      ("I hope you feel great soon!", "أتمنى أن تشعر بحال رائعة قريبا!")],
  3: [("What is it?", "ما هذا؟"),
      ("It is a cat! What is that?", "إنه قط! ما ذلك؟"),
      ("It is a dog.", "إنه كلب."),
      ("I like cats and dogs!", "أحب القطط والكلاب!")],
  4: [("Look at that elephant!", "انظر إلى ذلك الفيل!"),
      ("It is big! And look at the mouse.", "إنه كبير! وانظر إلى الفأر."),
      ("It is small!", "إنه صغير!"),
      ("Big and small animals are both fun.", "الحيوانات الكبيرة والصغيرة كلاهما ممتع.")],
  5: [("Can you count to twenty?", "هل تستطيع العد إلى عشرين؟"),
      ("Yes! Eleven, twelve, thirteen...", "نعم! أحد عشر، اثنا عشر، ثلاثة عشر..."),
      ("What comes after nineteen?", "ماذا يأتي بعد التاسع عشر؟"),
      ("Twenty!", "عشرون!")],
  6: [("What color is it?", "ما لونه؟"),
      ("It is red. What color is that?", "إنه أحمر. ما لون ذلك؟"),
      ("It is blue!", "إنه أزرق!"),
      ("I like blue and red.", "أحب الأزرق والأحمر.")],
  7: [("Do you like apples?", "هل تحب التفاح؟"),
      ("Yes, I like apples! I like juice too.", "نعم، أحب التفاح! أحب العصير أيضا."),
      ("I like pizza and ice cream.", "أحب البيتزا والآيس كريم."),
      ("Me too! Yummy!", "أنا أيضا! لذيذ!")],
  8: [("Do you like broccoli?", "هل تحب البروكلي؟"),
      ("No, I don't like broccoli.", "لا، لا أحب البروكلي."),
      ("I don't like onions either.", "لا أحب البصل أيضا."),
      ("What about beans?", "ماذا عن الفاصولياء؟")],
  9: [("This is my house.", "هذا منزلي."),
      ("Where is your bedroom?", "أين غرفة نومك؟"),
      ("It is next to the kitchen.", "إنها بجانب المطبخ."),
      ("I love your house!", "أحب منزلك!")],
  10: [("What is in the kitchen?", "ماذا يوجد في المطبخ؟"),
       ("There is a plate and a cup.", "يوجد طبق وكوب."),
       ("And a spoon and a fork!", "وملعقة وشوكة!"),
       ("Let's set the table!", "لنجهز الطاولة!")],
  11: [("What are you wearing?", "ماذا ترتدي؟"),
       ("I am wearing a shirt and pants.", "أرتدي قميصا وبنطالا."),
       ("I am wearing a dress and shoes.", "أرتدي فستانا وحذاء."),
       ("You look great!", "تبدو رائعا!")],
  12: [("How is the weather today?", "كيف هو الطقس اليوم؟"),
       ("It is sunny! How about tomorrow?", "إنه مشمس! ماذا عن الغد؟"),
       ("It might be rainy and windy.", "قد يكون ممطرا وعاصفا."),
       ("I hope it's not stormy!", "أتمنى ألا يكون عاصفا!")],
  13: [("What day is it today?", "أي يوم اليوم؟"),
       ("Today is Monday. What about tomorrow?", "اليوم الاثنين. ماذا عن الغد؟"),
       ("Tomorrow is Tuesday.", "غدا الثلاثاء."),
       ("I love Fridays and Saturdays!", "أحب الجمعة والسبت!")],
  14: [("Can you swim?", "هل تستطيع السباحة؟"),
       ("Yes, I can! Can you dance?", "نعم أستطيع! هل تستطيع الرقص؟"),
       ("Yes, and I can sing too!", "نعم، وأستطيع الغناء أيضا!"),
       ("Let's run and jump together!", "لنجرِ ونقفز معا!")],
  15: [("Where is the ball?", "أين الكرة؟"),
       ("It is under the table.", "إنها تحت الطاولة."),
       ("And where is the book?", "وأين الكتاب؟"),
       ("It is on the chair.", "إنه على الكرسي.")],
  16: [("Do you have a pet?", "هل لديك حيوان أليف؟"),
       ("Yes, I have a dog and a cat.", "نعم، لدي كلب وقطة."),
       ("I have a rabbit and a turtle!", "لدي أرنب وسلحفاة!"),
       ("Pets are wonderful friends.", "الحيوانات الأليفة أصدقاء رائعون.")],
  17: [("Let's go to the park!", "لنذهب إلى الحديقة!"),
       ("Yes! I want to play on the slide.", "نعم! أريد اللعب على الزحليقة."),
       ("I want to fly my kite.", "أريد تطيير طائرتي الورقية."),
       ("Let's sit on the bench after.", "لنجلس على المقعد بعد ذلك.")],
  18: [("What shape is this?", "ما هذا الشكل؟"),
       ("It is a circle! What is that?", "إنه دائرة! ما ذلك؟"),
       ("It is a square.", "إنه مربع."),
       ("I see a star and a heart too!", "أرى نجمة وقلبا أيضا!")],
  19: [("Is the soup hot or cold?", "هل الحساء ساخن أم بارد؟"),
       ("It is hot! Is the ice cream cold?", "إنه ساخن! هل الآيس كريم بارد؟"),
       ("Yes, it's very cold!", "نعم، إنه بارد جدا!"),
       ("Hot and cold, fast and slow -- opposites are fun!", "ساخن وبارد، سريع وبطيء -- الأضداد ممتعة!")],
  20: [("Let's review everything we learned!", "لنراجع كل ما تعلمناه!"),
       ("My friend is happy. My dog is big.", "صديقي سعيد. كلبي كبير."),
       ("The apple is red. My house is sunny.", "التفاحة حمراء. منزلي مشمس."),
       ("I can run in a circle! Great job, everyone!", "أستطيع الجري في دائرة! أحسنتم جميعا!")],
}

run("level1", DIALOGUES, PHONICS_UNITS)
