# -*- coding: utf-8 -*-
import json, os

LESSONS = [
  {"title": "What I Did This Weekend", "titleAr": "ماذا فعلت في نهاية الأسبوع",
   "goal": "I can talk about things I did in the past using regular verbs.",
   "grammarFocus": "Past Simple — Regular Verbs",
   "vocab": [
     {"en": "played", "ar": "لعب", "example": "I played football with my friends."},
     {"en": "watched", "ar": "شاهد", "example": "We watched a movie last night."},
     {"en": "walked", "ar": "مشى", "example": "She walked to the park."},
     {"en": "helped", "ar": "ساعد", "example": "He helped his mom in the kitchen."},
     {"en": "cleaned", "ar": "نظف", "example": "They cleaned their room."},
     {"en": "cooked", "ar": "طبخ", "example": "My dad cooked dinner."},
   ]},
  {"title": "Yesterday's Adventure", "titleAr": "مغامرة الأمس",
   "goal": "I can talk about the past using common irregular verbs.",
   "grammarFocus": "Past Simple — Irregular Verbs",
   "vocab": [
     {"en": "went", "ar": "ذهب", "example": "I went to the mall yesterday."},
     {"en": "saw", "ar": "رأى", "example": "We saw a great show."},
     {"en": "ate", "ar": "أكل", "example": "She ate pizza for lunch."},
     {"en": "had", "ar": "كان لديه", "example": "They had a great time."},
     {"en": "took", "ar": "أخذ", "example": "He took a lot of photos."},
     {"en": "got", "ar": "حصل على", "example": "I got a new phone."},
   ]},
  {"title": "Did You...?", "titleAr": "هل فعلت...؟",
   "goal": "I can ask and answer past-tense questions.",
   "grammarFocus": "Past Simple Negatives & Questions",
   "vocab": [
     {"en": "finish", "ar": "ينهي", "example": "Did you finish your homework?"},
     {"en": "forget", "ar": "ينسى", "example": "I didn't forget your birthday."},
     {"en": "miss", "ar": "يفوت", "example": "Did she miss the bus?"},
     {"en": "call", "ar": "يتصل", "example": "He didn't call me back."},
     {"en": "answer", "ar": "يجيب", "example": "Did they answer the question?"},
     {"en": "check", "ar": "يتحقق", "example": "I didn't check my messages."},
   ]},
  {"title": "How It Was", "titleAr": "كيف كان الأمر",
   "goal": "I can describe how things and people were in the past.",
   "grammarFocus": "Was / Were",
   "vocab": [
     {"en": "excited", "ar": "متحمس", "example": "I was excited about the trip."},
     {"en": "crowded", "ar": "مزدحم", "example": "The mall was crowded."},
     {"en": "quiet", "ar": "هادئ", "example": "The classroom was quiet."},
     {"en": "amazing", "ar": "مذهل", "example": "The concert was amazing."},
     {"en": "difficult", "ar": "صعب", "example": "The test was difficult."},
     {"en": "boring", "ar": "ممل", "example": "The movie was boring."},
   ]},
  {"title": "Back Then", "titleAr": "في ذلك الوقت",
   "goal": "I can describe what existed in a past situation.",
   "grammarFocus": "There was / There were",
   "vocab": [
     {"en": "crowd", "ar": "حشد", "example": "There was a huge crowd."},
     {"en": "line", "ar": "طابور", "example": "There was a long line."},
     {"en": "traffic", "ar": "ازدحام مروري", "example": "There was a lot of traffic."},
     {"en": "prize", "ar": "جائزة", "example": "There was a big prize."},
     {"en": "surprise", "ar": "مفاجأة", "example": "There was a surprise for everyone."},
     {"en": "problem", "ar": "مشكلة", "example": "There were a few problems."},
   ]},
  {"title": "Time Travel", "titleAr": "السفر عبر الزمن",
   "goal": "I can use time expressions to say when things happened.",
   "grammarFocus": "Time Expressions (ago, last, yesterday)",
   "vocab": [
     {"en": "yesterday", "ar": "أمس", "example": "I saw him yesterday."},
     {"en": "last week", "ar": "الأسبوع الماضي", "example": "We traveled last week."},
     {"en": "last night", "ar": "الليلة الماضية", "example": "I slept early last night."},
     {"en": "two days ago", "ar": "قبل يومين", "example": "She called me two days ago."},
     {"en": "last summer", "ar": "الصيف الماضي", "example": "We went to the beach last summer."},
     {"en": "a while ago", "ar": "منذ فترة", "example": "I met him a while ago."},
   ]},
  {"title": "And Then...", "titleAr": "ثم...",
   "goal": "I can tell a story in the right order using sequencing words.",
   "grammarFocus": "Sequencing Words (first, then, next, finally)",
   "vocab": [
     {"en": "first", "ar": "أولا", "example": "First, we packed our bags."},
     {"en": "then", "ar": "ثم", "example": "Then, we drove to the airport."},
     {"en": "next", "ar": "بعد ذلك", "example": "Next, we checked in."},
     {"en": "after that", "ar": "بعد ذلك", "example": "After that, we boarded the plane."},
     {"en": "finally", "ar": "أخيرا", "example": "Finally, we arrived."},
     {"en": "in the end", "ar": "في النهاية", "example": "In the end, it was a great trip."},
   ]},
  {"title": "Why It Happened", "titleAr": "لماذا حدث ذلك",
   "goal": "I can explain the reason for something using 'because'.",
   "grammarFocus": "Because (giving reasons)",
   "vocab": [
     {"en": "because", "ar": "لأن", "example": "I was late because I missed the bus."},
     {"en": "so", "ar": "لذلك", "example": "It was raining, so we stayed home."},
     {"en": "reason", "ar": "سبب", "example": "What's the reason for that?"},
     {"en": "excuse", "ar": "عذر", "example": "That's not a good excuse."},
     {"en": "explain", "ar": "يشرح", "example": "Can you explain why?"},
     {"en": "since", "ar": "بما أن", "example": "Since it was late, we went home."},
   ]},
  {"title": "How I Felt", "titleAr": "كيف شعرت",
   "goal": "I can describe how I felt about a past event.",
   "grammarFocus": "Feelings in the Past",
   "vocab": [
     {"en": "proud", "ar": "فخور", "example": "I was proud of my grade."},
     {"en": "nervous", "ar": "متوتر", "example": "She was nervous before the test."},
     {"en": "relieved", "ar": "مرتاح", "example": "We were relieved when it was over."},
     {"en": "disappointed", "ar": "محبط", "example": "He was disappointed with the result."},
     {"en": "surprised", "ar": "متفاجئ", "example": "I was surprised by the news."},
     {"en": "grateful", "ar": "ممتن", "example": "They were grateful for the help."},
   ]},
  {"title": "What Was Happening", "titleAr": "ماذا كان يحدث",
   "goal": "I can describe an action that was in progress in the past.",
   "grammarFocus": "Past Continuous (intro)",
   "vocab": [
     {"en": "was studying", "ar": "كان يدرس", "example": "I was studying when you called."},
     {"en": "was sleeping", "ar": "كان نائما", "example": "She was sleeping at 10pm."},
     {"en": "was raining", "ar": "كانت تمطر", "example": "It was raining all morning."},
     {"en": "were talking", "ar": "كانوا يتحدثون", "example": "They were talking about the game."},
     {"en": "was cooking", "ar": "كان يطبخ", "example": "My mom was cooking dinner."},
     {"en": "were waiting", "ar": "كانوا ينتظرون", "example": "We were waiting for the bus."},
   ]},
  {"title": "Study Story", "titleAr": "قصة الدراسة",
   "goal": "I can retell a past study session in order.",
   "grammarFocus": "Past Simple (review)",
   "vocab": [
     {"en": "reviewed", "ar": "راجع", "example": "I reviewed my notes."},
     {"en": "memorized", "ar": "حفظ", "example": "She memorized the vocabulary."},
     {"en": "practiced", "ar": "تمرن", "example": "We practiced together."},
     {"en": "passed", "ar": "نجح", "example": "He passed the test."},
     {"en": "struggled", "ar": "عانى", "example": "I struggled with the last question."},
     {"en": "improved", "ar": "تحسن", "example": "My grades improved."},
   ]},
  {"title": "The Big Trip", "titleAr": "الرحلة الكبيرة",
   "goal": "I can describe a trip I took using past tense.",
   "grammarFocus": "Past Simple (review, travel)",
   "vocab": [
     {"en": "packed", "ar": "حزم", "example": "I packed my suitcase."},
     {"en": "flew", "ar": "طار", "example": "We flew to a new city."},
     {"en": "explored", "ar": "استكشف", "example": "They explored the old town."},
     {"en": "arrived", "ar": "وصل", "example": "We arrived late at night."},
     {"en": "stayed", "ar": "أقام", "example": "We stayed at my aunt's house."},
     {"en": "returned", "ar": "عاد", "example": "I returned home on Sunday."},
   ]},
  {"title": "What Went Wrong", "titleAr": "ماذا حدث خطأ",
   "goal": "I can describe a problem that happened, and why.",
   "grammarFocus": "Because (review)",
   "vocab": [
     {"en": "broke", "ar": "كسر", "example": "I broke my phone because I dropped it."},
     {"en": "lost", "ar": "فقد", "example": "She lost her keys because she was in a hurry."},
     {"en": "spilled", "ar": "سكب", "example": "He spilled juice because he was running."},
     {"en": "late", "ar": "متأخر", "example": "We were late because of the traffic."},
     {"en": "mistake", "ar": "خطأ", "example": "I made a mistake because I was tired."},
     {"en": "fixed", "ar": "أصلح", "example": "I fixed it so it was okay."},
   ]},
  {"title": "The Party", "titleAr": "الحفلة",
   "goal": "I can describe a party or event that already happened.",
   "grammarFocus": "There was/were (review)",
   "vocab": [
     {"en": "guests", "ar": "ضيوف", "example": "There were a lot of guests."},
     {"en": "music", "ar": "موسيقى", "example": "There was great music."},
     {"en": "cake", "ar": "كعكة", "example": "There was a huge cake."},
     {"en": "games", "ar": "ألعاب", "example": "There were fun games."},
     {"en": "gifts", "ar": "هدايا", "example": "There were so many gifts."},
     {"en": "decorations", "ar": "زينة", "example": "There were colorful decorations."},
   ]},
  {"title": "A Day to Remember", "titleAr": "يوم لا يُنسى",
   "goal": "I can tell a full short story about a memorable day.",
   "grammarFocus": "Sequencing Words (review)",
   "vocab": [
     {"en": "woke up", "ar": "استيقظ", "example": "First, I woke up early."},
     {"en": "got ready", "ar": "استعد", "example": "Then, I got ready fast."},
     {"en": "left", "ar": "غادر", "example": "Next, we left the house."},
     {"en": "celebrated", "ar": "احتفل", "example": "After that, we celebrated together."},
     {"en": "remembered", "ar": "تذكر", "example": "I will always remember that day."},
     {"en": "unforgettable", "ar": "لا يُنسى", "example": "It was an unforgettable day."},
   ]},
  {"title": "While It Happened", "titleAr": "أثناء حدوثه",
   "goal": "I can describe two things happening at the same time in the past.",
   "grammarFocus": "Past Continuous (review)",
   "vocab": [
     {"en": "was texting", "ar": "كان يراسل", "example": "I was texting while I was walking."},
     {"en": "was listening", "ar": "كان يستمع", "example": "She was listening to music while studying."},
     {"en": "was laughing", "ar": "كان يضحك", "example": "He was laughing while telling the story."},
     {"en": "were watching", "ar": "كانوا يشاهدون", "example": "We were watching TV while eating."},
     {"en": "was thinking", "ar": "كان يفكر", "example": "I was thinking about the test."},
     {"en": "were playing", "ar": "كانوا يلعبون", "example": "They were playing while it was raining."},
   ]},
  {"title": "Interview a Classmate", "titleAr": "قابل زميل صف",
   "goal": "I can ask a partner questions about their past experiences.",
   "grammarFocus": "Past Simple Questions (review)",
   "vocab": [
     {"en": "experience", "ar": "تجربة", "example": "Tell me about your experience."},
     {"en": "favorite memory", "ar": "أفضل ذكرى", "example": "What's your favorite memory?"},
     {"en": "achievement", "ar": "إنجاز", "example": "What was your biggest achievement?"},
     {"en": "challenge", "ar": "تحدٍ", "example": "Did you face a challenge?"},
     {"en": "adventure", "ar": "مغامرة", "example": "Did you go on an adventure?"},
     {"en": "story", "ar": "قصة", "example": "Tell me a story from last year."},
   ]},
  {"title": "Movie Night Recap", "titleAr": "ملخص ليلة الأفلام",
   "goal": "I can describe an evening of watching something with friends, using past tense.",
   "grammarFocus": "Past Simple & Past Continuous (mixed review)",
   "vocab": [
     {"en": "chose", "ar": "اختار", "example": "We chose a scary movie."},
     {"en": "laughed", "ar": "ضحك", "example": "We laughed a lot during the film."},
     {"en": "was texting", "ar": "كان يراسل", "example": "He was texting while the movie played."},
     {"en": "fell asleep", "ar": "غفا", "example": "She fell asleep before the end."},
     {"en": "shared", "ar": "شارك", "example": "We shared popcorn."},
     {"en": "recommend", "ar": "يوصي", "example": "I would recommend that movie."},
   ]},
  {"title": "Reading Adventure: The Lost Backpack", "titleAr": "مغامرة قرائية: الحقيبة المفقودة",
   "goal": "I can read and understand a short past-tense story about a problem and how it was solved.",
   "grammarFocus": "Reading comprehension review",
   "vocab": [
     {"en": "lost", "ar": "فقد", "example": "I lost my backpack at school."},
     {"en": "searched", "ar": "بحث", "example": "We searched everywhere."},
     {"en": "found", "ar": "وجد", "example": "Finally, we found it."},
     {"en": "worried", "ar": "قلق", "example": "I was worried at first."},
     {"en": "relieved", "ar": "مرتاح", "example": "I felt relieved when I found it."},
     {"en": "careful", "ar": "حذر", "example": "Now I'm more careful with my things."},
   ]},
  {"title": "Review + My Story Project", "titleAr": "مراجعة + مشروع قصتي",
   "goal": "I can write and tell a full short story about something that happened to me.",
   "grammarFocus": "Review of all structures from Lessons 1-19",
   "vocab": [
     {"en": "played", "ar": "لعب", "example": "I played football with my friends."},
     {"en": "went", "ar": "ذهب", "example": "I went to the mall yesterday."},
     {"en": "excited", "ar": "متحمس", "example": "I was excited about the trip."},
     {"en": "because", "ar": "لأن", "example": "I was late because I missed the bus."},
     {"en": "finally", "ar": "أخيرا", "example": "Finally, we arrived."},
     {"en": "unforgettable", "ar": "لا يُنسى", "example": "It was an unforgettable day."},
     {"en": "proud", "ar": "فخور", "example": "I was proud of my grade."},
     {"en": "story", "ar": "قصة", "example": "Tell me a story from last year."},
   ]},
]

OUT_DIR = "lessons/level5"
os.makedirs(OUT_DIR, exist_ok=True)
for old in os.listdir(OUT_DIR) if os.path.exists(OUT_DIR) else []:
    os.remove(os.path.join(OUT_DIR, old))

for i, L in enumerate(LESSONS, start=1):
    num = f"{i:02d}"
    lesson = {
        "id": f"level5-{num}", "level": "level5", "number": i,
        "title": L["title"], "titleAr": L["titleAr"], "goal": L["goal"],
        "grammarFocus": L["grammarFocus"], "vocab": L["vocab"],
        "activities": [
            {"type": "vocab"}, {"type": "speak", "rounds": 3},
            {"type": "listen-choose", "rounds": 6}, {"type": "match"},
            {"type": "quiz", "rounds": 4}, {"type": "spell", "rounds": 3},
        ],
    }
    with open(os.path.join(OUT_DIR, f"lesson{num}.json"), "w", encoding="utf-8") as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)
        f.write("\n")

print(f"Wrote {len(LESSONS)} lesson files to {OUT_DIR}/")
