# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "lib")
from deck_template_v2 import run

DIALOGUES = {
  1: [("Hello! Nice to meet you!", "مرحبا! تشرفنا!"),
      ("Nice to meet you too! What's your name?", "تشرفنا أيضا! ما اسمك؟"),
      ("My name is Lumi. Thank you for saying hello!", "اسمي لومي. شكرا لك على الترحيب!"),
      ("You're welcome! Goodbye for now!", "عفوا! مع السلامة الآن!")],
  2: [("How old are you?", "كم عمرك؟"),
      ("I am eight years old. How old are you?", "عمري ثماني سنوات. كم عمرك أنت؟"),
      ("I am seven years old. My birthday is in May.", "عمري سبع سنوات. عيد ميلادي في مايو."),
      ("Happy early birthday!", "عيد ميلاد سعيد مقدما!")],
  3: [("This is my family tree. These are my grandparents.", "هذه شجرة عائلتي. هؤلاء أجدادي."),
      ("Who is this?", "من هذا؟"),
      ("This is my uncle, and this is my aunt.", "هذا عمي، وهذه عمتي."),
      ("You have a big family!", "لديك عائلة كبيرة!")],
  4: [("Look, who is that?", "انظر، من ذلك؟"),
      ("He is my brother. He is funny.", "هو أخي. هو مضحك."),
      ("And who is she?", "ومن هي؟"),
      ("She is my sister. She is smart.", "هي أختي. هي ذكية.")],
  5: [("Is this your bag?", "هل هذه حقيبتك؟"),
      ("No, that is not my bag. This is my bag.", "لا، تلك ليست حقيبتي. هذه حقيبتي."),
      ("Whose bag is that, then?", "حقيبة من تلك إذن؟"),
      ("That is her bag, I think.", "تلك حقيبتها على ما أظن.")],
  6: [("Have you got a phone?", "هل لديك هاتف؟"),
      ("Yes, I have got a new phone. Have you got a watch?", "نعم، لدي هاتف جديد. هل لديك ساعة؟"),
      ("I have got a watch and an umbrella too!", "لدي ساعة ومظلة أيضا!"),
      ("Wow, you have got a lot of things!", "واو، لديك أشياء كثيرة!")],
  7: [("My cheek hurts a little.", "خدي يؤلمني قليلا."),
      ("Oh no! Is your chin okay?", "يا للأسف! هل ذقنك بخير؟"),
      ("Yes, my chin is fine. My elbow hurts too.", "نعم، ذقني بخير. مرفقي يؤلمني أيضا."),
      ("Let's ask the teacher for help.", "لنسأل المعلمة للمساعدة.")],
  8: [("There is a big board in our classroom.", "هناك سبورة كبيرة في فصلنا."),
      ("Is there a playground too?", "هل هناك ملعب أيضا؟"),
      ("Yes! There is a playground next to the classroom.", "نعم! هناك ملعب بجانب الفصل."),
      ("I love our classroom and playground!", "أحب فصلنا وملعبنا!")],
  9: [("Please stand up, everyone.", "من فضلكم، قفوا جميعا."),
      ("Okay! Now what?", "حسنا! والآن؟"),
      ("Now sit down and listen carefully.", "الآن اجلسوا واستمعوا بانتباه."),
      ("Should we open our books too?", "هل نفتح كتبنا أيضا؟")],
  10: [("Can you count to a hundred?", "هل تستطيع العد إلى مئة؟"),
       ("I can count by tens: twenty, thirty, forty...", "أستطيع العد بالعشرات: عشرون، ثلاثون، أربعون..."),
       ("Great! What comes after eighty?", "رائع! ماذا يأتي بعد الثمانين؟"),
       ("Ninety, then one hundred!", "تسعون، ثم مئة!")],
  11: [("When is your birthday?", "متى عيد ميلادك؟"),
       ("My birthday is in January. What month is it now?", "عيد ميلادي في يناير. ما الشهر الآن؟"),
       ("It is September. School just started.", "إنه سبتمبر. بدأت المدرسة للتو."),
       ("My favorite month is June, no school!", "شهري المفضل هو يونيو، لا مدرسة!")],
  12: [("We are having a birthday party today!", "لدينا حفلة عيد ميلاد اليوم!"),
       ("Wonderful! Are there balloons and a cake?", "رائع! هل هناك بالونات وكعكة؟"),
       ("Yes, and candles too! Every guest gets a present.", "نعم، وشموع أيضا! كل ضيف يحصل على هدية."),
       ("I can't wait for the cake!", "لا أستطيع الانتظار للكعكة!")],
  13: [("What time is it?", "كم الساعة؟"),
       ("It is three o'clock. Look at the clock!", "الساعة الثالثة تماما. انظر إلى الساعة!"),
       ("Is it afternoon or evening?", "هل هو بعد الظهر أم المساء؟"),
       ("It is the afternoon. School ends soon.", "إنه بعد الظهر. تنتهي المدرسة قريبا.")],
  14: [("What do you do every morning?", "ماذا تفعل كل صباح؟"),
       ("I wake up, then I brush my teeth.", "أستيقظ، ثم أنظف أسناني."),
       ("Do you have breakfast before school?", "هل تتناول الفطور قبل المدرسة؟"),
       ("Yes, I have breakfast, then I go to school.", "نعم، أتناول الفطور، ثم أذهب إلى المدرسة.")],
  15: [("What do you do in the evening?", "ماذا تفعل في المساء؟"),
       ("I come home, then I do my homework.", "أعود إلى المنزل، ثم أؤدي واجبي."),
       ("Do you read before bed?", "هل تقرأ قبل النوم؟"),
       ("Yes, I read a book, then I go to bed.", "نعم، أقرأ كتابا، ثم أذهب إلى النوم.")],
  16: [("What do you eat for breakfast?", "ماذا تأكل في الفطور؟"),
       ("I eat eggs for breakfast. What about lunch?", "آكل بيضا في الفطور. ماذا عن الغداء؟"),
       ("I eat healthy food for lunch, like vegetables.", "آكل طعاما صحيا في الغداء، مثل الخضار."),
       ("I drink a lot of water every day too.", "أشرب الكثير من الماء كل يوم أيضا.")],
  17: [("Do you like drawing?", "هل تحب الرسم؟"),
       ("Yes, I do! I like drawing and painting.", "نعم، أحب! أحب الرسم والتلوين."),
       ("Do you like singing?", "هل تحب الغناء؟"),
       ("No, I don't. But I like dancing!", "لا، لا أحب. لكن أحب الرقص!")],
  18: [("This is my pencil. What is that?", "هذا قلمي. ما ذلك؟"),
       ("That is your bag, over there.", "تلك حقيبتك، هناك."),
       ("And these are my books!", "وهذه كتبي!"),
       ("Those are nice books!", "تلك كتب جميلة!")],
  19: [("I have two boxes here.", "لدي صندوقان هنا."),
       ("How many children are playing outside?", "كم طفلا يلعبون في الخارج؟"),
       ("Three children are playing. Look, two babies are sleeping.", "ثلاثة أطفال يلعبون. انظر، طفلان رضيعان نائمان."),
       ("And two men are watching them.", "ورجلان يراقبانهم.")],
  20: [("Hello! Let's talk about my family and my classroom.", "مرحبا! دعنا نتحدث عن عائلتي وفصلي."),
       ("What do you eat for breakfast?", "ماذا تأكل في الفطور؟"),
       ("I eat breakfast, then I like drawing before school.", "آكل الفطور، ثم أحب الرسم قبل المدرسة."),
       ("Happy birthday, by the way! Look at the clock — time for class!", "عيد ميلاد سعيد بالمناسبة! انظر إلى الساعة — حان وقت الحصة!")],
}

run("level2", DIALOGUES)
