# -*- coding: utf-8 -*-
import json, os

LESSONS = [
  {"title": "Meet the Crew", "titleAr": "تعرف على الشلة",
   "goal": "I can talk about what my friends and I do together.",
   "grammarFocus": "Present Simple (I/you/we/they)",
   "vocab": [
     {"en": "hang out", "ar": "يقضي وقتا مع الأصدقاء", "example": "We hang out after school."},
     {"en": "chat", "ar": "يتحدث", "example": "I chat with my friends every day."},
     {"en": "text", "ar": "يراسل نصيا", "example": "They text each other all the time."},
     {"en": "laugh", "ar": "يضحك", "example": "We laugh a lot together."},
     {"en": "joke", "ar": "نكتة", "example": "He always makes a joke."},
     {"en": "crew", "ar": "الشلة", "example": "My crew is the best."},
   ]},
  {"title": "What Do They Do?", "titleAr": "ماذا يفعلون؟",
   "goal": "I can describe what someone else does regularly.",
   "grammarFocus": "Present Simple (he/she/it + -s)",
   "vocab": [
     {"en": "plays", "ar": "يلعب (هو)", "example": "She plays basketball every week."},
     {"en": "studies", "ar": "يدرس (هو)", "example": "He studies after dinner."},
     {"en": "watches", "ar": "يشاهد (هو)", "example": "She watches videos online."},
     {"en": "listens", "ar": "يستمع (هو)", "example": "He listens to music on the bus."},
     {"en": "practices", "ar": "يتمرن (هو)", "example": "She practices guitar every day."},
     {"en": "trains", "ar": "يتدرب (هو)", "example": "He trains with his team."},
   ]},
  {"title": "Not My Thing", "titleAr": "هذا ليس ما أحب",
   "goal": "I can say what I don't like or don't do.",
   "grammarFocus": "Present Simple Negatives",
   "vocab": [
     {"en": "boring", "ar": "ممل", "example": "I don't like boring shows."},
     {"en": "awesome", "ar": "رائع", "example": "This game is awesome."},
     {"en": "weird", "ar": "غريب", "example": "That sounds weird."},
     {"en": "annoying", "ar": "مزعج", "example": "I don't like annoying noises."},
     {"en": "cool", "ar": "رائع (عامية)", "example": "Your jacket is so cool."},
     {"en": "lame", "ar": "تافه", "example": "I don't watch lame movies."},
   ]},
  {"title": "My Room", "titleAr": "غرفتي",
   "goal": "I can describe what's in my room.",
   "grammarFocus": "There is / There are",
   "vocab": [
     {"en": "poster", "ar": "ملصق", "example": "There is a poster on my wall."},
     {"en": "shelf", "ar": "رف", "example": "There are books on the shelf."},
     {"en": "desk", "ar": "مكتب", "example": "There is a desk by the window."},
     {"en": "lamp", "ar": "مصباح", "example": "There is a lamp on my desk."},
     {"en": "speaker", "ar": "سماعة", "example": "There is a speaker on my shelf."},
     {"en": "beanbag", "ar": "كرسي إسفنجي", "example": "There is a beanbag in the corner."},
   ]},
  {"title": "This or That?", "titleAr": "هذا أم ذاك؟",
   "goal": "I can compare and choose between things.",
   "grammarFocus": "This / That / These / Those",
   "vocab": [
     {"en": "sneakers", "ar": "حذاء رياضي", "example": "These sneakers are new."},
     {"en": "headphones", "ar": "سماعات رأس", "example": "Those headphones are mine."},
     {"en": "backpack", "ar": "حقيبة ظهر", "example": "This backpack is heavy."},
     {"en": "hoodie", "ar": "سترة بقلنسوة", "example": "That hoodie looks warm."},
     {"en": "cap", "ar": "قبعة", "example": "This cap is my favorite."},
     {"en": "jacket", "ar": "سترة", "example": "Those jackets are on sale."},
   ]},
  {"title": "Squad Goals", "titleAr": "أهداف المجموعة",
   "goal": "I can talk about the people in my life using plurals.",
   "grammarFocus": "Plural Nouns",
   "vocab": [
     {"en": "teammates", "ar": "زملاء الفريق", "example": "My teammates are awesome."},
     {"en": "classmates", "ar": "زملاء الصف", "example": "My classmates help me study."},
     {"en": "siblings", "ar": "الإخوة والأخوات", "example": "I have two siblings."},
     {"en": "cousins", "ar": "أبناء العم/الخال", "example": "My cousins visit us often."},
     {"en": "neighbors", "ar": "الجيران", "example": "Our neighbors are friendly."},
     {"en": "followers", "ar": "المتابعون", "example": "She has many followers."},
   ]},
  {"title": "Whose Phone Is This?", "titleAr": "لمن هذا الهاتف؟",
   "goal": "I can talk about my personal things.",
   "grammarFocus": "Possessive Adjectives",
   "vocab": [
     {"en": "phone", "ar": "هاتف", "example": "This is my phone."},
     {"en": "charger", "ar": "شاحن", "example": "Is this your charger?"},
     {"en": "earbuds", "ar": "سماعات أذن", "example": "These are her earbuds."},
     {"en": "password", "ar": "كلمة السر", "example": "That is his password, not mine."},
     {"en": "screen", "ar": "شاشة", "example": "Our screen is cracked."},
     {"en": "app", "ar": "تطبيق", "example": "Their app is really fun."},
   ]},
  {"title": "Around School", "titleAr": "في أرجاء المدرسة",
   "goal": "I can describe where things are around school.",
   "grammarFocus": "Prepositions of Place",
   "vocab": [
     {"en": "locker", "ar": "خزانة", "example": "My locker is next to the door."},
     {"en": "hallway", "ar": "الممر", "example": "We meet in the hallway."},
     {"en": "cafeteria", "ar": "الكافيتيريا", "example": "The cafeteria is behind the gym."},
     {"en": "gym", "ar": "صالة رياضية", "example": "The gym is in front of the library."},
     {"en": "library", "ar": "مكتبة", "example": "The library is above the cafeteria."},
     {"en": "playground", "ar": "ساحة اللعب", "example": "The playground is between the gym and the gate."},
   ]},
  {"title": "Can You Skate?", "titleAr": "هل تستطيع التزلج؟",
   "goal": "I can talk about skills I have and don't have.",
   "grammarFocus": "Can / Can't (Ability)",
   "vocab": [
     {"en": "skateboard", "ar": "يتزلج بلوح", "example": "Can you skateboard?"},
     {"en": "dance", "ar": "يرقص", "example": "She can dance really well."},
     {"en": "code", "ar": "يبرمج", "example": "He can code a simple game."},
     {"en": "bake", "ar": "يخبز", "example": "I can bake cookies."},
     {"en": "swim", "ar": "يسبح", "example": "Can you swim fast?"},
     {"en": "draw", "ar": "يرسم", "example": "She can draw anime characters."},
   ]},
  {"title": "20 Questions", "titleAr": "٢٠ سؤالا",
   "goal": "I can ask different kinds of questions to find something out.",
   "grammarFocus": "Wh- Questions",
   "vocab": [
     {"en": "guess", "ar": "يخمن", "example": "Can you guess what it is?"},
     {"en": "clue", "ar": "دليل", "example": "Give me a clue!"},
     {"en": "mystery", "ar": "لغز", "example": "This is a mystery."},
     {"en": "riddle", "ar": "أحجية", "example": "I love a good riddle."},
     {"en": "answer", "ar": "إجابة", "example": "What's your answer?"},
     {"en": "secret", "ar": "سر", "example": "It's a secret!"},
   ]},
  {"title": "Who's Faster?", "titleAr": "من الأسرع؟",
   "goal": "I can compare people and things.",
   "grammarFocus": "Comparatives (bigger, smaller)",
   "vocab": [
     {"en": "race", "ar": "سباق", "example": "Let's have a race."},
     {"en": "score", "ar": "نتيجة", "example": "My score is higher than yours."},
     {"en": "record", "ar": "رقم قياسي", "example": "She broke the record."},
     {"en": "opponent", "ar": "منافس", "example": "My opponent is strong."},
     {"en": "medal", "ar": "ميدالية", "example": "He won a gold medal."},
     {"en": "faster", "ar": "أسرع", "example": "I am faster than my brother."},
   ]},
  {"title": "The New Kid", "titleAr": "الطالب الجديد",
   "goal": "I can welcome someone new and talk about them.",
   "grammarFocus": "Articles: a / an / the",
   "vocab": [
     {"en": "newcomer", "ar": "الوافد الجديد", "example": "She is a newcomer at school."},
     {"en": "nervous", "ar": "متوتر", "example": "The new kid looks nervous."},
     {"en": "welcome", "ar": "يرحب", "example": "Let's welcome him."},
     {"en": "introduce", "ar": "يعرّف", "example": "I will introduce her to the class."},
     {"en": "stranger", "ar": "غريب", "example": "He isn't a stranger anymore."},
     {"en": "friendly", "ar": "ودود", "example": "She is very friendly."},
   ]},
  {"title": "Classroom Rules", "titleAr": "قواعد الصف",
   "goal": "I can understand and give classroom instructions.",
   "grammarFocus": "Imperatives (Commands)",
   "vocab": [
     {"en": "raise your hand", "ar": "ارفع يدك", "example": "Raise your hand to answer."},
     {"en": "be quiet", "ar": "كن هادئا", "example": "Please be quiet."},
     {"en": "line up", "ar": "قف في طابور", "example": "Line up at the door."},
     {"en": "pay attention", "ar": "انتبه", "example": "Pay attention, please."},
     {"en": "submit", "ar": "يسلّم", "example": "Submit your homework."},
     {"en": "participate", "ar": "يشارك", "example": "Participate in class."},
   ]},
  {"title": "Right Now", "titleAr": "الآن",
   "goal": "I can say what's happening at this exact moment.",
   "grammarFocus": "Present Continuous (I am doing)",
   "vocab": [
     {"en": "texting", "ar": "يراسل الآن", "example": "I am texting my friend."},
     {"en": "streaming", "ar": "يبث الآن", "example": "She is streaming a game."},
     {"en": "scrolling", "ar": "يتصفح الآن", "example": "He is scrolling his phone."},
     {"en": "gaming", "ar": "يلعب ألعاب فيديو الآن", "example": "They are gaming right now."},
     {"en": "chilling", "ar": "يسترخي الآن", "example": "We are chilling at home."},
     {"en": "studying", "ar": "يدرس الآن", "example": "She is studying for a test."},
   ]},
  {"title": "Study Buddies", "titleAr": "رفاق الدراسة",
   "goal": "I can talk about how I study with others.",
   "grammarFocus": "Present Continuous (review)",
   "vocab": [
     {"en": "highlight", "ar": "يبرز بالألوان", "example": "I am highlighting the key points."},
     {"en": "memorize", "ar": "يحفظ", "example": "We are memorizing new words."},
     {"en": "quiz", "ar": "اختبار قصير", "example": "We have a quiz tomorrow."},
     {"en": "flashcard", "ar": "بطاقة تعليمية", "example": "I am making flashcards."},
     {"en": "group project", "ar": "مشروع جماعي", "example": "We are working on a group project."},
     {"en": "presentation", "ar": "عرض تقديمي", "example": "She is preparing a presentation."},
   ]},
  {"title": "Game Night", "titleAr": "ليلة الألعاب",
   "goal": "I can talk about playing games and who's winning.",
   "grammarFocus": "Comparatives (review)",
   "vocab": [
     {"en": "champion", "ar": "بطل", "example": "He is the champion."},
     {"en": "controller", "ar": "ذراع تحكم", "example": "Pass me the controller."},
     {"en": "teammate", "ar": "زميل الفريق", "example": "My teammate is amazing."},
     {"en": "strategy", "ar": "استراتيجية", "example": "We need a better strategy."},
     {"en": "level up", "ar": "يرتقي مستوى", "example": "I leveled up!"},
     {"en": "high score", "ar": "أعلى نتيجة", "example": "That's the high score."},
   ]},
  {"title": "Movie Marathon", "titleAr": "ماراثون الأفلام",
   "goal": "I can talk about movies I like and don't like.",
   "grammarFocus": "This/That/These/Those (review)",
   "vocab": [
     {"en": "genre", "ar": "نوع (فيلم)", "example": "What genre do you like?"},
     {"en": "subtitle", "ar": "ترجمة", "example": "This movie has subtitles."},
     {"en": "popcorn", "ar": "فشار", "example": "Let's get popcorn."},
     {"en": "screen", "ar": "شاشة", "example": "That screen is huge."},
     {"en": "trailer", "ar": "إعلان الفيلم", "example": "This trailer looks exciting."},
     {"en": "sequel", "ar": "الجزء التالي", "example": "I can't wait for the sequel."},
   ]},
  {"title": "Big Questions", "titleAr": "أسئلة مهمة",
   "goal": "I can ask about and share opinions.",
   "grammarFocus": "Wh- Questions (review)",
   "vocab": [
     {"en": "opinion", "ar": "رأي", "example": "What's your opinion?"},
     {"en": "agree", "ar": "يوافق", "example": "I agree with you."},
     {"en": "disagree", "ar": "يختلف", "example": "I disagree, actually."},
     {"en": "decide", "ar": "يقرر", "example": "Let's decide together."},
     {"en": "choice", "ar": "خيار", "example": "It's your choice."},
     {"en": "reason", "ar": "سبب", "example": "What's the reason?"},
   ]},
  {"title": "Reading Adventure: The Big Match", "titleAr": "مغامرة قرائية: المباراة الكبرى",
   "goal": "I can read and understand a short story about a school sports match.",
   "grammarFocus": "Reading comprehension review",
   "vocab": [
     {"en": "match", "ar": "مباراة", "example": "Our school has a big match today."},
     {"en": "cheer", "ar": "يشجع", "example": "We cheer for our team."},
     {"en": "nervous", "ar": "متوتر", "example": "She feels nervous before the match."},
     {"en": "proud", "ar": "فخور", "example": "The coach is proud of the team."},
     {"en": "win", "ar": "يفوز", "example": "We want to win the match."},
     {"en": "teamwork", "ar": "العمل الجماعي", "example": "Teamwork made the difference."},
   ]},
  {"title": "Review + Time Capsule Project", "titleAr": "مراجعة + مشروع كبسولة الزمن",
   "goal": "I can talk about my life, friends, and school using everything I've learned.",
   "grammarFocus": "Review of all structures from Lessons 1-19",
   "vocab": [
     {"en": "hang out", "ar": "يقضي وقتا مع الأصدقاء", "example": "We hang out after school."},
     {"en": "teammates", "ar": "زملاء الفريق", "example": "My teammates are awesome."},
     {"en": "phone", "ar": "هاتف", "example": "This is my phone."},
     {"en": "locker", "ar": "خزانة", "example": "My locker is next to the door."},
     {"en": "champion", "ar": "بطل", "example": "He is the champion."},
     {"en": "opinion", "ar": "رأي", "example": "What's your opinion?"},
     {"en": "teamwork", "ar": "العمل الجماعي", "example": "Teamwork made the difference."},
     {"en": "proud", "ar": "فخور", "example": "The coach is proud of the team."},
   ]},
]

OUT_DIR = "lessons/level3"
os.makedirs(OUT_DIR, exist_ok=True)
for old in os.listdir(OUT_DIR):
    os.remove(os.path.join(OUT_DIR, old))

for i, L in enumerate(LESSONS, start=1):
    num = f"{i:02d}"
    lesson = {
        "id": f"level3-{num}", "level": "level3", "number": i,
        "title": L["title"], "titleAr": L["titleAr"], "goal": L["goal"],
        "grammarFocus": L["grammarFocus"], "vocab": L["vocab"],
        "activities": [
            {"type": "vocab"}, {"type": "speak", "rounds": 3},
            {"type": "listen-choose", "rounds": 6}, {"type": "match"},
            {"type": "quiz", "rounds": 4}, {"type": "spell", "rounds": 3},
        ],
    }
    with open(os.path.join(OUT_DIR, f"lesson{num}.json"), "w", encoding="utf-8") as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)
        f.write("\n")

print(f"Wrote {len(LESSONS)} lesson files to {OUT_DIR}/")
