# -*- coding: utf-8 -*-
import json

TOPICS = [
  {"title": "This is + noun", "titleAr": "This is + اسم",
   "explanation": "We use \"This is\" to introduce or point to one person or thing that is close to us.",
   "explanationAr": "نستخدم \"This is\" لتقديم أو الإشارة إلى شخص أو شيء واحد قريب منا.",
   "examples": [{"en": "This is a boy.", "ar": "هذا ولد."}, {"en": "This is my friend.", "ar": "هذا صديقي."},
                {"en": "This is my mom.", "ar": "هذه أمي."}, {"en": "This is a teacher.", "ar": "هذه معلمة."}]},
  {"title": "I am... / You are...", "titleAr": "I am... / You are...",
   "explanation": "We use \"I am\" to talk about ourselves, and \"You are\" to talk to someone else, followed by a feeling or description.",
   "explanationAr": "نستخدم \"I am\" للحديث عن أنفسنا، و\"You are\" للحديث عن شخص آخر، متبوعة بشعور أو وصف.",
   "examples": [{"en": "I am happy.", "ar": "أنا سعيد."}, {"en": "You are tired.", "ar": "أنت متعب."},
                {"en": "I am fine.", "ar": "أنا بخير."}, {"en": "You are great!", "ar": "أنت رائع!"}]},
  {"title": "It is a + noun", "titleAr": "It is a + اسم",
   "explanation": "We use \"It is a\" to say what an object or animal is.",
   "explanationAr": "نستخدم \"It is a\" لقول ما هو الشيء أو الحيوان.",
   "examples": [{"en": "It is a cat.", "ar": "إنه قط."}, {"en": "It is a car.", "ar": "إنها سيارة."},
                {"en": "It is a ball.", "ar": "إنها كرة."}, {"en": "It is a bird.", "ar": "إنه طائر."}]},
  {"title": "big / small with It is...", "titleAr": "big / small مع It is...",
   "explanation": "We add \"big\" or \"small\" before the noun, or after \"It is\", to describe size.",
   "explanationAr": "نضيف \"big\" أو \"small\" قبل الاسم، أو بعد \"It is\"، لوصف الحجم.",
   "examples": [{"en": "It is big.", "ar": "إنه كبير."}, {"en": "It is small.", "ar": "إنه صغير."},
                {"en": "The elephant is big.", "ar": "الفيل كبير."}, {"en": "The mouse is small.", "ar": "الفأر صغير."}]},
  {"title": "Numbers 11-20", "titleAr": "الأرقام 11-20",
   "explanation": "Numbers from eleven to twenty each have their own special word (not built from smaller numbers the same way as later numbers).",
   "explanationAr": "الأرقام من أحد عشر إلى عشرين لكل منها كلمة خاصة بها.",
   "examples": [{"en": "I have eleven stickers.", "ar": "لدي أحد عشر ملصقا."}, {"en": "She is twelve years old.", "ar": "هي في الثانية عشرة من عمرها."},
                {"en": "Count to twenty!", "ar": "عد إلى عشرين!"}, {"en": "There are fifteen chairs.", "ar": "هناك خمسة عشر كرسيا."}]},
  {"title": "What color is it? — It is...", "titleAr": "ما لونه؟ — إنه...",
   "explanation": "We ask \"What color is it?\" to find out a color, and answer with \"It is\" + the color.",
   "explanationAr": "نسأل \"What color is it?\" لمعرفة اللون، ونجيب بـ \"It is\" + اللون.",
   "examples": [{"en": "What color is it?", "ar": "ما لونه؟"}, {"en": "It is red.", "ar": "إنه أحمر."},
                {"en": "It is blue.", "ar": "إنه أزرق."}, {"en": "The ball is green.", "ar": "الكرة خضراء."}]},
  {"title": "I like...", "titleAr": "I like... (أحب)",
   "explanation": "We use \"I like\" + a noun to say we enjoy something.",
   "explanationAr": "نستخدم \"I like\" + اسم لقول أننا نستمتع بشيء ما.",
   "examples": [{"en": "I like apples.", "ar": "أحب التفاح."}, {"en": "I like juice.", "ar": "أحب العصير."},
                {"en": "I like pizza.", "ar": "أحب البيتزا."}, {"en": "Do you like cake?", "ar": "هل تحب الكعك؟"}]},
  {"title": "I don't like...", "titleAr": "I don't like... (لا أحب)",
   "explanation": "We use \"I don't like\" + a noun to say we do not enjoy something.",
   "explanationAr": "نستخدم \"I don't like\" + اسم لقول أننا لا نستمتع بشيء ما.",
   "examples": [{"en": "I don't like onions.", "ar": "لا أحب البصل."}, {"en": "I don't like fish.", "ar": "لا أحب السمك."},
                {"en": "She doesn't like lemons.", "ar": "هي لا تحب الليمون."}, {"en": "Do you like beans? No, I don't.", "ar": "هل تحب الفاصولياء؟ لا، لا أحب."}]},
  {"title": "This is my...", "titleAr": "This is my... (هذا ملكي)",
   "explanation": "We use \"This is my\" + a noun to show something belongs to us.",
   "explanationAr": "نستخدم \"This is my\" + اسم لإظهار أن شيئا ما ملك لنا.",
   "examples": [{"en": "This is my house.", "ar": "هذا منزلي."}, {"en": "This is my bedroom.", "ar": "هذه غرفة نومي."},
                {"en": "This is my kitchen.", "ar": "هذا مطبخي."}, {"en": "This is my door.", "ar": "هذا بابي."}]},
  {"title": "It is a... (kitchen objects)", "titleAr": "It is a... (أدوات المطبخ)",
   "explanation": "We keep using \"It is a\" + noun to name objects, this time things we find in the kitchen.",
   "explanationAr": "نستمر باستخدام \"It is a\" + اسم لتسمية الأشياء، هذه المرة أشياء نجدها في المطبخ.",
   "examples": [{"en": "It is a plate.", "ar": "إنه طبق."}, {"en": "It is a cup.", "ar": "إنه كوب."},
                {"en": "It is a spoon.", "ar": "إنها ملعقة."}, {"en": "It is a fridge.", "ar": "إنها ثلاجة."}]},
  {"title": "I am wearing... / It is a...", "titleAr": "I am wearing... / It is a...",
   "explanation": "We use \"I am wearing\" + a noun to say what clothes we have on.",
   "explanationAr": "نستخدم \"I am wearing\" + اسم لقول ما نرتديه من ملابس.",
   "examples": [{"en": "I am wearing a shirt.", "ar": "أرتدي قميصا."}, {"en": "I am wearing shoes.", "ar": "أرتدي حذاء."},
                {"en": "It is a hat.", "ar": "إنها قبعة."}, {"en": "I am wearing a jacket.", "ar": "أرتدي سترة."}]},
  {"title": "How is the weather? — It is...", "titleAr": "كيف هو الطقس؟ — إنه...",
   "explanation": "We ask \"How is the weather?\" and answer with \"It is\" + a weather word.",
   "explanationAr": "نسأل \"How is the weather?\" ونجيب بـ \"It is\" + كلمة تصف الطقس.",
   "examples": [{"en": "How is the weather?", "ar": "كيف هو الطقس؟"}, {"en": "It is sunny.", "ar": "إنه مشمس."},
                {"en": "It is rainy.", "ar": "إنه ممطر."}, {"en": "It is windy today.", "ar": "إنه عاصف اليوم."}]},
  {"title": "Today is...", "titleAr": "Today is... (اليوم هو)",
   "explanation": "We use \"Today is\" + the day's name to say what day it is.",
   "explanationAr": "نستخدم \"Today is\" + اسم اليوم لقول أي يوم هو.",
   "examples": [{"en": "Today is Monday.", "ar": "اليوم الاثنين."}, {"en": "Today is Friday!", "ar": "اليوم الجمعة!"},
                {"en": "Tomorrow is Saturday.", "ar": "غدا السبت."}, {"en": "What day is it today?", "ar": "أي يوم اليوم؟"}]},
  {"title": "I can... / Can you...?", "titleAr": "I can... / Can you...?",
   "explanation": "We use \"I can\" + a base verb to say what we're able to do, and \"Can you...?\" to ask someone else.",
   "explanationAr": "نستخدم \"I can\" + فعل أساسي لقول ما نستطيع فعله، و\"Can you...?\" لسؤال شخص آخر.",
   "examples": [{"en": "I can run.", "ar": "أستطيع الجري."}, {"en": "I can swim.", "ar": "أستطيع السباحة."},
                {"en": "Can you dance?", "ar": "هل تستطيع الرقص؟"}, {"en": "I can sing and draw.", "ar": "أستطيع الغناء والرسم."}]},
  {"title": "Where is it? — It is in/on/under...", "titleAr": "أين هو؟ — إنه في/على/تحت...",
   "explanation": "We ask \"Where is it?\" and answer with \"It is\" + in/on/under + a place, to describe location.",
   "explanationAr": "نسأل \"Where is it?\" ونجيب بـ \"It is\" + في/على/تحت + مكان، لوصف الموقع.",
   "examples": [{"en": "Where is it?", "ar": "أين هو؟"}, {"en": "It is in the box.", "ar": "إنه في الصندوق."},
                {"en": "It is on the table.", "ar": "إنه على الطاولة."}, {"en": "It is under the chair.", "ar": "إنه تحت الكرسي."}]},
  {"title": "I have...", "titleAr": "I have... (لدي)",
   "explanation": "We use \"I have\" + a noun to say we own or possess something, like a pet.",
   "explanationAr": "نستخدم \"I have\" + اسم لقول أننا نملك شيئا ما، مثل حيوان أليف.",
   "examples": [{"en": "I have a dog.", "ar": "لدي كلب."}, {"en": "I have a cat.", "ar": "لدي قطة."},
                {"en": "I have a pet turtle.", "ar": "لدي سلحفاة أليفة."}, {"en": "Do you have a rabbit?", "ar": "هل لديك أرنب؟"}]},
  {"title": "I play... / I go to...", "titleAr": "I play... / I go to...",
   "explanation": "We use \"I play\" for activities/toys, and \"I go to\" + a place to say where we go.",
   "explanationAr": "نستخدم \"I play\" للأنشطة/الألعاب، و\"I go to\" + مكان لقول إلى أين نذهب.",
   "examples": [{"en": "I play on the swing.", "ar": "ألعب على الأرجوحة."}, {"en": "I go to the park.", "ar": "أذهب إلى الحديقة."},
                {"en": "I play with a kite.", "ar": "ألعب بطائرة ورقية."}, {"en": "We go to the slide.", "ar": "نذهب إلى الزحليقة."}]},
  {"title": "It is a...", "titleAr": "It is a... (شكل)",
   "explanation": "We continue using \"It is a\" + noun, now naming shapes.",
   "explanationAr": "نستمر باستخدام \"It is a\" + اسم، هذه المرة لتسمية الأشكال.",
   "examples": [{"en": "It is a circle.", "ar": "إنها دائرة."}, {"en": "It is a square.", "ar": "إنه مربع."},
                {"en": "It is a star.", "ar": "إنها نجمة."}, {"en": "It is a heart.", "ar": "إنه قلب."}]},
  {"title": "Adjective opposites", "titleAr": "الصفات المتضادة",
   "explanation": "Opposite adjectives describe two different ends of the same idea, like hot/cold or fast/slow.",
   "explanationAr": "الصفات المتضادة تصف طرفين مختلفين لنفس الفكرة، مثل ساخن/بارد أو سريع/بطيء.",
   "examples": [{"en": "The soup is hot.", "ar": "الحساء ساخن."}, {"en": "The ice cream is cold.", "ar": "الآيس كريم بارد."},
                {"en": "The car is fast.", "ar": "السيارة سريعة."}, {"en": "The turtle is slow.", "ar": "السلحفاة بطيئة."}]},
  {"title": "Review of all structures from Lessons 1-19", "titleAr": "مراجعة كل تراكيب الدروس 1-19",
   "explanation": "This lesson mixes every sentence pattern learned so far: This is, I am, It is, I like, I can, and more.",
   "explanationAr": "يجمع هذا الدرس كل أنماط الجمل التي تعلمناها حتى الآن: This is، I am، It is، I like، I can، وغيرها.",
   "examples": [{"en": "This is my friend.", "ar": "هذا صديقي."}, {"en": "I am happy.", "ar": "أنا سعيد."},
                {"en": "I like apples.", "ar": "أحب التفاح."}, {"en": "I can run in a circle!", "ar": "أستطيع الجري في دائرة!"}]},
]

data = {"level": "level1", "levelName": "Level 1 \u00b7 First Sentences", "topics": TOPICS}
with open("grammar-hub/level1.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("Wrote grammar-hub/level1.json with", len(TOPICS), "topics")
