# Second dialogue per Level 5 lesson: named core characters, six lines,
# past-tense storytelling register. (speaker, en, ar)
CREW_TALK = {
 1:[("Sara","What did you do this weekend?","ماذا فعلت في عطلة نهاية الأسبوع؟"),("Omar","I played football, then I helped my dad and cleaned the car.","لعبت كرة القدم، ثم ساعدت أبي ونظفت السيارة."),("Sara","That's a chore, not a weekend.","هذا عمل منزلي وليس عطلة."),("Omar","After that I cooked dinner and watched two movies.","بعد ذلك طبخت العشاء وشاهدت فيلمين."),("Sara","You cooked? What did you make?","طبخت؟ ماذا صنعت؟"),("Omar","Eggs. Twice. Both times it was an adventure.","بيض. مرتين. في المرتين كانت مغامرة.")],
 2:[("Ziad","Yesterday I went to the mall and saw the new phone.","أمس ذهبت إلى المول ورأيت الهاتف الجديد."),("Noor","Did you get it?","هل حصلت عليه؟"),("Ziad","No. I had twenty in my pocket and ate a burger instead.","لا. كان معي عشرون في جيبي وأكلت برجر بدلاً منه."),("Noor","So you took a photo of the phone and went home.","إذاً أخذت صورة للهاتف وعدت للمنزل."),("Ziad","Exactly. Best adventure ever.","بالضبط. أفضل مغامرة على الإطلاق."),("Noor","Your adventures have very small budgets.","مغامراتك ميزانياتها صغيرة جداً.")],
 3:[("Hamad","Did you finish the homework? Did you check the reminder?","هل أنهيت الواجب؟ هل تفقدت التذكير؟"),("Sara","I finished it. Did you call Ziad about the trip?","أنهيته. هل اتصلت بزياد بشأن الرحلة؟"),("Hamad","I called. He didn't answer. Did he forget?","اتصلت. لم يجب. هل نسي؟"),("Sara","He missed the message. He was asleep at noon.","فاتته الرسالة. كان نائماً في الظهيرة."),("Hamad","Did you answer his last text at least?","هل أجبت على آخر رسالة له على الأقل؟"),("Sara","Yes. With one word: 'wake up'.","نعم. بكلمة واحدة: 'استيقظ'.")],
 4:[("Omar","How was the concert? Crowded?","كيف كانت الحفلة؟ مزدحمة؟"),("Noor","Very crowded and very loud. But amazing.","مزدحمة جداً وصاخبة جداً. لكنها كانت مذهلة."),("Omar","Was it difficult to see the stage?","هل كان من الصعب رؤية المسرح؟"),("Noor","A little. Then it got quiet for one song and everyone was excited.","قليلاً. ثم ساد الهدوء لأغنية واحدة وكان الجميع متحمسين."),("Omar","Sounds better than my evening. My evening was boring.","يبدو أفضل من أمسيتي. أمسيتي كانت مملة."),("Noor","Next time, come. Boring is a choice.","المرة القادمة، تعال. الملل خيار.")],
 5:[("Ziad","Back then, the line at the fair was insane.","في ذلك الوقت، الطابور في المهرجان كان جنونياً."),("Hamad","I remember. Then the traffic after, a whole hour.","أتذكر. ثم الزحام بعدها، ساعة كاملة."),("Ziad","But you won a prize at the ring game.","لكنك فزت بجائزة في لعبة الحلقات."),("Hamad","A tiny plastic dinosaur. Total surprise.","ديناصور بلاستيكي صغير. مفاجأة كاملة."),("Ziad","The only problem was the crowd near the food.","المشكلة الوحيدة كانت الزحام قرب الطعام."),("Hamad","And we solved it. We waited until everyone left.","وحللناها. انتظرنا حتى غادر الجميع.")],
 6:[("Sara","When did you last see your cousins?","متى رأيت أبناء عمك آخر مرة؟"),("Omar","Last summer. Before that, a while ago.","الصيف الماضي. وقبل ذلك، منذ فترة."),("Sara","I saw mine two days ago. They came last night for dinner too.","رأيت أبناء عمي منذ يومين. جاؤوا ليلة أمس للعشاء أيضاً."),("Omar","Last week you said you never see them!","الأسبوع الماضي قلت إنك لا ترينهم أبداً!"),("Sara","Yesterday that was true. Time travel changes everything.","أمس كان ذلك صحيحاً. السفر عبر الزمن يغير كل شيء."),("Omar","That's not how time works.","ليس هكذا يعمل الزمن.")],
 7:[("Noor","Tell me the story. First, what happened?","احكِ لي القصة. أولاً، ماذا حدث؟"),("Hamad","First, I lost my bus card. Then I ran to the next stop.","أولاً، فقدت بطاقة الحافلة. ثم ركضت إلى المحطة التالية."),("Noor","Next?","ثم؟"),("Hamad","Next, I found the card in my other pocket. After that, the bus left.","ثم وجدت البطاقة في جيبي الآخر. بعد ذلك، غادرت الحافلة."),("Noor","And finally?","وأخيراً؟"),("Hamad","Finally, I walked. In the end, I arrived before the bus.","أخيراً، مشيت. في النهاية، وصلت قبل الحافلة.")],
 8:[("Ziad","Why were you late? Explain.","لماذا تأخرت؟ اشرح."),("Omar","Because my alarm didn't ring, so I overslept.","لأن منبهي لم يرن، فنمت أكثر."),("Ziad","That's an excuse, not a reason.","هذا عذر وليس سبباً."),("Omar","Since when is the truth an excuse?","منذ متى الحقيقة عذر؟"),("Ziad","Since you used it three times this month.","منذ أن استخدمتها ثلاث مرات هذا الشهر."),("Omar","So I need a new alarm. That's the real reason.","إذاً أحتاج منبهاً جديداً. هذا هو السبب الحقيقي.")],
 9:[("Sara","How did you feel after the results?","كيف شعرت بعد النتائج؟"),("Noor","Nervous before, relieved after, and honestly a bit proud.","متوترة قبلها، مرتاحة بعدها، وبصراحة فخورة قليلاً."),("Sara","I was disappointed with mine. Then surprised: it was a mistake!","كنت محبطة من نتيجتي. ثم تفاجأت: كان خطأ!"),("Noor","So you passed?","إذاً نجحت؟"),("Sara","Yes. I'm grateful the teacher checked again.","نعم. ممتنة أن المعلم تحقق مرة أخرى."),("Noor","Grateful and proud. That's a good day.","ممتنة وفخورة. هذا يوم جيد.")],
 10:[("Hamad","What were you doing when the storm hit?","ماذا كنت تفعل عندما ضربت العاصفة؟"),("Ziad","I was studying. Well, I was sleeping on my book.","كنت أدرس. حسناً، كنت نائماً على كتابي."),("Hamad","We were waiting at the bus stop. It was raining sideways.","كنا ننتظر في محطة الحافلة. كان المطر ينهمر بشكل جانبي."),("Ziad","Were you talking to anyone?","هل كنت تتحدث مع أحد؟"),("Hamad","Everyone. We were all shouting over the wind.","الجميع. كنا جميعاً نصرخ فوق صوت الرياح."),("Ziad","And my mom was cooking like nothing happened.","وأمي كانت تطبخ وكأن شيئاً لم يحدث.")],
 11:[("Omar","How did the exam go? Tell me the study story.","كيف سار الامتحان؟ احكِ لي قصة الدراسة."),("Sara","I reviewed for a week, memorized the dates, and practised past papers.","راجعت لمدة أسبوع، حفظت التواريخ، وتدربت على أوراق سابقة."),("Omar","And the grade?","والدرجة؟"),("Sara","I passed! I struggled with one question, but I improved a lot.","نجحت! واجهت صعوبة في سؤال واحد، لكنني تحسنت كثيراً."),("Omar","That's the story I like. Struggle, then improve.","هذه القصة التي أحبها. صعوبة، ثم تحسن."),("Sara","Next time, you review with me.","المرة القادمة، تراجع معي.")],
 12:[("Noor","We packed on Monday and flew on Tuesday.","حزمنا الأمتعة يوم الاثنين وسافرنا بالطائرة يوم الثلاثاء."),("Hamad","Where did you stay?","أين أقمتم؟"),("Noor","With my aunt. We explored the old town every day.","عند خالتي. استكشفنا المدينة القديمة كل يوم."),("Hamad","When did you return?","متى عدتم؟"),("Noor","Sunday. My suitcase was twice as heavy.","الأحد. حقيبتي كانت أثقل بمرتين."),("Hamad","Gifts?","هدايا؟"),],
 13:[("Ziad","Everything went wrong today.","كل شيء سار خطأ اليوم."),("Sara","What happened first?","ماذا حدث أولاً؟"),("Ziad","I spilled juice on my homework, then I lost my keys.","سكبت العصير على واجبي، ثم فقدت مفاتيحي."),("Sara","And then?","وبعدها؟"),("Ziad","I was late because of traffic, and I broke my headphones.","تأخرت بسبب الزحام، وكسرت سماعاتي."),("Sara","At least you fixed one thing: your excuse is perfect.","على الأقل أصلحت شيئاً واحداً: عذرك مثالي.")],
 14:[("Omar","The party had fifty guests and one small cake.","الحفلة كان فيها خمسون ضيفاً وكعكة واحدة صغيرة."),("Noor","Who brought the music?","من أحضر الموسيقى؟"),("Omar","Ziad. And the games. And most of the gifts were his idea.","زياد. والألعاب. ومعظم الهدايا كانت فكرته."),("Noor","The decorations were beautiful though.","لكن الزينة كانت جميلة."),("Omar","Sara made them the night before.","سارة صنعتها الليلة السابقة."),("Noor","So everyone contributed except the cake.","إذاً الجميع ساهم ما عدا الكعكة.")],
 15:[("Hamad","I woke up at six, got ready fast, and left early.","استيقظت السادسة، تجهزت بسرعة، وغادرت مبكراً."),("Ziad","Why? What did you celebrate?","لماذا؟ ماذا احتفلت؟"),("Hamad","My grandfather's ninetieth birthday. It was unforgettable.","عيد ميلاد جدي التسعين. كان لا يُنسى."),("Ziad","That's a memory to keep.","هذه ذكرى تستحق الاحتفاظ بها."),("Hamad","He remembered every grandchild's name. All twenty of us.","تذكر اسم كل حفيد. كلنا العشرين."),("Ziad","That's the best celebration story I've heard.","هذه أفضل قصة احتفال سمعتها.")],
 16:[("Sara","What were you doing while it was raining?","ماذا كنت تفعلين بينما كانت تمطر؟"),("Noor","I was listening to music and texting you.","كنت أستمع للموسيقى وأراسلك."),("Sara","I was laughing at your messages while my brothers were watching TV.","كنت أضحك على رسائلك بينما كان إخوتي يشاهدون التلفاز."),("Noor","And Omar was thinking about football the whole time.","وعمر كان يفكر في كرة القدم طوال الوقت."),("Sara","While we were playing cards, he was drawing a stadium.","بينما كنا نلعب الورق، كان يرسم ملعباً."),("Noor","That's the thought that never stops.","هذه الفكرة التي لا تتوقف أبداً.")],
 17:[("Ziad","Interview time. What's your favourite memory?","وقت المقابلة. ما ذكراك المفضلة؟"),("Hamad","The adventure last summer: the mountain hike.","مغامرة الصيف الماضي: رحلة الجبل."),("Ziad","Biggest achievement?","أكبر إنجاز؟"),("Hamad","I reached the top. The biggest challenge was my legs.","وصلت إلى القمة. أكبر تحدٍ كان ساقيّ."),("Ziad","Tell me the story in one sentence.","احكِ لي القصة في جملة واحدة."),("Hamad","An experience I complained about for ten hours and loved forever.","تجربة تذمرت منها عشر ساعات وأحببتها للأبد.")],
 18:[("Noor","Movie night recap: who chose the movie?","ملخص ليلة الفيلم: من اختار الفيلم؟"),("Omar","Sara. We laughed for two hours.","سارة. ضحكنا لمدة ساعتين."),("Noor","Was Ziad texting the whole time?","هل كان زياد يراسل طوال الوقت؟"),("Omar","He was texting, then he fell asleep with the popcorn.","كان يراسل، ثم نام والفشار في يده."),("Noor","Did you share the leftovers?","هل تقاسمتم البقايا؟"),("Omar","We ate them. I recommend the movie, not the popcorn.","أكلناها. أنصح بالفيلم وليس الفشار.")],
 19:[("Sara","I lost my backpack yesterday. I searched everywhere.","فقدت حقيبتي أمس. بحثت في كل مكان."),("Ziad","Were you worried?","هل كنت قلقة؟"),("Sara","Very. My notes were inside. Then Hamad found it in the gym.","جداً. ملاحظاتي كانت بداخلها. ثم وجدها حمد في الصالة الرياضية."),("Ziad","Relieved?","مرتاحة؟"),("Sara","So relieved. Now I'm careful. I check twice before I leave.","مرتاحة جداً. الآن أنا حذرة. أتحقق مرتين قبل أن أغادر."),("Ziad","Lesson learned the expensive way.","درس مستفاد بالطريقة المكلفة.")],
 20:[("Hamad","My story project: I cooked, I played, I went everywhere.","مشروع قصتي: طبخت، لعبت، ذهبت إلى كل مكان."),("Noor","Did you finish it? Did you check the spelling?","هل أنهيته؟ هل تحققت من الإملاء؟"),("Hamad","I took my time. It's amazing, honestly.","أخذت وقتي. إنه مذهل، بصراحة."),("Noor","Excited to present it?","متحمس لعرضه؟"),("Hamad","Very. I even practised the ending.","جداً. حتى إنني تدربت على النهاية."),("Noor","Then it's not a story anymore. It's a show.","إذاً لم تعد قصة. إنه عرض.")],
}


# Second Crew Talk per lesson (A2 richness campaign): a shorter, later
# conversation (4 lines / 2 exchanges) using more of the lesson's own
# vocabulary in a fresh situation. Skipped for Lesson 20.
CREW_TALK_2 = {
 1:[("Noor","Did you rest at all this weekend, or just chores?","هل ارتحت أصلاً في العطلة، أم واجبات فقط؟"),("Sara","I visited my aunt and baked cookies with her. That counts as rest.","زرت عمتي وخبزت معها كعكاً. هذا يُحسب راحة."),("Noor","Baking sounds fun. I just cleaned my room.","الخبز يبدو ممتعاً. أنا فقط نظفت غرفتي."),("Sara","Next weekend, come bake with us instead of cleaning.","الأسبوع القادم، تعالي اخبزي معنا بدلاً من التنظيف.")],
 2:[("Hamad","So what did you buy at the mall in the end?","إذاً ماذا اشتريت في المول أخيراً؟"),("Omar","Nothing. I met an old friend and we just talked.","لا شيء. قابلت صديقاً قديماً وتحدثنا فقط."),("Hamad","You went to buy something and found a friend instead.","ذهبت لتشتري شيئاً ووجدت صديقاً بدلاً منه."),("Omar","Best adventure. I still got the burger though.","أفضل مغامرة. لكنني حصلت على البرجر رغم ذلك.")],
 3:[("Sara","Did you attend the meeting? I couldn't deliver my part.","هل حضرت الاجتماع؟ لم أستطع تسليم جزئي."),("Ziad","I attended, but I forgot to check my messages first.","حضرت، لكنني نسيت أن أتفقد رسائلي أولاً."),("Sara","Did anyone reply to the reminder at least?","هل رد أحد على التذكير على الأقل؟"),("Ziad","Two people. I'll deliver the notes to you after class.","شخصان. سأوصل لك الملاحظات بعد الحصة.")],
 4:[("Omar","How was the concert? Crowded and noisy?","كيف كان الحفل؟ مزدحماً وصاخباً؟"),("Noor","Crowded, yes, but not noisy. Actually quite peaceful.","مزدحماً، نعم، لكن غير صاخب. كان هادئاً فعلاً."),("Omar","Peaceful and amazing at the same time? Unusual.","هادئ ومذهل في نفس الوقت؟ غير معتاد."),("Noor","It was difficult to leave, if that tells you anything.","كان من الصعب المغادرة، إن كان هذا يخبرك بشيء.")],
 5:[("Hamad","Was there a long queue for the tickets?","هل كان هناك طابور طويل للتذاكر؟"),("Ziad","A queue and traffic both. We almost missed it.","طابور وزحمة معاً. كدنا نفوّته."),("Hamad","Any surprise at least, after all that?","أي مفاجأة على الأقل، بعد كل ذلك؟"),("Ziad","One problem solved itself: they gave us a prize for waiting.","مشكلة واحدة حُلّت نفسها: أعطونا جائزة على الانتظار.")],
 6:[("Sara","What did you do a while ago that you still remember?","ماذا فعلت منذ فترة ولا تزال تتذكره؟"),("Omar","Last summer, recently actually, I learned to swim.","الصيف الماضي، مؤخراً في الواقع، تعلمت السباحة."),("Sara","That wasn't ago, that was earlier this year!","هذا لم يكن منذ فترة، كان أبكر هذا العام!"),("Omar","Time flies. Feels like ages ago to me.","الوقت يمر بسرعة. يبدو لي وكأنه منذ زمن بعيد.")],
 7:[("Ziad","Tell the story in order: first, then, finally.","احكِ القصة بالترتيب: أولاً، ثم، وأخيراً."),("Hamad","First we got lost, then it started raining, meanwhile Ziad laughed.","أولاً تهنا، ثم بدأ المطر، وفي الأثناء ضحك زياد."),("Ziad","Suddenly a bus appeared, and in the end we got home.","فجأة ظهرت حافلة، وفي النهاية وصلنا للمنزل."),("Hamad","At last! I thought we'd tell that story forever.","أخيراً! ظننت أننا سنحكي تلك القصة للأبد.")],
 8:[("Noor","What was the reason you were late, really?","ما السبب الحقيقي لتأخرك؟"),("Sara","No excuse this time. The result was I missed the bus.","لا عذر هذه المرة. النتيجة أنني فاتني الباص."),("Noor","So explain the cause, since there's a reason for everything.","إذاً اشرحي السبب، فلكل شيء سبب."),("Sara","I overslept, therefore everything else happened.","نمت كثيراً، ولذلك حدث كل شيء آخر.")],
 9:[("Omar","How did you feel when you got the results?","كيف شعرت عندما حصلت على النتائج؟"),("Ziad","Nervous first, then thrilled, then a little embarrassed I doubted myself.","متوتراً أولاً، ثم متحمساً، ثم محرجاً قليلاً لأنني شككت بنفسي."),("Omar","Relieved and grateful too, I bet.","مرتاح وممتن أيضاً، أراهن."),("Ziad","Very. Surprised is the right word, honestly.","جداً. متفاجئ هي الكلمة الصحيحة، بصراحة.")],
 10:[("Sara","What was happening when the storm started?","ماذا كان يحدث عندما بدأت العاصفة؟"),("Hamad","We were waiting at the bus stop. Thunder everywhere.","كنا ننتظر عند موقف الباص. رعد في كل مكان."),("Sara","Was everyone talking, or was it quiet?","هل كان الجميع يتحدث، أم كان هادئاً؟"),("Hamad","Everyone was talking about the umbrella nobody brought.","الجميع كان يتحدث عن المظلة التي لم يحضرها أحد.")],
 11:[("Noor","How did the exam go? Did all that revision help?","كيف سار الامتحان؟ هل ساعدت كل تلك المراجعة؟"),("Omar","I memorized everything, practiced twice, and still struggled a bit.","حفظت كل شيء، تمرنت مرتين، ولا زلت واجهت صعوبة قليلاً."),("Noor","But you passed, and your score improved from last time.","لكنك نجحت، ودرجتك تحسنت عن المرة السابقة."),("Omar","True. The effort was worth the grade.","صحيح. الجهد كان يستحق الدرجة.")],
 12:[("Ziad","Did you keep the boarding pass from the trip?","هل احتفظت ببطاقة الصعود من الرحلة؟"),("Sara","I packed it in my suitcase by mistake. Along with a landmark postcard.","وضعتها في حقيبتي بالخطأ. مع بطاقة بريدية لمعلم سياحي."),("Ziad","Did you stay at the same hotel as last time?","هل أقمت في نفس الفندق كالمرة الماضية؟"),("Sara","No, we flew somewhere new and explored a different city.","لا، طرنا لمكان جديد واستكشفنا مدينة مختلفة.")],
 13:[("Hamad","What went wrong at the party, exactly?","ماذا حدث بالضبط في الحفلة؟"),("Omar","I dropped the cake, then spilled juice, then apologized ten times.","أوقعت الكعكة، ثم سكبت العصير، ثم اعتذرت عشر مرات."),("Hamad","No traffic excuse this time, then. Just a mistake.","لا عذر الزحمة هذه المرة إذاً. مجرد خطأ."),("Omar","I fixed the cake with extra cream. Nobody noticed.","أصلحت الكعكة بكريمة إضافية. لم يلاحظ أحد.")],
 14:[("Sara","Were there balloons and decorations at the party?","هل كان هناك بالونات وزينة في الحفلة؟"),("Noor","Balloons, gifts, and a playlist that never stopped.","بالونات، هدايا، وقائمة أغاني لم تتوقف."),("Sara","Did everyone bring the invitation like I asked?","هل أحضر الجميع الدعوة كما طلبت؟"),("Noor","Every single guest. Even the music arrived on time.","كل ضيف. حتى الموسيقى وصلت في الوقت المحدد.")],
 15:[("Omar","What's your most unforgettable memory from this year?","ما ذكراك الأكثر تميزاً هذا العام؟"),("Ziad","My grandmother's anniversary celebration. We made a whole photo album.","احتفال ذكرى جدتي. صنعنا ألبوم صور كاملاً."),("Omar","That sounds like a real tradition in your family.","هذا يبدو تقليداً حقيقياً في عائلتكم."),("Ziad","It is. We remembered every detail together.","إنه كذلك. تذكرنا كل التفاصيل معاً.")],
 16:[("Noor","What were you doing when I called you last night?","ماذا كنت تفعل عندما اتصلت بك ليلة أمس؟"),("Hamad","Honestly? Daydreaming. Then whispering to myself like a plan.","بصراحة؟ أشرد بأحلام اليقظة. ثم أهمس لنفسي وكأنها خطة."),("Noor","Were you giggling at your phone the whole time too?","هل كنت تضحك خفية على هاتفك طوال الوقت أيضاً؟"),("Hamad","Guilty. I was thinking about something funny.","مذنب. كنت أفكر في شيء مضحك.")],
 17:[("Sara","What's your favorite memory and your biggest achievement?","ما ذكراك المفضلة وأكبر إنجاز لك؟"),("Omar","My favorite memory is a hobby I started as a challenge.","ذكراي المفضلة هي هواية بدأتها كتحدٍ."),("Sara","And the turning point? When did it become an adventure?","والنقطة الفاصلة؟ متى أصبحت مغامرة؟"),("Omar","When I stopped calling it a hobby and started calling it my story.","عندما توقفت عن تسميتها هواية وبدأت أسميها قصتي.")],
 18:[("Ziad","So what movie did you choose in the end?","إذاً أي فيلم اخترتم أخيراً؟"),("Noor","We chose the one with the plot twist in the last scene.","اخترنا الفيلم الذي فيه المفاجأة في المشهد الأخير."),("Ziad","Did you laugh, or was it a serious one?","هل ضحكتم، أم كان جدياً؟"),("Noor","Laughed until the credits, then someone fell asleep. I won't say who.","ضحكنا حتى نهاية الفيلم، ثم نام أحدهم. لن أقول من.")],
 19:[("Hamad","Did you ever find the backpack you lost?","هل وجدت الحقيبة التي فقدتها؟"),("Sara","Someone searched the lost and found and saw the label with my name.","بحث أحدهم في قسم المفقودات ورأى البطاقة التي تحمل اسمي."),("Hamad","Were you still worried, or relieved right away?","هل كنت لا تزالين قلقة، أم ارتحت فوراً؟"),("Sara","Relieved instantly. No more panic after that.","ارتحت فوراً. لا مزيد من الذعر بعد ذلك.")],
}
