# Second dialogue per Level 4 lesson: named core characters, six lines,
# routines / frequency / money / advice register. (speaker, en, ar)
CREW_TALK = {
 1:[("Sara","Does Noor even sleep? She wakes up at five to study.","هل تنام نور أصلاً؟ تستيقظ الخامسة لتدرس."),("Ziad","Then she practices piano, then she hangs out with us.","ثم تتمرن على البيانو، ثم تقضي وقتاً معنا."),("Sara","When does she relax?","متى تسترخي؟"),("Ziad","She takes a nap after school. Ten minutes exactly.","تأخذ قيلولة بعد المدرسة. عشر دقائق بالضبط."),("Sara","That's not a hobby, that's a schedule.","هذه ليست هواية، هذا جدول."),("Ziad","Don't tell her that. She'll chill even less.","لا تقولي لها ذلك. ستسترخي أقل.")],
 2:[("Omar","My mom set a new bedtime and a screen-time limit.","أمي وضعت موعد نوم جديداً وحداً لوقت الشاشة."),("Hamad","Same. My schedule is: homework, workout, sleep.","نفس الشيء. جدولي: واجب، تمرين، نوم."),("Omar","When's your deadline for the science project?","متى موعد تسليم مشروع العلوم؟"),("Hamad","Friday. My rule: finish it before the weekend.","الجمعة. قاعدتي: أنهيه قبل عطلة نهاية الأسبوع."),("Omar","My rule is different. I finish it Sunday night.","قاعدتي مختلفة. أنهيه ليلة الأحد."),("Hamad","That's not a rule, that's panic.","هذه ليست قاعدة، هذا هلع.")],
 3:[("Noor","How often do you actually clean your room?","كم مرة تنظف غرفتك فعلاً؟"),("Ziad","Weekly. Okay, occasionally. Fine, rarely.","أسبوعياً. حسناً، أحياناً. حسناً، نادراً."),("Noor","I do it daily. It takes five minutes.","أفعلها يومياً. تأخذ خمس دقائق."),("Ziad","You constantly say that, but I never see you do it.","تقولين ذلك باستمرار، لكنني لا أراك تفعلين ذلك أبداً."),("Noor","Because you never visit, you're always gaming.","لأنك لا تزور أبداً، أنت دائماً تلعب."),("Ziad","Fair. Rarely visiting is also a habit.","صحيح. الزيارة نادراً عادة أيضاً.")],
 4:[("Hamad","Do you have any plans before the holiday?","هل لديك أي خطط قبل العطلة؟"),("Sara","A dentist appointment, then a deadline, then freedom.","موعد عند طبيب الأسنان، ثم موعد تسليم، ثم الحرية."),("Hamad","After the break, the new semester starts already.","بعد الاستراحة، يبدأ الفصل الجديد مباشرة."),("Sara","Don't say that. I'm still in weekend mode.","لا تقل ذلك. ما زلت في وضع عطلة نهاية الأسبوع."),("Hamad","It's Tuesday.","اليوم الثلاثاء."),("Sara","Exactly. Two days before the weekend.","بالضبط. يومان قبل عطلة نهاية الأسبوع.")],
 5:[("Omar","I texted you three times. Why no reply?","راسلتك ثلاث مرات. لماذا لا رد؟"),("Noor","I was on a video chat with my cousin. What's up?","كنت في مكالمة فيديو مع ابنة عمي. ما الأمر؟"),("Omar","Ziad wants to invite everyone to meet at the park.","زياد يريد دعوة الجميع للقاء في الحديقة."),("Noor","Call him and say yes. I'll add the contact to the group.","اتصل به وقل نعم. سأضيف جهة الاتصال إلى المجموعة."),("Omar","Done. He replied with twelve emojis.","تم. رد باثني عشر إيموجي."),("Noor","That's Ziad for 'great'.","هذا يعني 'رائع' بلغة زياد.")],
 6:[("Ziad","Whose earbuds are these? They're in my jacket.","سماعات من هذه؟ إنها في سترتي."),("Hamad","Those are mine! I left them in your bike basket.","هذه لي! تركتها في سلة دراجتك."),("Ziad","And this notebook? And this wallet?","وهذا الدفتر؟ وهذه المحفظة؟"),("Hamad","The notebook is Sara's. The wallet is yours, look.","الدفتر لسارة. المحفظة لك، انظر."),("Ziad","Oh. That explains the missing sneakers too.","أوه. هذا يفسر الأحذية المفقودة أيضاً."),("Hamad","Your sneakers are on your feet, Ziad.","أحذيتك في قدميك يا زياد.")],
 7:[("Sara","Got any snacks? I'm starving.","هل لديك أي وجبات خفيفة؟ أتضور جوعاً."),("Omar","There are leftovers in the fridge and chips in the pantry.","هناك بقايا في الثلاجة ورقائق في المخزن."),("Sara","Leftovers of what?","بقايا ماذا؟"),("Omar","Pasta. My dad bought the groceries and cooked it.","معكرونة. أبي اشترى البقالة وطبخها."),("Sara","What ingredients? I'm allergic to nothing but curiosity.","أي مكونات؟ لست حساسة من شيء سوى الفضول."),("Omar","Tomato, cheese, and a secret. Eat.","طماطم وجبن وسر. كلي.")],
 8:[("Noor","How much is that hoodie? I don't see a price tag.","كم سعر هذا الهودي؟ لا أرى بطاقة سعر."),("Ziad","Eighty, but there's a discount today. Sixty.","ثمانون، لكن هناك خصم اليوم. ستون."),("Noor","My allowance is fifty. My budget says no.","مصروفي خمسون. ميزانيتي تقول لا."),("Ziad","Use your savings. It's a good deal.","استخدمي مدخراتك. إنها صفقة جيدة."),("Noor","Savings are for emergencies.","المدخرات للطوارئ."),("Ziad","A cold day without a hoodie IS an emergency. Keep the receipt.","يوم بارد بدون هودي هو طارئ. احتفظي بالإيصال.")],
 9:[("Hamad","I'm saving up for a new bike. Forty coins so far.","أدخر لدراجة جديدة. أربعون عملة حتى الآن."),("Sara","In a moneybox? Seriously?","في حصالة؟ حقاً؟"),("Hamad","Yes. I earn ten a week helping my uncle.","نعم. أكسب عشرة أسبوعياً بمساعدة عمي."),("Sara","Don't spend it on snacks. Or lend it to Ziad.","لا تنفقها على الوجبات الخفيفة. أو تقرضها لزياد."),("Hamad","I never lend. I only borrow.","لا أقرض أبداً. أنا فقط أستلف."),("Sara","That's why your wallet is empty.","لهذا محفظتك فارغة.")],
 10:[("Omar","Noor's drawing won. It was outstanding.","رسمة نور فازت. كانت متميزة."),("Ziad","Honestly, all the drawings were impressive.","بصراحة، كل الرسومات كانت مبهرة."),("Omar","Hers was unique though. Nobody drew the city at night.","لكن رسمتها كانت فريدة. لم يرسم أحد المدينة ليلاً."),("Ziad","She's so talented and she never brags.","إنها موهوبة جداً ولا تتفاخر أبداً."),("Omar","That's why she's popular.","لهذا هي محبوبة."),("Ziad","And skilled. Don't forget skilled.","وماهرة. لا تنسَ ماهرة.")],
 11:[("Noor","I'd like the chicken, please. What do you recommend?","أريد الدجاج من فضلك. بماذا تنصح؟"),("Hamad","I suggest the rice with it. It's the best on the menu.","أقترح الأرز معه. إنه الأفضل في القائمة."),("Noor","I prefer salad. Can I request that instead?","أفضّل السلطة. هل يمكنني طلب ذلك بدلاً منه؟"),("Hamad","Of course. Good choice, this restaurant does great salads.","بالطبع. اختيار جيد، هذا المطعم يقدم سلطات رائعة."),("Noor","And you? What's your order?","وأنت؟ ما طلبك؟"),("Hamad","Everything. I'll decide when it arrives.","كل شيء. سأقرر عندما يصل.")],
 12:[("Sara","Can I give you some advice about the exam?","هل يمكنني إعطاؤك نصيحة عن الامتحان؟"),("Ziad","Only if it's a good tip.","فقط إذا كانت نصيحة جيدة."),("Sara","You should try studying in the morning. It's a habit that works.","يجب أن تجرب الدراسة في الصباح. إنها عادة تنجح."),("Ziad","My opinion? Mornings are a warning sign.","رأيي؟ الصباح إشارة تحذير."),("Sara","My suggestion is free, take it or leave it.","اقتراحي مجاني، خذه أو اتركه."),("Ziad","Fine. One morning. Then we'll see.","حسناً. صباح واحد. ثم نرى.")],
 13:[("Omar","Did you see Hamad's post? Two hundred likes.","هل رأيت منشور حمد؟ مئتا إعجاب."),("Noor","I commented and shared it. The hashtag is genius.","علّقت وشاركته. الهاشتاق عبقري."),("Omar","My notifications won't stop. Everyone's online.","إشعاراتي لا تتوقف. الجميع متصل."),("Noor","Check his profile. He changed the picture again.","تفقد ملفه الشخصي. غيّر الصورة مرة أخرى."),("Omar","Third time this week.","ثالث مرة هذا الأسبوع."),("Noor","That's the group chat's favourite topic now.","هذا موضوع الدردشة الجماعية المفضل الآن.")],
 14:[("Hamad","The captain says we need to cooperate more.","القائد يقول إننا نحتاج للتعاون أكثر."),("Ziad","I contribute! I encourage everyone from the bench.","أنا أساهم! أشجع الجميع من مقاعد البدلاء."),("Hamad","Support is good. Playing is better.","الدعم جيد. اللعب أفضل."),("Ziad","Teamwork means everyone has a role. Mine is the loud one.","العمل الجماعي يعني أن للجميع دوراً. دوري هو الصاخب."),("Hamad","The trophy needs goals, not noise.","الكأس تحتاج أهدافاً وليس ضجيجاً."),("Ziad","A true leader accepts both.","القائد الحقيقي يقبل الاثنين.")],
 15:[("Sara","I have to decide: art club or robotics.","يجب أن أقرر: نادي الفن أم الروبوتات."),("Omar","Consider the consequence. Robotics has a Saturday class.","فكري في العاقبة. الروبوتات فيها حصة يوم السبت."),("Sara","Then the option is clear... but art is my favourite.","إذاً الخيار واضح... لكن الفن هو المفضل لدي."),("Omar","Compromise: robotics now, art next semester.","حل وسط: الروبوتات الآن، والفن الفصل القادم."),("Sara","That's a real choice. How are you so calm about this?","هذا خيار حقيقي. كيف أنت هادئ جداً بشأن هذا؟"),("Omar","Because it's your decision, not mine.","لأنه قرارك وليس قراري.")],
 16:[("Noor","I'm so nervous about the speech tomorrow.","أنا متوترة جداً بشأن الخطاب غداً."),("Hamad","You'll be fine. Stay calm and breathe.","ستكونين بخير. ابقي هادئة وتنفسي."),("Noor","Easy for you, you're always confident.","سهل عليك، أنت دائماً واثق."),("Hamad","I was anxious last week. Then I practised ten times.","كنت قلقاً الأسبوع الماضي. ثم تمرنت عشر مرات."),("Noor","And after?","وبعدها؟"),("Hamad","Relieved. And a little proud. You will be too.","مرتاح. وفخور قليلاً. وأنت ستكونين كذلك.")],
 17:[("Ziad","What's your dream job? Be honest.","ما وظيفة أحلامك؟ كن صادقاً."),("Sara","My goal is to be an architect. Buildings are my passion.","هدفي أن أكون مهندسة معمارية. المباني شغفي."),("Ziad","That's a serious ambition. What career for me?","هذا طموح جدي. أي مهنة لي؟"),("Sara","Something with games. You'd achieve a lot.","شيء متعلق بالألعاب. ستحقق الكثير."),("Ziad","Game designer. My future self will thank me.","مصمم ألعاب. نسختي المستقبلية ستشكرني."),("Sara","Only if your present self starts studying.","فقط إذا بدأت نسختك الحالية بالدراسة.")],
 18:[("Omar","I want to explore Japan one day. The culture is fascinating.","أريد استكشاف اليابان يوماً ما. الثقافة رائعة."),("Noor","Every country has a custom that surprises you.","كل بلد فيه عادة تفاجئك."),("Omar","Like what?","مثل ماذا؟"),("Noor","In Japan you take off your shoes inside. That's a tradition.","في اليابان تخلع حذاءك في الداخل. هذه تقليد."),("Omar","We do that too! Same custom, different language.","نحن نفعل ذلك أيضاً! نفس العادة، لغة مختلفة."),("Noor","That's the point of a journey. You find what's shared.","هذا هدف الرحلة. تجد ما هو مشترك.")],
 19:[("Hamad","The group project deadline is Friday and we disagree on everything.","موعد مشروع المجموعة الجمعة ونحن مختلفون على كل شيء."),("Sara","Then we compromise. You do the research, I do the design.","إذاً نتوصل لحل وسط. أنت تبحث، وأنا أصمم."),("Hamad","And Ziad?","وزياد؟"),("Sara","Ziad presents. He loves an audience.","زياد يعرض. يحب الجمهور."),("Hamad","That's real teamwork. I'm almost proud.","هذا عمل جماعي حقيقي. أكاد أكون فخوراً."),("Sara","Be proud on Friday, after we submit.","كن فخوراً يوم الجمعة، بعد أن نسلّم.")],
 20:[("Noor","Future plans project: what's yours?","مشروع الخطط المستقبلية: ما خطتك؟"),("Ziad","Wake up late, chill, and never have a bedtime.","أستيقظ متأخراً، أسترخي، ولا يكون لي موعد نوم أبداً."),("Noor","That's a holiday, not a plan.","هذه عطلة وليست خطة."),("Ziad","Fine: a schedule with an appointment every day.","حسناً: جدول فيه موعد كل يوم."),("Noor","Rarely realistic, but constantly funny.","نادراً ما يكون واقعياً، لكنه مضحك دائماً."),("Ziad","Put that on my profile.","ضعي هذا على ملفي الشخصي.")],
}

# Second Crew Talk per lesson (per Eslam's A2 richness campaign): a
# shorter, later moment (4 lines / 2 exchanges) using more of the
# lesson's own vocabulary in a fresh situation, not just a repeat of
# CREW_TALK's opening scene. Skipped for Lesson 20 (already the
# heaviest review deck in the level).
CREW_TALK_2 = {
 1:[("Noor","Be honest, do you ever actually relax?","بصراحة، هل ترتاحين فعلاً؟"),("Sara","I nap for ten minutes. That's my whole hobby now.","أقيلولة عشر دقائق. هذه كل هوايتي الآن."),("Noor","Ten minutes isn't rest, it's a power nap for robots.","عشر دقائق ليست راحة، إنها قيلولة سريعة للروبوتات."),("Sara","My energy says otherwise. It works.","طاقتي تقول عكس ذلك. إنها تنجح.")],
 2:[("Hamad","Your planner has a limit for everything. Even fun?","مخططك فيه حد لكل شيء. حتى المرح؟"),("Omar","My priority this week is the deadline, not fun.","أولويتي هذا الأسبوع الموعد النهائي، وليس المرح."),("Hamad","One priority every week? That's a strict schedule.","أولوية واحدة كل أسبوع؟ هذا جدول صارم."),("Omar","Strict schedules finish homework. Loose ones finish nothing.","الجداول الصارمة تنهي الواجب. المرنة لا تنهي شيئاً.")],
 3:[("Ziad","So how often is 'sometimes' really? Be exact.","إذاً كم مرة تعني 'أحياناً' فعلاً؟ كن دقيقاً."),("Noor","Twice a month. Rarely is once, if I'm honest.","مرتين شهرياً. ونادراً تعني مرة واحدة، بصراحة."),("Ziad","So your habit is basically never.","إذاً عادتك هي أساساً أبداً."),("Noor","My habit is constantly promising and occasionally doing it.","عادتي هي الوعد باستمرار والتنفيذ أحياناً.")],
 4:[("Sara","Mark the calendar, my appointment moved before the weekend.","علّم في التقويم، موعدي انتقل قبل عطلة نهاية الأسبوع."),("Hamad","Before the holiday too? That's a tight countdown.","قبل العطلة أيضاً؟ هذا عد تنازلي ضيق."),("Sara","I know. My whole semester is squeezed into one calendar page.","أعرف. فصلي الدراسي كله مضغوط في صفحة تقويم واحدة."),("Hamad","Set a reminder before you forget the appointment itself.","اضبط تذكيراً قبل أن تنسى الموعد نفسه.")],
 5:[("Sara","Why didn't you reply? I left a voicemail too.","لماذا لم ترد؟ تركت رسالة صوتية أيضاً."),("Ziad","My phone showed 'typing...' from you, then nothing.","هاتفي أظهر 'يكتب...' منك، ثم لا شيء."),("Sara","Group call tonight, then. Contact everyone.","مكالمة جماعية الليلة إذاً. اتصل بالجميع."),("Ziad","Invite Hamad too. He only replies to emojis anyway.","ادعُ حمد أيضاً. هو أصلاً لا يرد إلا بالإيموجي.")],
 6:[("Sara","Is this keychain yours? It was on my bike.","هل هذه السلسلة لك؟ كانت على دراجتي."),("Omar","Mine! And is that my lunchbox in your bag?","لي! وهل هذا صندوق غدائي في حقيبتك؟"),("Sara","Guilty. Your umbrella is in my locker too.","مذنبة. ومظلتك في خزانتي أيضاً."),("Omar","Between us we could open a lost and found.","بيننا يمكننا افتتاح قسم للمفقودات.")],
 7:[("Hamad","This is crunchy! What's in it?","هذا مقرمش! ما الذي بداخله؟"),("Noor","A recipe from my grandma. And yes, it's spicy.","وصفة من جدتي. ونعم، إنها حارة."),("Hamad","Too spicy for Ziad. He'll ask for the ingredients anyway.","حارة جداً لزياد. سيسأل عن المكونات على أي حال."),("Noor","Let him. There are always more groceries in the pantry.","دعه. هناك دائماً بقالة أكثر في المخزن.")],
 8:[("Ziad","Sale ends today. Sixty percent off with this receipt.","التخفيضات تنتهي اليوم. ستون بالمئة خصم بهذا الإيصال."),("Noor","My savings say yes, my budget says think again.","مدخراتي تقول نعم، ميزانيتي تقول فكري مجدداً."),("Ziad","Pay cash, get the change, and it's still a good sale.","ادفعي كاش، خذي الباقي، وتظل صفقة جيدة."),("Noor","Fine. But the receipt goes straight in my budget folder.","حسناً. لكن الإيصال يذهب مباشرة إلى ملف ميزانيتي.")],
 9:[("Noor","How's the goal jar? Still saving for the bike?","كيف حال وعاء الهدف؟ لا تزال تدخر للدراجة؟"),("Hamad","Yes, but I had to spend some on a birthday gift.","نعم، لكن اضطررت لإنفاق بعضه على هدية عيد ميلاد."),("Noor","At least you didn't borrow from the bank... or from Ziad.","على الأقل لم تقترض من البنك... أو من زياد."),("Hamad","Cheap gift, cheap lesson. I earn it back by Friday.","هدية رخيصة، درس رخيص. سأعوّضه بحلول الجمعة.")],
 10:[("Sara","The whole audience stood up. The applause didn't stop.","الجمهور بأكمله وقف. التصفيق لم يتوقف."),("Omar","Even the judge looked impressed, and she's strict.","حتى الحكمة بدت معجبة، وهي صارمة."),("Sara","It was outstanding. Truly one of a kind.","كانت متميزة. فريدة من نوعها حقاً."),("Omar","Unique doesn't even cover it. She raised the bar for everyone.","فريدة لا تكفي حتى. رفعت السقف للجميع.")],
 11:[("Ziad","What's outstanding on this menu? I can't decide.","ما الطبق المميز في هذه القائمة؟ لا أستطيع أن أقرر."),("Hamad","The waiter said the dessert is the restaurant's specialty.","قال النادل إن الحلوى هي تخصص المطعم."),("Ziad","Then I'd like that, please, and the bill after.","إذاً أريد ذلك من فضلك، والفاتورة بعدها."),("Hamad","Good choice. I'll order the same, honestly.","اختيار جيد. سأطلب نفس الشيء بصراحة.")],
 12:[("Omar","One tip before the test: patience with the hard questions.","نصيحة واحدة قبل الاختبار: الصبر مع الأسئلة الصعبة."),("Sara","That's real advice, not just an opinion.","هذه نصيحة حقيقية، وليست مجرد رأي."),("Omar","My suggestion: skip a mistake, don't stop on it.","اقتراحي: تجاوز الخطأ، لا تتوقف عنده."),("Sara","Fair warning taken. Patience it is.","تحذير عادل، مقبول. سأتحلى بالصبر.")],
 13:[("Hamad","Follow the trend, add a caption, and post it.","تابع الترند، أضف تعليقاً توضيحياً، وانشره."),("Ziad","Every comment and share is a notification for me now.","كل تعليق ومشاركة صار إشعاراً لي الآن."),("Hamad","That's the hashtag working. You're online too much though.","هذا هو الهاشتاق يعمل. لكنك متصل كثيراً جداً."),("Ziad","Patience, one more post and I'm done. Probably.","صبراً، منشور واحد أخير وأنتهي. ربما.")],
 14:[("Noor","Great practice match. You really passed well today.","مباراة تدريبية رائعة. لقد مررت الكرة جيداً اليوم."),("Sara","The whole team cheered when you supported that last play.","الفريق بأكمله هتف عندما دعمت تلك اللعبة الأخيرة."),("Noor","Cooperate now, celebrate later, that's my motto.","تعاونوا الآن، احتفلوا لاحقاً، هذا شعاري."),("Sara","A real leader encourages before the trophy, not after.","القائد الحقيقي يشجع قبل الكأس، لا بعده.")],
 15:[("Hamad","Weighing the pros and cons still, or did you decide?","ما زلت تزن الإيجابيات والسلبيات، أم قررت؟"),("Sara","The risk is real, but so is the regret if I don't try.","الخطر حقيقي، لكن الندم أيضاً حقيقي إن لم أحاول."),("Hamad","Then compromise: try it small first, not the big option.","إذاً حل وسط: جربيها صغيرة أولاً، لا الخيار الكبير."),("Sara","That's actually a smart consequence to plan for.","هذه في الواقع عاقبة ذكية أخطط لها.")],
 16:[("Ziad","On stage in five minutes. Take a deep breath.","على المسرح بعد خمس دقائق. خذ نفساً عميقاً."),("Omar","I was calm until you said 'five minutes'.","كنت هادئاً حتى قلت 'خمس دقائق'."),("Ziad","You'll get applause, not silence. Stay confident.","ستنال تصفيقاً، لا صمتاً. ابقَ واثقاً."),("Omar","Relieved just hearing that. Thanks for not letting me be anxious alone.","مرتاح فقط لسماع ذلك. شكراً لأنك لم تتركني قلقاً وحدي.")],
 17:[("Noor","Still chasing that architect dream, or new ambition?","ما زلت تلاحقين حلم المهندسة المعمارية، أم طموح جديد؟"),("Ziad","Same passion, new goal: university first, career after.","نفس الشغف، هدف جديد: الجامعة أولاً، ثم المهنة."),("Noor","And volunteering? You said you'd achieve that too.","والتطوع؟ قلت إنك ستحقق ذلك أيضاً."),("Ziad","Already started. Small steps, big career later.","بدأت بالفعل. خطوات صغيرة، مهنة كبيرة لاحقاً.")],
 18:[("Sara","Bring me a souvenir from the festival, please!","أحضري لي هدية تذكارية من المهرجان، رجاءً!"),("Hamad","Only if you explore the culture with me first, not just the shops.","فقط إن استكشفت الثقافة معي أولاً، لا المحلات فقط."),("Sara","Deal. Every custom and tradition, I promise.","اتفقنا. كل عادة وتقليد، أعدك."),("Hamad","Even the language? A few words go a long way.","حتى اللغة؟ بضع كلمات تفيد كثيراً.")],
 19:[("Omar","Our research needs more slides before the feedback session.","بحثنا يحتاج شرائح أكثر قبل جلسة الملاحظات."),("Noor","Agreed. Let's compromise on the deadline: two more days.","موافقة. لنتفق على حل وسط للموعد: يومان إضافيان."),("Omar","Good, teamwork beats a rushed project every time.","جيد، العمل الجماعي يتفوق على المشروع المتسرع دائماً."),("Noor","Proud of this one already, honestly.","فخورة بهذا المشروع بالفعل، بصراحة.")],
}
