# Second dialogue per Level 3 lesson: named core characters, natural teen
# register, built around that lesson's key words. (speaker, en, ar)
CREW_TALK = {
 1:[("Ziad","Who's in your crew these days?","من في شلتك هذه الأيام؟"),("Omar","Same people. We mostly chat in the group chat and send memes.","نفس الأشخاص. نتحدث غالباً في الدردشة الجماعية ونرسل ميمز."),("Ziad","Text me one. I need a good laugh.","أرسل لي واحداً. أحتاج ضحكة جيدة."),("Omar","Done. Don't blame me if it's a bad joke.","تم. لا تلمني إن كانت نكتة سيئة.")],
 2:[("Sara","What does your brother do after school?","ماذا يفعل أخوك بعد المدرسة؟"),("Noor","He plays football, then he watches videos about it.","يلعب كرة القدم، ثم يشاهد فيديوهات عنها."),("Sara","So football is his hobby?","إذاً كرة القدم هوايته؟"),("Noor","Hobby? He trains like it's his job!","هواية؟ يتدرب وكأنها وظيفته!")],
 3:[("Hamad","Was the movie awesome or boring?","هل كان الفيلم رائعاً أم مملاً؟"),("Ziad","Kind of weird, honestly. The ending was lame.","غريب نوعاً ما، بصراحة. النهاية كانت سخيفة."),("Hamad","Everyone online says it's cool though.","لكن الجميع على الإنترنت يقولون إنه رائع."),("Ziad","Everyone online is annoying.","الجميع على الإنترنت مزعجون.")],
 4:[("Omar","Your room is so neat. Is that a new poster?","غرفتك مرتبة جداً. هل هذا ملصق جديد؟"),("Sara","Yes! And I finally got a beanbag next to the desk.","نعم! وأخيراً حصلت على كرسي خرز بجانب المكتب."),("Omar","The speaker on the shelf is nice too.","السماعة على الرف جميلة أيضاً."),("Sara","Don't touch the lamp, it's my favourite.","لا تلمس المصباح، إنه المفضل لدي.")],
 5:[("Noor","Sneakers or boots for the trip?","أحذية رياضية أم جزمة للرحلة؟"),("Hamad","Sneakers, obviously. And a hoodie.","أحذية رياضية، بالطبع. وهودي."),("Noor","Take your headphones too. The bus is loud.","خذ سماعاتك أيضاً. الحافلة صاخبة."),("Hamad","Already in my backpack.","في حقيبتي بالفعل.")],
 6:[("Ziad","Are those your classmates or your teammates?","هل هؤلاء زملاء الصف أم زملاء الفريق؟"),("Omar","Both. And two of them are my cousins.","كلاهما. واثنان منهم أبناء عمي."),("Ziad","Squad goals. Do your neighbors play too?","أهداف الفريق. هل يلعب جيرانك أيضاً؟"),("Omar","Only when they want followers for their videos.","فقط عندما يريدون متابعين لفيديوهاتهم.")],
 7:[("Sara","Whose phone is this? The screen is cracked.","هاتف من هذا؟ الشاشة مكسورة."),("Noor","Not mine. Mine has a charger attached.","ليس لي. هاتفي متصل بالشاحن."),("Sara","There's a fitness app open... and earbuds.","هناك تطبيق لياقة مفتوح... وسماعات أذن."),("Noor","Then it's Hamad's. He forgot his password again.","إذاً هو هاتف حمد. نسي كلمة السر مجدداً.")],
 8:[("Hamad","Meet me at the lockers, then the cafeteria?","قابلني عند الخزائن، ثم الكافتيريا؟"),("Ziad","Can we go to the library first? I need a book.","هل يمكننا الذهاب إلى المكتبة أولاً؟ أحتاج كتاباً."),("Hamad","Fine, but the hallway is packed right now.","حسناً، لكن الممر مزدحم الآن."),("Ziad","Then the gym way. It's faster.","إذاً من طريق الصالة الرياضية. إنه أسرع.")],
 9:[("Omar","Can you skate? Like, actually?","هل تستطيع التزلج؟ فعلاً؟"),("Sara","A little. I can bake better than I can skate.","قليلاً. أستطيع الخبز أفضل من التزلج."),("Omar","Send me the recipe. I'll code an app for it.","أرسلي لي الوصفة. سأبرمج تطبيقاً لها."),("Sara","An app for cookies? Okay, that's cool.","تطبيق للبسكويت؟ حسناً، هذا رائع.")],
 10:[("Noor","Give me a clue. Is it an animal?","أعطني تلميحاً. هل هو حيوان؟"),("Hamad","No. It's a mystery, not a riddle.","لا. إنه لغز وليس أحجية."),("Noor","That's not a clue, that's a secret.","هذا ليس تلميحاً، هذا سر."),("Hamad","Fine. It's something you're holding.","حسناً. إنه شيء تمسكينه.")],
 11:[("Ziad","Who's faster, you or your opponent?","من الأسرع، أنت أم منافسك؟"),("Omar","Me. I beat my own record in the last race.","أنا. كسرت رقمي القياسي في السباق الأخير."),("Ziad","Did you get a medal?","هل حصلت على ميدالية؟"),("Omar","No, but the score says I should have.","لا، لكن النتيجة تقول إنه كان يجب ذلك.")],
 12:[("Sara","There's a newcomer in our class today.","هناك وافد جديد في صفنا اليوم."),("Noor","He looks nervous. Let's introduce ourselves.","يبدو متوتراً. لنقدّم أنفسنا."),("Sara","Good idea. Nobody should feel like a stranger.","فكرة جيدة. لا ينبغي لأحد أن يشعر بأنه غريب."),("Noor","Welcome to the crew, then!","مرحباً بك في الشلة إذاً!")],
 13:[("Hamad","Why do we have to raise our hand every time?","لماذا يجب أن نرفع أيدينا في كل مرة؟"),("Ziad","It's the rule. Be quiet and pay attention.","إنها القاعدة. اهدأ وانتبه."),("Hamad","Did you submit the assignment?","هل سلّمت الواجب؟"),("Ziad","Yes. Now line up, we're late.","نعم. الآن اصطف، نحن متأخرون.")],
 14:[("Omar","What are you doing right now?","ماذا تفعل الآن؟"),("Sara","Scrolling, streaming, and pretending I'm studying.","أتصفح وأشاهد بثاً وأتظاهر بأنني أدرس."),("Omar","Same. I'm gaming and texting at once.","نفس الشيء. ألعب وأتراسل في نفس الوقت."),("Sara","We're both just chilling, be honest.","كلانا نسترخي فقط، كن صادقاً.")],
 15:[("Noor","Let's memorize this with flashcards.","لنحفظ هذا بالبطاقات التعليمية."),("Hamad","Or highlight the textbook and quiz each other.","أو نظلل الكتاب ونختبر بعضنا."),("Noor","The group project presentation is Thursday.","عرض المشروع الجماعي يوم الخميس."),("Hamad","Then flashcards tonight, quiz tomorrow.","إذاً بطاقات الليلة، واختبار غداً.")],
 16:[("Ziad","Game night! Who's the champion this time?","ليلة الألعاب! من البطل هذه المرة؟"),("Omar","Me, if my controller works. My strategy is ready.","أنا، إذا عمل جهاز التحكم. استراتيجيتي جاهزة."),("Ziad","Your strategy is pressing every button.","استراتيجيتك هي الضغط على كل الأزرار."),("Omar","And it got me the high score. Level up!","وحصلت بها على أعلى نتيجة. مستوى جديد!")],
 17:[("Sara","Which genre tonight? I have popcorn.","أي نوع الليلة؟ لدي فشار."),("Noor","Anything with subtitles. I saw a great trailer.","أي شيء بترجمة. رأيت إعلاناً رائعاً."),("Sara","Is it a sequel?","هل هو جزء ثانٍ؟"),("Noor","Yes, but you don't need to see the first one.","نعم، لكنك لا تحتاجين لمشاهدة الأول.")],
 18:[("Hamad","In my opinion, we should choose the park.","برأيي، يجب أن نختار الحديقة."),("Ziad","I disagree. The mall has better food.","لا أوافق. المول فيه طعام أفضل."),("Hamad","Give me one good reason.","أعطني سبباً واحداً وجيهاً."),("Ziad","It's raining. Decide now.","إنها تمطر. قرر الآن.")],
 19:[("Omar","I'm so nervous about the big match.","أنا متوتر جداً بشأن المباراة الكبيرة."),("Sara","Don't be. Teamwork is what wins.","لا تكن كذلك. العمل الجماعي هو ما ينتصر."),("Omar","Will you cheer for us?","هل ستشجعيننا؟"),("Sara","Loudest voice in the crowd. Make me proud.","أعلى صوت في الجمهور. اجعلني فخورة.")],
 20:[("Noor","What goes in our time capsule?","ماذا نضع في كبسولة الزمن؟"),("Hamad","A poster, a meme, and one awesome memory.","ملصق وميم وذكرى رائعة واحدة."),("Noor","Add the crew's best joke.","أضف أفضل نكتة للشلة."),("Hamad","Deal. Future us will laugh so hard.","اتفقنا. نحن في المستقبل سنضحك كثيراً.")],
}
