# Second dialogue per Level 6 lesson: named core characters, six lines,
# plans / predictions / comparisons / debate register. (speaker, en, ar)
CREW_TALK = {
 1:[("Omar","What are your plans after exams?","ما خططك بعد الامتحانات؟"),("Sara","I'm going to visit my grandmother, then join a summer job.","سأزور جدتي، ثم ألتحق بعمل صيفي."),("Omar","A job? Where are you going to apply?","عمل؟ أين ستتقدمين؟"),("Sara","The bookshop downtown. They start hiring in June.","المكتبة في وسط المدينة. يبدؤون التوظيف في يونيو."),("Omar","I'm going to move to the football team's summer camp.","سأنتقل إلى المعسكر الصيفي لفريق كرة القدم."),("Sara","Two very different summers. Both good.","صيفان مختلفان جداً. كلاهما جيد.")],
 2:[("Ziad","I predict our team will win on Saturday.","أتوقع أن يفوز فريقنا يوم السبت."),("Hamad","Probably. Maybe. Definitely not if you play.","على الأرجح. ربما. بالتأكيد لا إن لعبت أنت."),("Ziad","I believe in myself, even if you don't.","أنا أؤمن بنفسي، حتى لو لم تكن أنت."),("Hamad","I believe the future has surprises.","أؤمن أن المستقبل فيه مفاجآت."),("Ziad","Like me scoring twice.","مثل تسجيلي هدفين."),("Hamad","That would definitely be a surprise.","هذه ستكون مفاجأة بالتأكيد.")],
 3:[("Noor","This weekend I'm attending a concert and hosting a study group.","في عطلة نهاية الأسبوع سأحضر حفلة وأستضيف مجموعة دراسة."),("Sara","Same weekend? When are you leaving for the concert?","نفس العطلة؟ متى ستغادرين إلى الحفلة؟"),("Noor","Saturday at six. The study group is starting at ten on Sunday.","السبت الساعة السادسة. مجموعة الدراسة تبدأ العاشرة يوم الأحد."),("Sara","I'm meeting my cousins Sunday, but I'll come after.","سأقابل أبناء عمي يوم الأحد، لكن سآتي بعدها."),("Noor","Perfect. Bring the notes from the party lesson.","ممتاز. أحضري الملاحظات من درس الحفلة."),("Sara","Traveling from one plan to another. That's us.","نسافر من خطة إلى أخرى. هذا نحن.")],
 4:[("Hamad","I was doing my homework when the call came.","كنت أحل واجبي عندما جاءت المكالمة."),("Omar","Who interrupted you?","من قاطعك؟"),("Hamad","Ziad. He noticed it started raining and wanted to play football anyway.","زياد. لاحظ أن المطر بدأ وأراد أن يلعب كرة القدم رغم ذلك."),("Omar","What happened next?","ماذا حدث بعد ذلك؟"),("Hamad","Meanwhile, my mom arrived and said no. In that moment, I was relieved.","في هذه الأثناء، وصلت أمي وقالت لا. في تلك اللحظة، شعرت بالارتياح."),("Omar","Rain plus Ziad equals mud. Wise mom.","مطر زائد زياد يساوي طيناً. أم حكيمة.")],
 5:[("Sara","Do we have to submit the form today?","هل يجب أن نسلّم النموذج اليوم؟"),("Ziad","It's required. The photo is optional though.","إنه مطلوب. لكن الصورة اختيارية."),("Sara","You don't have to add a photo? Then why did you?","لا يجب أن تضيف صورة؟ إذاً لماذا فعلت؟"),("Ziad","Responsibility. Also my hair looked great that day.","المسؤولية. وأيضاً شعري بدا رائعاً في ذلك اليوم."),("Sara","Your duty is the form, not the hair.","واجبك النموذج وليس الشعر."),("Ziad","A leader has many duties.","القائد له واجبات كثيرة.")],
 6:[("Omar","Noor finished the puzzle so quickly.","نور أنهت الأحجية بسرعة كبيرة."),("Hamad","She works carefully and quietly. That's why.","تعمل بعناية وهدوء. لهذا السبب."),("Omar","I work loudly and easily lose the pieces.","أنا أعمل بصخب وأفقد القطع بسهولة."),("Hamad","You should do it patiently, like she does.","يجب أن تفعلها بصبر، مثلها."),("Omar","Patiently is not my style.","الصبر ليس أسلوبي."),("Hamad","Then losing is your style.","إذاً الخسارة أسلوبك.")],
 7:[("Noor","This book is more interesting than the movie.","هذا الكتاب أكثر إثارة من الفيلم."),("Sara","But the movie is more exciting, and less difficult!","لكن الفيلم أكثر تشويقاً، وأقل صعوبة!"),("Noor","The book was the most popular in class, though.","لكن الكتاب كان الأكثر شعبية في الصف."),("Sara","Because it was cheaper. The cinema is more expensive.","لأنه كان أرخص. السينما أغلى."),("Noor","And the library chairs are the most comfortable.","وكراسي المكتبة هي الأكثر راحة."),("Sara","Fine. Book wins. Even better than I thought.","حسناً. الكتاب يفوز. أفضل مما ظننت.")],
 8:[("Ziad","Weekend plans: sleep in, then hang out downtown.","خطط عطلة نهاية الأسبوع: أنام متأخراً، ثم أقضي وقتاً في وسط المدينة."),("Hamad","I'm going to volunteer at the charity on Saturday morning.","سأتطوع في الجمعية الخيرية صباح السبت."),("Ziad","In the morning? On a Saturday?","في الصباح؟ يوم السبت؟"),("Hamad","Yes. Then I'll catch up on sleep and relax.","نعم. ثم سأعوض النوم وأسترخي."),("Ziad","Can I come and explore with you after?","هل يمكنني المجيء والاستكشاف معك بعدها؟"),("Hamad","Only if you wake up before noon.","فقط إذا استيقظت قبل الظهر.")],
 9:[("Sara","Predictions about us: who will graduate first?","توقعات عنا: من سيتخرج أولاً؟"),("Omar","Noor, definitely. Then she'll travel and invent something.","نور بالتأكيد. ثم ستسافر وتخترع شيئاً."),("Sara","And Ziad?","وزياد؟"),("Omar","Ziad will succeed in games and change the whole industry.","زياد سينجح في الألعاب وسيغير الصناعة كلها."),("Sara","What about you?","ماذا عنك؟"),("Omar","I'll achieve one goal at a time. The future is long.","سأحقق هدفاً واحداً في كل مرة. المستقبل طويل.")],
 10:[("Noor","My parents set a new curfew. Nine o'clock.","والداي وضعا حظر تجول جديداً. الساعة التاسعة."),("Hamad","Do you need permission for everything now?","هل تحتاجين إذناً لكل شيء الآن؟"),("Noor","No. I'm allowed to choose my chores, and they trust me with the rest.","لا. مسموح لي أن أختار أعمالي المنزلية، ويثقون بي في الباقي."),("Hamad","That's fair. Trust makes you independent.","هذا عادل. الثقة تجعلك مستقلة."),("Noor","Independent with a nine o'clock curfew.","مستقلة مع حظر تجول في التاسعة."),("Hamad","Independent enough.","مستقلة بما فيه الكفاية.")],
 11:[("Ziad","You explained that so clearly in class. How?","شرحت ذلك بوضوح شديد في الصف. كيف؟"),("Sara","I spoke slowly and politely, and I looked at the teacher.","تحدثت ببطء وبأدب، ونظرت إلى المعلم."),("Ziad","I always speak nervously and too fast.","أنا دائماً أتحدث بتوتر وبسرعة كبيرة."),("Sara","Honestly, everyone does at first. Practise speaking confidently.","بصراحة، الجميع يفعل ذلك في البداية. تدرب على التحدث بثقة."),("Ziad","And kindly? The teacher likes kindly.","وبلطف؟ المعلم يحب اللطف."),("Sara","Kindly is free. Start there.","اللطف مجاني. ابدأ من هناك.")],
 12:[("Omar","Bus or bike to school? Which is better?","حافلة أم دراجة إلى المدرسة؟ أيهما أفضل؟"),("Noor","The bike is more convenient, and it's the most reliable.","الدراجة أكثر ملاءمة، وهي الأكثر موثوقية."),("Omar","The bus is more reasonable in the rain though.","لكن الحافلة أكثر منطقية في المطر."),("Noor","Is it worth it? The bus is late every day.","هل تستحق؟ الحافلة تتأخر كل يوم."),("Omar","So the most useful option depends on the weather.","إذاً الخيار الأكثر فائدة يعتمد على الطقس."),("Noor","Now you're being reasonable.","الآن أنت منطقي.")],
 13:[("Hamad","I was cooking, chatting, and scrolling at the same time.","كنت أطبخ وأدردش وأتصفح في نفس الوقت."),("Ziad","That's not multitasking, that's a fire hazard.","هذا ليس تعدد مهام، هذا خطر حريق."),("Hamad","My sister was studying while my dad was driving us.","أختي كانت تدرس بينما كان أبي يقودنا."),("Ziad","And you?","وأنت؟"),("Hamad","I was on my phone. I lost focus on every task.","كنت على هاتفي. فقدت التركيز في كل مهمة."),("Ziad","One task, one phone-free hour. Try it.","مهمة واحدة، ساعة بدون هاتف. جرّبها.")],
 14:[("Sara","Next year's goal: improve my English and read more.","هدف العام القادم: تحسين لغتي الإنجليزية والقراءة أكثر."),("Omar","My resolution is to challenge myself with harder books.","قراري أن أتحدى نفسي بكتب أصعب."),("Sara","Do you expect to keep it?","هل تتوقع أن تلتزم به؟"),("Omar","I hope so. I wrote a list in my diary.","آمل ذلك. كتبت قائمة في يومياتي."),("Sara","A list is a start. Reading it every week is the trick.","القائمة بداية. قراءتها كل أسبوع هي السر."),("Omar","Then that's goal number two.","إذاً هذا الهدف رقم اثنين.")],
 15:[("Noor","In my point of view, school should start later.","من وجهة نظري، يجب أن تبدأ المدرسة في وقت متأخر."),("Hamad","Convince me. What's your evidence?","أقنعيني. ما دليلك؟"),("Noor","Studies show teens learn better after nine.","الدراسات تظهر أن المراهقين يتعلمون أفضل بعد التاسعة."),("Hamad","Fair point. But I agree partly. Buses would be crowded.","نقطة عادلة. لكنني أوافق جزئياً. الحافلات ستكون مزدحمة."),("Noor","You argue well. But you didn't win.","تجادل جيداً. لكنك لم تفز."),("Hamad","A debate isn't about winning. Mostly.","المناظرة ليست عن الفوز. غالباً.")],
 16:[("Ziad","Are you ready for the presentation tomorrow?","هل أنت جاهز للعرض غداً؟"),("Omar","I prepared the notes, organized the slides, and practised twice.","جهزت الملاحظات، رتبت الشرائح، وتدربت مرتين."),("Ziad","Did you review the checklist?","هل راجعت قائمة التحقق؟"),("Omar","Yes. Now I'm going to rest. A tired brain is not ready.","نعم. الآن سأرتاح. الدماغ المتعب ليس جاهزاً."),("Ziad","I haven't started.","لم أبدأ بعد."),("Omar","Then get ready. Now. I'll send you my checklist.","إذاً استعد. الآن. سأرسل لك قائمتي.")],
 17:[("Sara","Do it properly this time. Safely, too.","افعلها بشكل صحيح هذه المرة. وبأمان أيضاً."),("Hamad","I'm cutting the paper neatly and the glue is going on smoothly.","أقص الورق بدقة والغراء يُوضع بسلاسة."),("Sara","Efficiently, too. We only have ten minutes.","وبكفاءة أيضاً. لدينا عشر دقائق فقط."),("Hamad","Correctly matters more than quickly.","بشكل صحيح أهم من بسرعة."),("Sara","Both matter. That's the whole lesson.","كلاهما مهم. هذا هو الدرس كله."),("Hamad","Done. Properly, safely, neatly. Check.","تم. بشكل صحيح، بأمان، بدقة. تحقق.")],
 18:[("Noor","Every culture has a tradition for guests.","كل ثقافة لها تقليد للضيوف."),("Ziad","Ours is coffee and dates. What's the most colorful custom you know?","تقليدنا القهوة والتمر. ما أكثر عادة ملونة تعرفها؟"),("Noor","The lantern festival. The most traditional ones are hand-painted.","مهرجان الفوانيس. الأكثر تقليدية مرسومة يدوياً."),("Ziad","Our lifestyle is similar in one way: family first.","أسلوب حياتنا متشابه في شيء واحد: العائلة أولاً."),("Noor","Similar hearts, different colors.","قلوب متشابهة، ألوان مختلفة."),("Ziad","That should be on a poster.","يجب أن يكون هذا على ملصق.")],
 19:[("Omar","The field trip was memorable for the wrong reasons.","الرحلة المدرسية كانت لا تُنسى لأسباب خاطئة."),("Sara","Something unexpected happened?","هل حدث شيء غير متوقع؟"),("Omar","The bus broke down. Hamad handled it: he called the school and kept everyone calm.","الحافلة تعطلت. حمد تعامل مع الأمر: اتصل بالمدرسة وأبقى الجميع هادئين."),("Sara","And you? Were you excited or scared?","وأنت؟ كنت متحمساً أم خائفاً؟"),("Omar","Both. The lesson learned: always pack snacks.","كلاهما. الدرس المستفاد: احزم دائماً وجبات خفيفة."),("Sara","And always bring Hamad.","وأحضر حمد دائماً.")],
 20:[("Hamad","My future plans project: I'm going to apply for a scholarship.","مشروع خططي المستقبلية: سأتقدم لمنحة دراسية."),("Noor","I predict you'll definitely get it.","أتوقع أنك ستحصل عليها بالتأكيد."),("Hamad","Meanwhile, I'm hosting a study group and traveling in July.","في هذه الأثناء، أستضيف مجموعة دراسة وأسافر في يوليو."),("Noor","Nothing interrupted your plan?","لم يقاطع خطتك شيء؟"),("Hamad","Only exams. And exams are part of the plan.","الامتحانات فقط. والامتحانات جزء من الخطة."),("Noor","That's the most organized future I've ever heard.","هذا أكثر مستقبل منظم سمعته على الإطلاق.")],
}


# Second Crew Talk per lesson (A2 richness campaign): a shorter, later
# conversation (4 lines / 2 exchanges) using more of the lesson's own
# vocabulary in a fresh situation. Skipped for Lesson 20.
CREW_TALK_2 = {
 1:[("Noor","Are you going to apply for the internship too?","هل ستتقدمين للتدريب أيضاً؟"),("Sara","Yes, and I'm going to ask about the scholarship in the same email.","نعم، وسأسأل عن المنحة في نفس الإيميل."),("Noor","Smart. What's your schedule like this week?","ذكي. كيف جدولك هذا الأسبوع؟"),("Sara","Packed, but I'll join the team meeting first.","مزدحم، لكنني سألتحق باجتماع الفريق أولاً.")],
 2:[("Hamad","Do you think it will rain during the match?","هل تظن أنها ستمطر أثناء المباراة؟"),("Ziad","Probably not. The forecast says it's unlikely.","على الأرجح لا. التوقعات تقول إنه غير مرجح."),("Hamad","I'm certain we'll win anyway.","أنا متأكد أننا سنفوز على أي حال."),("Ziad","Maybe. I believe in the team, definitely.","ربما. أؤمن بالفريق، بالتأكيد.")],
 3:[("Omar","Are you leaving for the concert straight after school?","هل ستغادرين للحفلة فور انتهاء المدرسة؟"),("Noor","Yes, and I'm meeting Sara at the ticket booth first.","نعم، وسأقابل سارة عند شباك التذاكر أولاً."),("Omar","Did you finish booking everything?","هل أنهيت حجز كل شيء؟"),("Noor","Almost. I just need to check the guest list.","تقريباً. أحتاج فقط لمراجعة قائمة الضيوف.")],
 4:[("Ziad","What happened while you were walking home?","ماذا حدث بينما كنت تمشي إلى المنزل؟"),("Hamad","It started raining suddenly, and as soon as I noticed, I ran.","بدأ المطر فجأة، وبمجرد أن لاحظت، ركضت."),("Ziad","Did anyone call you at that moment?","هل اتصل بك أحد في تلك اللحظة؟"),("Hamad","Yes, my mom, but by the time I answered, I was already soaked.","نعم، أمي، لكن بحلول وقت ردي، كنت مبللاً تماماً.")],
 5:[("Sara","Is attending the workshop mandatory or optional?","هل حضور الورشة إلزامي أم اختياري؟"),("Omar","Optional, but volunteering counts as extra responsibility.","اختياري، لكن التطوع يُحسب مسؤولية إضافية."),("Sara","Do we need permission from home for that?","هل نحتاج إذناً من المنزل لذلك؟"),("Omar","Yes, that part is definitely required.","نعم، هذا الجزء مطلوب بالتأكيد.")],
 6:[("Hamad","How did you finish so accurately and so quickly?","كيف أنهيت بدقة وبسرعة هكذا؟"),("Noor","I worked carefully, and I checked everything gently before submitting.","عملت بعناية، وتحققت من كل شيء برفق قبل التسليم."),("Hamad","I always rush and do it loudly and badly.","أنا دائماً أتسرع وأفعلها بصخب وبشكل سيئ."),("Noor","Try patiently next time, not quickly.","جرب بصبر المرة القادمة، وليس بسرعة.")],
 7:[("Ziad","Which phone is the most reliable, in your opinion?","أي هاتف الأكثر موثوقية، برأيك؟"),("Sara","The newer one is more expensive but healthier for the battery, honestly.","الأحدث أغلى لكنه أفضل للبطارية، بصراحة."),("Ziad","Is it really the most popular one at school?","هل هو حقاً الأكثر شعبية في المدرسة؟"),("Sara","Definitely. And it's cheaper than the one Omar has.","بالتأكيد. وهو أرخص من هاتف عمر.")],
 8:[("Omar","Are we still going on the road trip this weekend?","هل ما زلنا سنقوم برحلة برية هذا الأسبوع؟"),("Hamad","Yes, after I catch up on sleep and relax a little first.","نعم، بعد أن أعوض النوم وأسترخي قليلاً أولاً."),("Omar","Can we stop downtown for brunch on the way?","هل يمكننا التوقف في وسط المدينة لوجبة برانش في الطريق؟"),("Hamad","Definitely, and maybe a board game after.","بالتأكيد، وربما لعبة لوحية بعدها.")],
 9:[("Noor","Do you think technology will solve every future problem?","هل تظنين أن التكنولوجيا ستحل كل مشكلة مستقبلية؟"),("Sara","Not every problem, but I predict we'll discover a lot.","ليس كل مشكلة، لكنني أتوقع أننا سنكتشف الكثير."),("Noor","Will you succeed in your own goal, then?","هل ستنجحين في هدفك الخاص إذاً؟"),("Sara","I believe so. I'll achieve it step by step.","أعتقد ذلك. سأحققه خطوة بخطوة.")],
 10:[("Hamad","Are you allowed to skip chores this week?","هل مسموح لك بتخطي الأعمال المنزلية هذا الأسبوع؟"),("Ziad","No, but my parents trust me with the curfew now.","لا، لكن والداي يثقان بي في حظر التجول الآن."),("Hamad","Do they still need to give permission for outings?","هل ما زالا يحتاجان لإعطاء إذن للخروج؟"),("Ziad","Less than before. I'm more independent, and I respect that.","أقل من قبل. أنا أكثر استقلالية، وأحترم ذلك.")],
 11:[("Sara","Did you speak confidently in the interview?","هل تحدثت بثقة في المقابلة؟"),("Noor","I tried, and I kept good eye contact the whole time.","حاولت، وحافظت على تواصل بصري جيد طوال الوقت."),("Sara","Was your tone calm, or a little nervous?","هل كانت نبرتك هادئة، أم متوترة قليلاً؟"),("Noor","A little nervous, but I answered politely and honestly.","متوترة قليلاً، لكنني أجبت بأدب وصدق.")],
 12:[("Ziad","Which option is more affordable for you?","أي خيار أكثر بأسعار معقولة بالنسبة لك؟"),("Omar","The used one, and it seems durable enough.","المستعمل، ويبدو متيناً بما فيه الكفاية."),("Ziad","Is it worth it compared to the new one?","هل يستحق مقارنة بالجديد؟"),("Omar","I think so — it's efficient, and the price is reasonable.","أعتقد ذلك — إنه فعال، والسعر معقول.")],
 13:[("Noor","Were you scrolling your phone while I was talking?","هل كنت تتصفح هاتفك بينما كنت أتحدث؟"),("Hamad","Sorry, I was trying to focus, but the notifications were a distraction.","آسف، كنت أحاول التركيز، لكن الإشعارات كانت تشتيتاً."),("Noor","Set a timer next time so you stay productive.","اضبط مؤقتاً المرة القادمة لتبقى منتجاً."),("Hamad","Good idea. One task at a time from now on.","فكرة جيدة. مهمة واحدة في كل مرة من الآن.")],
 14:[("Sara","What's your biggest goal for next year?","ما أكبر هدفك للعام القادم؟"),("Ziad","To improve my grades and reach one big milestone.","تحسين درجاتي والوصول لإنجاز كبير واحد."),("Sara","Do you track your progress anywhere?","هل تتابع تقدمك في أي مكان؟"),("Ziad","In a diary. It keeps my motivation up.","في يوميات. هذا يبقي حماسي مرتفعاً.")],
 15:[("Omar","Did your point of view change after the debate?","هل تغيرت وجهة نظرك بعد المناظرة؟"),("Noor","A little — Hamad had a fair point and good evidence.","قليلاً — كان لحمد نقطة عادلة ودليل جيد."),("Omar","So you agree partly with the counterargument now?","إذاً أنت توافقين جزئياً على الحجة المضادة الآن؟"),("Noor","Partly. But my conclusion is still the same.","جزئياً. لكن استنتاجي ما زال كما هو.")],
 16:[("Hamad","Did you organize your notes before the rehearsal?","هل رتبت ملاحظاتك قبل البروفة؟"),("Sara","Yes, and I made a checklist with a backup plan too.","نعم، وأعددت قائمة تحقق مع خطة بديلة أيضاً."),("Hamad","Smart. Did you review the timeline?","ذكي. هل راجعت الجدول الزمني؟"),("Sara","Twice. Now I just need to rest before tomorrow.","مرتين. الآن أحتاج فقط للراحة قبل الغد.")],
 17:[("Ziad","Did you follow the instructions step by step?","هل اتبعت التعليمات خطوة بخطوة؟"),("Omar","Yes, and I double-checked everything before moving on.","نعم، وتحققت من كل شيء مرتين قبل المتابعة."),("Ziad","Was it smooth, or did something go wrong?","هل كان سلساً، أم حدث خطأ ما؟"),("Omar","Smooth. Doing it properly the first time saved time.","سلساً. فعلها بشكل صحيح من أول مرة وفّر الوقت.")],
 18:[("Noor","What tradition is the most colorful in your family?","أي تقليد هو الأكثر ألواناً في عائلتك؟"),("Sara","Our Eid customs, definitely. The food is part of our heritage too.","عادات العيد لدينا، بالتأكيد. الطعام جزء من تراثنا أيضاً."),("Noor","Is your lifestyle similar to your cousins' in other countries?","هل أسلوب حياتكم مشابه لأبناء عمكم في دول أخرى؟"),("Sara","Similar hospitality, different cuisine.","نفس الضيافة، مطبخ مختلف.")],
 19:[("Hamad","What was the most unexpected part of the school trip?","ما أكثر جزء غير متوقع في الرحلة المدرسية؟"),("Ziad","The headcount was wrong, and the chaperone had to recheck twice.","عدد الطلاب كان خاطئاً، واضطر المرافق لإعادة العد مرتين."),("Hamad","Was the itinerary still followed after that?","هل تم اتباع خطة الرحلة بعد ذلك؟"),("Ziad","Mostly. The lesson learned made it memorable anyway.","في الغالب. الدرس المستفاد جعلها لا تُنسى على أي حال.")],
}
