# -*- coding: utf-8 -*-
"""Level 5 "Phrase Focus" content (per Eslam's A2 richness campaign):
3 real, commonly-used phrases/sentences per lesson tied to its topic --
distinct from the grammar-driven "Notice the Pattern" slide -- each
with a plain-English gloss and an Arabic line, for the teacher to
pause on and explain. Skipped for Lesson 20 (review/project lesson).

Each entry: (phrase_en, gloss_en, phrase_ar)
"""
PHRASE_FOCUS = {
 1: [("How was your weekend?", "the standard way to ask what someone did recently", "كيف كانت عطلتك؟"),
     ("I didn't do much.", "a common, modest answer even after a busy weekend", "لم أفعل الكثير."),
     ("Same old, same old.", "nothing new happened, it was an ordinary weekend", "نفس الروتين المعتاد.")],
 2: [("Guess what happened!", "an exciting way to introduce a story", "خمن ماذا حدث!"),
     ("You won't believe it.", "building excitement before telling a surprising story", "لن تصدق ذلك."),
     ("Long story short...", "summarizing a story quickly before the details", "باختصار...")],
 3: [("Did you, by any chance...?", "a polite, gentle way to ask if something happened", "هل حدث، بأي حال، أن...؟"),
     ("Nope, not at all.", "a casual, firm way to say no", "لا، إطلاقاً."),
     ("I totally forgot!", "admitting you completely forgot to do something", "نسيت تماماً!")],
 4: [("It was out of this world.", "something was amazing, beyond expectations", "كان شيئاً خيالياً."),
     ("It could've been better.", "something was okay, but disappointing in some way", "كان يمكن أن يكون أفضل."),
     ("Nothing special.", "an experience was plain, not memorable", "لا شيء مميز.")],
 5: [("Back in the day...", "starting a story about the past, often nostalgic", "في ذلك الزمان..."),
     ("There used to be...", "describing something that existed before but not now", "كان يوجد..."),
     ("Those were the days.", "looking back fondly on an earlier time", "تلك كانت أيام جميلة.")],
 6: [("It feels like yesterday.", "something from the past still feels recent", "يبدو وكأنه حدث بالأمس."),
     ("Time flies!", "time passes faster than you expect", "الوقت يمر بسرعة!"),
     ("A while back.", "a vague way to say something happened some time ago", "منذ فترة.")],
 7: [("To make a long story short...", "skipping to the end of a long story", "باختصار الحكاية..."),
     ("And then, out of nowhere...", "something unexpected suddenly happened in a story", "وفجأة، من العدم..."),
     ("And that's how it happened.", "closing a story after explaining the events", "وهكذا حدث الأمر.")],
 8: [("That's the reason why...", "clearly stating the cause of something", "هذا هو سبب..."),
     ("No excuses!", "refusing to accept a reason for something wrong", "لا أعذار!"),
     ("It's not my fault.", "denying responsibility for something that went wrong", "ليس خطئي.")],
 9: [("I was over the moon.", "feeling extremely happy about something", "كنت في قمة السعادة."),
     ("My heart sank.", "feeling a sudden wave of sadness or disappointment", "انقبض قلبي."),
     ("I couldn't believe my eyes.", "being extremely surprised by what you saw", "لم أصدق عينيّ.")],
 10: [("Right in the middle of it...", "something happened while another thing was going on", "في خضم ذلك تماماً..."),
      ("I was in the middle of something.", "explaining you were busy doing something when interrupted", "كنت منشغلاً بشيء ما."),
      ("Everything happened at once.", "several things occurred at the same time", "كل شيء حدث في آن واحد.")],
 11: [("I pulled an all-nighter.", "stayed up all night studying or working", "سهرت طوال الليل للمذاكرة."),
      ("It paid off.", "hard work led to a good result", "الجهد آتى ثماره."),
      ("Practice makes perfect.", "the more you practise, the better you get", "التدريب يصنع الإتقان.")],
 12: [("It was the trip of a lifetime.", "an unforgettable, once-in-a-lifetime journey", "كانت رحلة العمر."),
      ("We packed our bags and left.", "getting ready and departing quickly", "حزمنا حقائبنا وغادرنا."),
      ("I brought back souvenirs.", "bringing gifts or mementos home from a trip", "أحضرت هدايا تذكارية.")],
 13: [("One thing after another.", "many problems happening in a row", "مشكلة تلو الأخرى."),
      ("It was a disaster!", "something went very badly wrong", "كانت كارثة!"),
      ("I managed to fix it.", "you succeeded in solving a problem despite difficulty", "تمكنت من إصلاحها.")],
 14: [("The more, the merrier!", "a bigger group makes an event more fun", "كلما زاد العدد، زاد المرح!"),
      ("It was a blast!", "an event was extremely fun", "كانت رائعة جداً!"),
      ("Let's throw a party.", "suggesting to organise a celebration", "لنقم حفلة.")],
 15: [("A day to remember.", "describing a memorable, special day", "يوم لا يُنسى."),
      ("It's a memory I'll treasure forever.", "a moment that will always be special to you", "ذكرى سأعتز بها للأبد."),
      ("Best day ever!", "an enthusiastic way to describe an amazing day", "أفضل يوم على الإطلاق!")],
 16: [("While all this was going on...", "describing background events happening at the same time", "بينما كان كل هذا يجري..."),
      ("Meanwhile, back at...", "shifting the story to what was happening elsewhere", "في تلك الأثناء، في..."),
      ("At the same time.", "two things happening simultaneously", "في نفس الوقت.")],
 17: [("Tell me about yourself.", "the classic opening line of an interview", "حدثني عن نفسك."),
      ("That's a great question.", "a polite way to buy a moment to think before answering", "هذا سؤال رائع."),
      ("If I had to pick one...", "narrowing down to a single favourite when asked", "إذا كان علي أن أختار واحداً...")],
 18: [("Spoiler alert!", "warning that you're about to reveal an ending", "تحذير من حرق الأحداث!"),
      ("I was on the edge of my seat.", "a movie was so exciting you felt tense watching it", "كنت متحمساً للغاية أثناء المشاهدة."),
      ("Two thumbs up.", "giving something a strong, enthusiastic recommendation", "أنصح به بشدة.")],
 19: [("Lost and found.", "the place or process for recovering something misplaced", "قسم المفقودات."),
      ("I searched high and low.", "looking everywhere thoroughly for something", "بحثت في كل مكان."),
      ("What a relief!", "feeling relieved after worry or stress ends", "يا له من ارتياح!")],
}
