# -*- coding: utf-8 -*-
"""Level 6 "Phrase Focus" content (per Eslam's A2 richness campaign):
3 real, commonly-used phrases/sentences per lesson tied to its topic --
distinct from the grammar-driven "Notice the Pattern" slide -- each
with a plain-English gloss and an Arabic line, for the teacher to
pause on and explain. Skipped for Lesson 20 (review/project lesson).

Each entry: (phrase_en, gloss_en, phrase_ar)
"""
PHRASE_FOCUS = {
 1: [("What are your plans for the future?", "a common way to ask about someone's goals", "ما خططك للمستقبل؟"),
     ("I'm still figuring it out.", "you haven't decided your plans yet", "ما زلت أفكر في الأمر."),
     ("I'm keeping my options open.", "not committing to one choice yet, staying flexible", "أبقي خياراتي مفتوحة.")],
 2: [("Your guess is as good as mine.", "you have no more idea than the other person", "تخمينك مثل تخميني تماماً."),
     ("Only time will tell.", "we can't know the answer until later", "الوقت وحده كفيل بالإجابة."),
     ("I'd bet on it.", "being very confident a prediction will come true", "أراهن على ذلك.")],
 3: [("I'm all booked up.", "your schedule is completely full", "جدولي ممتلئ تماماً."),
     ("Count me in!", "eagerly agreeing to join a plan", "احسبني معكم!"),
     ("Let's keep in touch.", "asking to stay connected before or after an event", "لنبقَ على تواصل.")],
 4: [("Out of the blue.", "something happened suddenly and unexpectedly", "من العدم، بشكل مفاجئ."),
     ("Talk about timing!", "commenting on something happening at a surprising moment", "يا له من توقيت!"),
     ("Just my luck.", "a sarcastic comment about bad timing or bad luck", "هذا حظي بالضبط.")],
 5: [("Rules are rules.", "insisting that regulations must be followed regardless", "القواعد قواعد."),
     ("It's up to you.", "the choice is optional and depends on the person", "الأمر يعود لك."),
     ("No exceptions.", "a rule applies to everyone with no special cases", "لا استثناءات.")],
 6: [("Slow and steady wins the race.", "being careful and patient leads to success", "الهدوء والثبات يفوزان بالسباق."),
     ("Easier said than done.", "something sounds simple but is actually hard to do", "أسهل قولاً من فعل."),
     ("Practice makes perfect.", "repeating something improves your skill at it", "التدريب يصنع الإتقان.")],
 7: [("It's not even close.", "one thing is clearly, obviously better than another", "لا مجال للمقارنة."),
     ("There's no comparison.", "two things are so different that comparing is pointless", "لا وجه للمقارنة."),
     ("Better late than never.", "doing something late is still better than not doing it", "أن تتأخر خير من ألا تأتي.")],
 8: [("I've got nothing planned.", "having a completely free, open schedule", "ليس لدي أي خطط."),
     ("Let's play it by ear.", "deciding what to do as things happen, without a fixed plan", "لنقرر حسب الظروف."),
     ("Sounds like a plan!", "enthusiastically agreeing to a suggested plan", "يبدو هذا خطة رائعة!")],
 9: [("The sky's the limit.", "there's no limit to what someone could achieve", "لا حدود للطموح."),
     ("I'll believe it when I see it.", "doubting a prediction until there's real proof", "سأصدق عندما أرى ذلك."),
     ("Big things are coming.", "hinting that exciting future events are ahead", "أشياء عظيمة قادمة.")],
 10: [("It's for your own good.", "a rule or decision is meant to help, not punish", "هذا لمصلحتك."),
      ("Fair is fair.", "insisting that a rule should apply equally to everyone", "العدل عدل."),
      ("Trust goes both ways.", "trust must be earned and given by both sides", "الثقة تسير في الاتجاهين.")],
 11: [("It's not what you say, it's how you say it.", "tone and manner matter as much as the words themselves", "ليس المهم ماذا تقول، بل كيف تقوله."),
      ("Actions speak louder than words.", "what you do matters more than what you say", "الأفعال أبلغ من الأقوال."),
      ("Say it like you mean it.", "speak with sincerity and confidence", "قلها وكأنك تقصدها.")],
 12: [("It's a toss-up.", "two options are so close it's hard to choose between them", "الأمر متعادل تماماً."),
      ("You get what you pay for.", "cheaper things are often lower quality", "ما تدفعه هو ما تحصل عليه."),
      ("When in doubt, go with the classic.", "choose the reliable, familiar option when unsure", "عند الشك، اختر الخيار التقليدي.")],
 13: [("I can't do two things at once.", "admitting it's hard to focus on more than one task", "لا أستطيع فعل شيئين في آن واحد."),
      ("One thing at a time.", "advice to focus on a single task before moving to the next", "شيء واحد في كل مرة."),
      ("I lost track of time.", "you were so focused (or distracted) you didn't notice time passing", "فقدت إحساسي بالوقت.")],
 14: [("New year, new me.", "a common resolution about self-improvement", "عام جديد، شخص جديد."),
      ("Small steps lead to big changes.", "gradual progress eventually creates major results", "الخطوات الصغيرة تؤدي لتغييرات كبيرة."),
      ("I'm turning over a new leaf.", "making a fresh start and changing your habits", "أبدأ صفحة جديدة.")],
 15: [("Let's agree to disagree.", "ending a debate respectfully without reaching agreement", "لنتفق على الاختلاف."),
      ("I see your point, but...", "acknowledging someone's argument before disagreeing", "أفهم وجهة نظرك، لكن..."),
      ("That's a fair point.", "admitting the other person made a valid argument", "هذه نقطة عادلة.")],
 16: [("Better safe than sorry.", "it's wiser to prepare than to regret not preparing", "الحذر خير من الندم."),
      ("Fail to prepare, prepare to fail.", "not preparing makes failure likely", "من لا يستعد، يستعد للفشل."),
      ("I've got this.", "expressing confidence that you're ready and capable", "أنا متمكن من الأمر.")],
 17: [("Follow the steps exactly.", "instructions must be done in the correct order", "اتبع الخطوات بالضبط."),
      ("Better safe than sloppy.", "careful, correct work matters more than speed", "الدقة أفضل من الإهمال."),
      ("Measure twice, cut once.", "check carefully before acting to avoid mistakes", "قِس مرتين واقطع مرة واحدة.")],
 18: [("Different strokes for different folks.", "different people and cultures have different preferences", "لكل شخص ذوقه الخاص."),
      ("When in Rome, do as the Romans do.", "adapt to the customs of the place you're in", "إذا كنت في مكان، فاتبع عاداته."),
      ("It's all part of the experience.", "even unfamiliar customs are worth appreciating", "كل هذا جزء من التجربة.")],
 19: [("It was a trip to remember.", "an especially memorable journey or outing", "كانت رحلة لا تُنسى."),
      ("Everything turned out fine in the end.", "despite problems, the outcome was good", "كل شيء انتهى بخير في النهاية."),
      ("Lesson learned.", "acknowledging you now understand something from an experience", "درس مستفاد.")],
}
