# -*- coding: utf-8 -*-
"""Level 4 "Phrase Focus" content (per Eslam's A2 richness campaign):
3 real, commonly-used phrases/sentences per lesson tied to its topic --
distinct from the grammar-driven "Notice the Pattern" slide -- each
with a plain-English gloss and an Arabic line, for the teacher to
pause on and explain. Skipped for Lesson 20 (review).

Each entry: (phrase_en, gloss_en, phrase_ar)
"""
PHRASE_FOCUS = {
 1: [("I'm exhausted.", "very, very tired", "أنا منهك تماماً."),
     ("I need my beauty sleep.", "I need extra rest to feel (and look) good", "أحتاج نوماً كافياً لأبدو بحال أفضل."),
     ("Rise and shine!", "a cheerful way to wake someone up", "استيقظ بنشاط!")],
 2: [("I'm swamped this week.", "extremely busy", "أنا مثقل بالمشاغل هذا الأسبوع."),
     ("Let's pencil it in.", "schedule something tentatively, it might change", "لنضعه في الجدول مبدئياً."),
     ("I'm running on empty.", "no energy left at all", "طاقتي نفدت تماماً.")],
 3: [("Once in a blue moon.", "very rarely, almost never", "نادراً جداً، مرة كل زمن."),
     ("Every single day.", "emphasizing something happens daily, without exception", "كل يوم دون استثناء."),
     ("I'm a creature of habit.", "someone who likes routine and rarely changes it", "أنا شخص أسير العادة.")],
 4: [("Save the date!", "remember this day, something important is happening", "احجز هذا التاريخ!"),
     ("I'm counting down the days.", "excitedly waiting for something to arrive", "أعد الأيام بفارغ الصبر."),
     ("Let's take a rain check.", "postpone this to another time", "لنؤجلها لوقت آخر.")],
 5: [("Leave me a voicemail.", "record a message if I don't pick up", "اترك لي رسالة صوتية."),
     ("Hit me up.", "casual way of saying \"contact me\"", "تواصل معي."),
     ("I'm typing...", "the status shown while someone writes a chat message", "أنا أكتب...")],
 6: [("That's not mine, it's yours.", "politely correcting who owns something", "هذا ليس لي، إنه لك."),
     ("Finders keepers!", "a playful claim: whoever finds it gets to keep it", "من وجد فقد ملك!"),
     ("Whose is this?", "asking who something belongs to", "لمن هذا؟")],
 7: [("I'm starving!", "extremely hungry", "أتضور جوعاً!"),
     ("Help yourself!", "inviting someone to take food freely", "تفضل، خذ ما تشاء!"),
     ("That hit the spot.", "a meal that was exactly what you needed", "هذا بالضبط ما كنت أحتاجه.")],
 8: [("It's on sale!", "the price has been reduced", "إنه معروض بتخفيض!"),
     ("That's a rip-off!", "something is unfairly overpriced", "هذا سعر مبالغ فيه!"),
     ("Can I get a discount?", "politely asking to pay less", "هل يمكنني الحصول على خصم؟")],
 9: [("I'm saving up for...", "putting money aside for a goal", "أنا أدخر من أجل..."),
     ("Money doesn't grow on trees.", "a reminder to be careful with spending", "المال لا يأتي بسهولة."),
     ("That's a bargain!", "a genuinely good deal", "هذه صفقة رابحة!")],
 10: [("You nailed it!", "you did something perfectly", "لقد أتقنتها تماماً!"),
      ("Give it your best shot.", "try as hard as you possibly can", "ابذل قصارى جهدك."),
      ("Round of applause!", "calling on everyone to clap", "تصفيق حار!")],
 11: [("I'd like to order, please.", "the polite way to ask for food at a restaurant", "أود أن أطلب، من فضلك."),
      ("Could I get the bill, please?", "asking a waiter for the check", "هل يمكنني الحصول على الفاتورة؟"),
      ("What do you recommend?", "asking someone for their suggestion", "بماذا تنصح؟")],
 12: [("Take it or leave it.", "an optional suggestion, no pressure either way", "اقبله أو اتركه، الخيار لك."),
      ("It's worth a try.", "encouraging someone to attempt something", "يستحق أن تجربه."),
      ("Better safe than sorry.", "being careful now avoids regret later", "الحذر خير من الندم.")],
 13: [("Don't forget to like and follow!", "a common social-media call to action", "لا تنسَ الإعجاب والمتابعة!"),
      ("It's trending!", "very popular online right now", "إنه رائج الآن!"),
      ("Drop a comment below.", "inviting people to comment on a post", "اترك تعليقاً في الأسفل.")],
 14: [("Teamwork makes the dream work.", "cooperating well helps everyone succeed", "العمل الجماعي يحقق الأحلام."),
      ("Give it your all.", "try your absolute hardest", "ابذل كل ما لديك."),
      ("We've got your back.", "reassuring someone that they're supported", "نحن نسندك.")],
 15: [("It's a tough call.", "a genuinely difficult decision", "قرار صعب حقاً."),
      ("Let's weigh the pros and cons.", "consider the good and bad sides before deciding", "لنزن الإيجابيات والسلبيات."),
      ("I'll sleep on it.", "think it over carefully before deciding", "سأفكر في الأمر لليلة.")],
 16: [("Take a deep breath.", "a way to calm yourself down", "خذ نفساً عميقاً."),
      ("Butterflies in my stomach.", "a nervous, fluttery feeling before something big", "فراشات في معدتي (شعور بالتوتر)."),
      ("Break a leg!", "a fun way to wish someone good luck before a performance", "بالتوفيق! (قبل عرض أو أداء)")],
 17: [("Shoot for the stars.", "aim as high as possible with your goals", "اطمح للنجوم."),
      ("It's a work in progress.", "still developing, not finished yet", "لا يزال قيد التطوير."),
      ("Follow your passion.", "pursue what you truly love doing", "اتبع شغفك.")],
 18: [("When in Rome...", "adapt to the customs of wherever you are", "إذا كنت في مكان، فاتبع عاداته."),
      ("It's a whole new world.", "describing a very different experience or place", "إنه عالم جديد كلياً."),
      ("Bring back a souvenir!", "asking someone to get a memento from their trip", "أحضر هدية تذكارية!")],
 19: [("Let's brainstorm.", "generate ideas together as a group", "لنتبادل الأفكار."),
      ("We're on the same page.", "everyone agrees and understands each other", "نحن متفقون تماماً."),
      ("Back to the drawing board.", "starting over after something didn't work", "لنعد إلى نقطة البداية.")],
}
