# -*- coding: utf-8 -*-
"""Extra scene slides for the Teen Track (Levels 3-6) -- scene coverage
campaign. Each lesson already has ONE scene (lib/teen_scenes.py ->
assets/vocab-scenes/<level>/NN.jpg). This adds two more per lesson so the
teen levels match the young track's ~3 scenes per lesson.

Images: assets/vocab-scenes/<level>/NN-2.jpg and NN-3.jpg. A scene whose
image is missing is simply skipped, so the rollout can be partial.

Entry: (sentence_en, [bold words], sentence_ar, staging note for the artist)
The staging note names which core characters appear and what they are
doing -- it is NOT shown to students, only used by gen_teen_scene_prompts.py.
Lesson 20 (review) reuses earlier words and gets no extra scenes.
"""

EXTRA = {
 "level3": {
  1: [("I chat with my friends every day.", ["chat", "every day"], "أتحدث مع أصدقائي كل يوم.",
       "Omar on a bench at the hangout spot, phone in hand, chatting happily; Ziad and Noor beside him leaning in to see the screen."),
      ("He sent me a funny meme.", ["sent", "meme"], "أرسل لي ميماً مضحكاً.",
       "Sara holding up her phone showing a silly cat picture (no text on it) to Noor, both laughing out loud; hangout spot.")],
  2: [("She practices guitar every day.", ["practices", "every day"], "تتدرب على الجيتار كل يوم.",
       "Sara sitting on the edge of her bed playing an acoustic guitar, a music stand beside her, calm focused expression; teen bedroom."),
      ("He trains with his team.", ["trains", "team"], "يتدرب مع فريقه.",
       "Hamad in football kit doing drills with two teammates on the school sports field, cones on the grass, coach's whistle visible.")],
  3: [("This game is awesome.", ["awesome"], "هذه اللعبة رائعة.",
       "Ziad on a beanbag with a game controller, eyes wide with delight at a glowing TV, thumbs up; Omar beside him equally impressed; game-night living room."),
      ("Your jacket is so cool.", ["jacket", "cool"], "سترتك رائعة جداً.",
       "Noor pointing admiringly at Ziad's blue zip-up jacket; Ziad grinning and showing it off; school hallway with lockers.")],
  4: [("There is a lamp on my desk.", ["There is", "lamp"], "هناك مصباح على مكتبي.",
       "Omar at his desk switching on a small desk lamp in the evening, laptop and notebook on the desk; teen bedroom with a window showing dusk."),
      ("The cat is asleep on the rug again.", ["cat", "rug"], "القطة نائمة على السجادة مرة أخرى.",
       "Noor in her bedroom, hands on hips, smiling down at a fluffy cat curled up asleep on a round patterned rug; beanbag and shelf behind.")],
  5: [("This backpack is heavy.", ["This", "backpack"], "هذه الحقيبة ثقيلة.",
       "Ziad struggling to lift a stuffed backpack onto his shoulder, leaning sideways with the weight, Hamad laughing; school gate."),
      ("Those headphones are mine.", ["Those", "headphones"], "تلك السماعات لي.",
       "Sara pointing across a table at a pair of orange headphones that Omar is holding up questioningly; school cafeteria.")],
  6: [("Noor has been my best friend since kindergarten.", ["best friend"], "نور صديقتي المقربة منذ الروضة.",
       "Sara and Noor arm in arm, matching beaded bracelets, big smiles; a small framed childhood-style photo of two little girls on the shelf behind them; teen bedroom."),
      ("Omar was chosen as team captain this season.", ["captain", "season"], "اختير عمر قائداً للفريق هذا الموسم.",
       "Omar in football kit with a captain's armband, teammates around him clapping him on the shoulders; sports field.")],
  7: [("Let's take a selfie before we leave.", ["selfie", "leave"], "لنلتقط صورة سيلفي قبل أن نغادر.",
       "Noor holding a phone up at arm's length for a selfie, Sara and Ziad squeezing into frame with big grins; school gate at the end of the day."),
      ("My battery is at two percent, I need a charger.", ["battery", "charger"], "بطاريتي عند اثنين بالمئة، أحتاج شاحناً.",
       "Ziad looking worried at his phone showing a red near-empty battery icon (no numbers), Hamad handing him a charging cable; hangout spot.")],
  8: [("My locker is next to the door.", ["locker", "next to"], "خزانتي بجانب الباب.",
       "Sara opening her locker right beside a classroom door, books in her arms; school hallway with a row of lockers."),
      ("We're doing an experiment in the science lab today.", ["experiment", "science lab"], "نجري تجربة في مختبر العلوم اليوم.",
       "Omar and Noor in safety goggles at a lab bench, pouring a colored liquid between beakers, a microscope beside them; school science lab.")],
  9: [("I can bake cookies.", ["can bake"], "أستطيع خبز الكعك.",
       "Hamad in an apron sliding a tray of cookies out of an oven, oven mitts on, proud smile; bright home kitchen."),
      ("She can draw anime characters.", ["can draw"], "تستطيع رسم شخصيات الأنمي.",
       "Noor at a desk sketching in a large sketchbook (the drawing is an original cartoon character), pencils scattered, Sara watching over her shoulder amazed; teen bedroom.")],
  10: [("Give me a hint, I have no idea what it is.", ["hint", "no idea"], "أعطني تلميحاً، ليس لدي أي فكرة عما هو.",
        "Ziad scratching his head with a confused face while Omar hides an object behind his back with a teasing grin; game-night living room."),
       ("This puzzle has a thousand pieces.", ["puzzle", "pieces"], "هذه الأحجية تحتوي على ألف قطعة.",
        "Sara and Hamad kneeling around a huge half-finished jigsaw puzzle on the floor, hundreds of loose pieces spread around; living room.")],
  11: [("She crossed the finish line first.", ["finish line", "first"], "عبرت خط النهاية أولاً.",
        "Noor breaking through a checkered finish-line tape with arms raised, two other runners just behind her; school running track."),
       ("He won a gold medal.", ["won", "medal"], "فاز بميدالية ذهبية.",
        "Hamad on a small podium holding up a gold medal, Omar and Ziad cheering beside him; sports field with a scoreboard (no readable text).")],
  12: [("Let's welcome him.", ["welcome"], "لنرحّب به.",
        "Sara, Noor and Omar smiling warmly and waving at a nervous new boy (Ziad) standing in the classroom doorway with his backpack; classroom."),
       ("He was too shy to say hello on his first day.", ["shy", "first day"], "كان خجولاً جداً ليقول مرحباً في يومه الأول.",
        "Ziad standing alone by the lockers, shoulders hunched, looking down, while a friendly group chats further down the hallway; school hallway.")],
  13: [("Line up at the door.", ["Line up"], "اصطفوا عند الباب.",
        "Omar, Sara, Noor, Ziad and Hamad standing in a neat line at a classroom door, a teacher (adult, back to camera) holding the door; classroom."),
       ("Submit your homework.", ["Submit", "homework"], "سلّم واجبك.",
        "Noor placing her homework notebook on a pile on the teacher's desk, other students queuing behind her with their notebooks; classroom.")],
  14: [("She is streaming a game.", ["is streaming"], "إنها تبث لعبة مباشرة.",
        "Sara at a desk with a headset on, talking into a small microphone, a game on her screen and a webcam light glowing; teen bedroom."),
       ("They are gaming right now.", ["are gaming", "right now"], "إنهم يلعبون ألعاب الفيديو الآن.",
        "Ziad and Hamad side by side on a sofa with controllers, leaning into the game intensely, snacks on the table; game-night living room.")],
  15: [("I am making flashcards.", ["am making", "flashcards"], "أنا أصنع بطاقات تعليمية.",
        "Omar at a library table writing on small index cards, a neat stack of finished cards beside him, marker pens; school library."),
       ("She is preparing a presentation.", ["is preparing", "presentation"], "إنها تحضّر عرضاً تقديمياً.",
        "Noor at a laptop with a slide deck open (slides show only shapes and pictures, no text), notes beside her, concentrating; library.")],
  16: [("Pass me the controller.", ["Pass", "controller"], "ناولني جهاز التحكم.",
        "Hamad reaching out with an open hand toward a game controller that Ziad is holding up, teasing him; game-night living room."),
       ("This game has a multiplayer mode for four players.", ["multiplayer", "four players"], "هذه اللعبة فيها وضع متعدد اللاعبين لأربعة لاعبين.",
        "Omar, Ziad, Sara and Hamad squeezed onto one sofa, four controllers, a split-screen game on the TV (no text), everyone laughing; living room.")],
  17: [("Let's get popcorn.", ["popcorn"], "لنحضر الفشار.",
        "Sara and Noor at a cinema snack counter holding two big striped popcorn buckets, excited; cinema lobby."),
       ("That horror movie gave me chills.", ["horror movie", "chills"], "فيلم الرعب ذلك أصابني بالقشعريرة.",
        "Ziad hiding behind a cushion with wide eyes while Omar peeks through his fingers at a spooky (not graphic) movie on the TV, dark room lit by the screen.")],
  18: [("Let's vote on where to go this weekend.", ["vote", "weekend"], "لنصوّت على المكان الذي سنذهب إليه في عطلة نهاية الأسبوع.",
        "The five friends around a cafeteria table, three hands raised, Noor counting the votes on her fingers; school cafeteria."),
       ("They had a small argument about which game to play.", ["argument", "game"], "تجادلوا قليلاً حول اللعبة التي سيلعبونها.",
        "Ziad and Hamad each holding up a different game box, frowning at each other playfully, while Sara rolls her eyes with a smile; living room.")],
  19: [("Omar scored the winning goal.", ["scored", "winning goal"], "سجّل عمر الهدف الحاسم.",
        "Omar mid-kick sending a football into the net, goalkeeper diving the wrong way, teammates already leaping in celebration; sports field."),
       ("The whole team ran out to celebrate.", ["celebrate"], "خرج الفريق كله للاحتفال.",
        "Hamad, Omar and Ziad sprinting across the pitch with arms wide, Sara and Noor cheering from the sideline with a homemade banner (no text); sports field.")],
 },
 "level4": {
  1: [("My alarm goes off at six every morning.", ["alarm", "every morning"], "ينطلق منبهي في السادسة كل صباح.",
       "Omar half-asleep in bed reaching out to slap a ringing alarm clock, sunrise light through the curtains; teen bedroom."),
      ("She takes a nap after school.", ["takes a nap", "after school"], "تأخذ قيلولة بعد المدرسة.",
       "Noor asleep on a beanbag still in her school clothes, backpack dropped on the floor, afternoon light; teen bedroom.")],
  2: [("I write all my homework in my planner.", ["planner"], "أكتب كل واجباتي في مفكرتي.",
       "Sara at her desk writing in an open planner with colorful tabs, textbooks stacked beside it; teen bedroom."),
      ("My bedtime is 10 pm.", ["bedtime"], "موعد نومي هو العاشرة مساءً.",
       "Hamad in pajamas switching off a bedside lamp, a wall clock showing ten (clock face only, no digits needed), yawning; bedroom at night.")],
  3: [("Sometimes I walk to school instead of taking the bus.", ["Sometimes", "walk"], "أحياناً أمشي إلى المدرسة بدلاً من ركوب الحافلة.",
       "Ziad walking along a sunny pavement with his backpack, waving at a school bus passing by; street near the school."),
      ("I brush my teeth twice a day.", ["twice a day"], "أنظف أسناني مرتين في اليوم.",
       "Omar brushing his teeth at a bathroom mirror, morning light; a small toothbrush cup with two toothbrushes on the sink.")],
  4: [("Mark the trip on the calendar so we don't forget.", ["calendar", "forget"], "علّم موعد الرحلة على التقويم حتى لا ننسى.",
       "Noor circling a date on a big wall calendar with a marker while Sara points at it; teen bedroom."),
      ("The countdown to summer vacation has started.", ["countdown", "summer vacation"], "بدأ العد التنازلي للعطلة الصيفية.",
       "Ziad crossing off days on a wall calendar with a beach poster next to it, excited grin; school hallway notice board.")],
  5: [("I video chat with her every week.", ["video chat", "every week"], "أتحدث معها عبر مكالمة فيديو كل أسبوع.",
       "Sara waving at a laptop screen showing Noor waving back from another room (video call window, no text); teen bedroom."),
      ("Invite them to the party.", ["Invite", "party"], "ادعُهم إلى الحفلة.",
       "Omar handing out small invitation cards (blank, decorated with balloons) to Ziad and Hamad in the school hallway.")],
  6: [("Is this wallet his?", ["wallet", "his"], "هل هذه المحفظة له؟",
       "Noor holding up a found brown wallet questioningly while Hamad pats his pockets in surprise; school cafeteria."),
      ("Take an umbrella, it might rain later.", ["umbrella", "rain"], "خذ مظلة، قد تمطر لاحقاً.",
       "Sara handing a folded umbrella to Ziad at the front door, grey clouds visible through the window; home entrance.")],
  7: [("Is there any juice in the fridge?", ["any juice", "fridge"], "هل يوجد أي عصير في الثلاجة؟",
       "Ziad peering into an open fridge, holding the door, Hamad behind him hopeful; bright home kitchen."),
      ("These chips are so crunchy.", ["chips", "crunchy"], "هذه الرقائق مقرمشة جداً.",
       "Omar biting a potato chip with a loud-crunch expression, a big open bag of chips on the table, Noor covering her ears playfully; living room.")],
  8: [("The shoes I wanted are finally on sale.", ["shoes", "on sale"], "الحذاء الذي أردته أصبح أخيراً في التخفيضات.",
       "Sara pointing excitedly at a pair of sneakers on a shop display with a red sale tag (no text, just a bright tag); shopping mall."),
      ("Keep the receipt.", ["Keep", "receipt"], "احتفظ بالإيصال.",
       "Hamad folding a paper receipt into his wallet at a shop counter while a cashier (adult, back turned) hands over a bag; mall shop.")],
  9: [("I earn money doing chores.", ["earn", "chores"], "أكسب المال بالقيام بالأعمال المنزلية.",
       "Omar washing a car in the driveway with a bucket and sponge, a few coins and notes on the step beside him, his dad (adult, thobe) giving a thumbs up in the background."),
      ("Can I borrow some money?", ["borrow", "money"], "هل يمكنني اقتراض بعض المال؟",
       "Ziad with a sheepish grin and empty pockets turned out, Hamad holding out a couple of coins; school cafeteria counter.")],
  10: [("The audience clapped loudly after the show.", ["audience", "clapped"], "صفّق الجمهور بصوت عالٍ بعد العرض.",
        "Noor on a small stage taking a bow, an audience of students clapping and cheering in the foreground; school hall."),
       ("He is the most skilled player.", ["the most skilled"], "هو اللاعب الأكثر مهارة.",
        "Hamad juggling a football on his knee with total control while Omar and Ziad watch impressed; sports field.")],
  11: [("Can I see the menu, please?", ["menu", "please"], "هل يمكنني رؤية قائمة الطعام، من فضلك؟",
        "Sara at a restaurant table politely asking a waiter (adult, back to camera) who is handing her a menu (blank cover); cozy restaurant."),
       ("Can we order dessert after dinner?", ["order", "dessert"], "هل يمكننا طلب الحلوى بعد العشاء؟",
        "Ziad and Noor at a restaurant table with empty plates, both looking hopefully at a dessert trolley of cakes passing by.")],
  12: [("Here's a useful tip.", ["useful tip"], "إليك نصيحة مفيدة.",
        "Omar showing Ziad how to hold a skateboard foot position, pointing at the board; hangout spot."),
       ("Practicing every day will help you improve.", ["Practicing", "improve"], "التدريب كل يوم سيساعدك على التحسن.",
        "Sara coaching Noor at a piano keyboard, Noor playing with a determined smile, a practice chart with stickers on the wall (no text); teen bedroom.")],
  13: [("He updated his profile picture.", ["updated", "profile picture"], "قام بتحديث صورة ملفه الشخصي.",
        "Hamad holding his phone showing a profile screen with a fresh photo of himself (screen has only a round photo and shapes, no text); hangout spot."),
       ("She added a fun hashtag to her post.", ["hashtag", "post"], "أضافت وسماً ممتعاً إلى منشورها.",
        "Noor typing on her phone with a big '#' symbol floating playfully above the screen, Sara looking over her shoulder smiling; school cafeteria.")],
  14: [("Our team won the trophy.", ["team", "trophy"], "فاز فريقنا بالكأس.",
        "Omar, Hamad and Ziad lifting a big gold trophy together, Sara and Noor cheering; sports field."),
       ("He made a perfect pass to his teammate.", ["pass", "teammate"], "قدّم تمريرة مثالية لزميله في الفريق.",
        "Ziad passing a football across the grass to Hamad who is ready to receive it, motion lines on the ball; sports field.")],
  15: [("Let's list the pros and cons before we decide.", ["pros and cons", "decide"], "لنكتب الإيجابيات والسلبيات قبل أن نقرر.",
        "Sara at a whiteboard drawing a two-column chart with plus and minus symbols (no words), Omar and Noor watching; classroom."),
       ("There's a small risk we might be late.", ["risk", "late"], "هناك خطر بسيط أن نتأخر.",
        "Hamad glancing anxiously at his watch while Ziad casually finishes a milkshake, a bus visible pulling up outside; cafe window.")],
  16: [("Take a deep breath before you go on stage.", ["deep breath", "stage"], "خذ نفساً عميقاً قبل أن تصعد على المسرح.",
        "Noor backstage with eyes closed taking a deep breath, Sara's hand on her shoulder reassuringly, stage curtain beside them."),
       ("He stays calm under pressure.", ["calm", "pressure"], "يبقى هادئاً تحت الضغط.",
        "Omar taking a penalty kick, completely composed, while a crowd in the background waves flags (no text); sports field.")],
  17: [("Art is my passion.", ["Art", "passion"], "الفن هو شغفي.",
        "Noor painting at an easel with paint on her fingers, a wall of her own colorful abstract paintings behind her; art room."),
       ("I want to volunteer at the animal shelter.", ["volunteer", "animal shelter"], "أريد أن أتطوع في ملجأ الحيوانات.",
        "Hamad crouched in a clean animal shelter holding a puppy, a cat in a pen behind him, a volunteer badge (blank) on his thobe.")],
  18: [("Don't forget your passport at the airport.", ["passport", "airport"], "لا تنسَ جواز سفرك في المطار.",
        "Sara holding up a passport (blank cover) and pointing at it, Ziad patting his pockets in panic, suitcases beside them; airport hall."),
       ("There's a food festival in the park this weekend.", ["food festival", "park"], "هناك مهرجان طعام في الحديقة في عطلة نهاية الأسبوع.",
        "Omar and Noor walking between colorful food stalls with string lights and flags (no text), holding skewers and lemonade; park at sunset.")],
  19: [("We did our research at the library.", ["research", "library"], "أجرينا بحثنا في المكتبة.",
        "Sara, Omar and Ziad at a library table covered in open books and a laptop, Sara taking notes; school library."),
       ("The teacher gave us helpful feedback on our project.", ["feedback", "project"], "قدّم لنا المعلم ملاحظات مفيدة على مشروعنا.",
        "A teacher (adult, seen from behind) pointing at a poster project held by Noor and Hamad, both nodding attentively; classroom.")],
 },
 "level5": {
  1: [("We visited my grandparents on Friday.", ["visited", "Friday"], "زرنا أجدادي يوم الجمعة.",
       "Omar and his little sister hugging a smiling grandmother and grandfather (adults in traditional Gulf dress) at their front door, a plate of dates on a side table; family home."),
      ("I baked cookies with my little sister.", ["baked", "little sister"], "خبزت الكعك مع أختي الصغيرة.",
       "Sara and a small girl (around 6) in aprons, flour on their cheeks, holding a tray of fresh cookies; home kitchen.")],
  2: [("She found her missing shoe under the bed.", ["found", "under the bed"], "وجدت حذاءها المفقود تحت السرير.",
       "Noor on her knees lifting the bedcover and pulling out a single sneaker, triumphant face; teen bedroom."),
      ("He took a lot of photos.", ["took", "photos"], "التقط الكثير من الصور.",
       "Ziad holding up his phone taking a photo of a colorful fountain, Hamad posing in front of it; city park.")],
  3: [("Did you reply to Noor's message yet?", ["reply", "message"], "هل رددت على رسالة نور بعد؟",
       "Sara tapping Omar on the shoulder and pointing at his phone with a raised eyebrow, Omar looking guilty; school hallway."),
      ("The mailman didn't deliver our package today.", ["deliver", "package"], "لم يوصل ساعي البريد طردنا اليوم.",
       "Hamad standing at an open front door looking at an empty doorstep, a mail van driving away down the street; house entrance.")],
  4: [("The concert was amazing.", ["concert", "amazing"], "كان الحفل مذهلاً.",
       "Noor and Sara among a crowd at an outdoor concert, stage lights and confetti, both with arms up and thrilled faces; evening."),
      ("The garden felt peaceful early in the morning.", ["garden", "peaceful"], "بدت الحديقة هادئة في الصباح الباكر.",
       "Omar sitting alone on a garden bench with a cup of tea, soft sunrise light, birds on a fence, calm expression; garden.")],
  5: [("We stood in a long queue for the roller coaster.", ["queue", "roller coaster"], "وقفنا في طابور طويل لركوب الأفعوانية.",
       "Ziad, Hamad and Omar in a winding queue at a theme park, a roller coaster looping in the background; sunny day."),
      ("There was a huge crowd.", ["There was", "crowd"], "كان هناك حشد ضخم.",
       "Sara and Noor on tiptoe trying to see over a big crowd at a school fair, lots of people and balloons; outdoor event.")],
  6: [("We moved to this house three years ago.", ["moved", "three years ago"], "انتقلنا إلى هذا البيت قبل ثلاث سنوات.",
       "Omar standing in front of a family house pointing at it while telling Ziad, a small moving-day memory shown as a framed photo in his hand; street."),
      ("I recently started learning the guitar.", ["recently", "guitar"], "بدأت مؤخراً تعلّم الجيتار.",
       "Hamad carefully strumming a brand-new guitar with a beginner's chord chart (shapes only, no text) propped beside him; teen bedroom.")],
  7: [("Suddenly, the lights went out.", ["Suddenly", "lights"], "فجأة، انطفأت الأنوار.",
       "The five friends in a dark living room lit only by a phone flashlight, surprised faces, a game paused on a black TV; night."),
      ("At last, the bus arrived.", ["At last", "bus"], "أخيراً، وصلت الحافلة.",
       "Sara and Noor at a bus stop in the rain, relieved faces as a bus pulls up with its headlights on; wet street.")],
  8: [("It was raining, so we stayed home.", ["raining", "stayed home"], "كانت تمطر، لذا بقينا في المنزل.",
       "Ziad and Omar on a sofa under a blanket with hot drinks, heavy rain on the window behind them; living room."),
      ("The cause of the delay was heavy traffic.", ["cause", "traffic"], "كان سبب التأخير هو الزحام الشديد.",
       "Hamad in the back seat of a car looking out at a long line of cars with red brake lights, checking his watch; city road at dusk.")],
  9: [("She was thrilled when she saw her test score.", ["thrilled", "test score"], "كانت في غاية السعادة عندما رأت درجة اختبارها.",
       "Noor jumping with joy holding a test paper with a big gold star sticker on it (no readable marks), Sara hugging her; classroom."),
      ("I felt embarrassed when I tripped in the hallway.", ["embarrassed", "tripped"], "شعرت بالإحراج عندما تعثرت في الممر.",
       "Ziad mid-stumble with books flying, red cheeks, Omar reaching out to help him; school hallway.")],
  10: [("We were waiting at the bus stop.", ["were waiting", "bus stop"], "كنا ننتظر عند موقف الحافلة.",
        "Omar, Sara and Hamad huddled under a bus-stop shelter, dark storm clouds and wind blowing leaves; street."),
       ("We took shelter under a big tree.", ["took shelter", "tree"], "احتمينا تحت شجرة كبيرة.",
        "Noor and Ziad crouched under a large tree during a downpour, holding a picnic basket, lightning far off in the sky; park.")],
  11: [("She memorized the vocabulary.", ["memorized", "vocabulary"], "حفظت المفردات.",
        "Sara with eyes closed and a finger to her temple, flashcards fanned in her other hand, a stack of cards on the desk; library."),
       ("I did a full revision the night before the exam.", ["revision", "exam"], "قمت بمراجعة كاملة في الليلة التي سبقت الامتحان.",
        "Hamad at his desk late at night surrounded by open notebooks and highlighters, a desk lamp on, a mug beside him; teen bedroom.")],
  12: [("Don't lose your boarding pass before the flight.", ["boarding pass", "flight"], "لا تفقد بطاقة صعود الطائرة قبل الرحلة.",
        "Noor holding a boarding pass firmly (blank card with an airplane icon) while Ziad searches his bag frantically; airport gate."),
       ("We took a photo in front of the famous landmark.", ["photo", "landmark"], "التقطنا صورة أمام المعلم الشهير.",
        "Omar, Sara and Hamad posing for a photo in front of a tall famous-looking tower in a foreign city (generic landmark, not a real one); sunny square.")],
  13: [("He spilled juice because he was running.", ["spilled", "running"], "سكب العصير لأنه كان يركض.",
        "Ziad running through the cafeteria with a cup of orange juice sloshing out onto the floor, a shocked Omar dodging; school cafeteria."),
       ("She apologized for being late.", ["apologized", "late"], "اعتذرت عن التأخر.",
        "Noor at a classroom door with hands pressed together in apology, a teacher (adult, back to camera) and classmates looking up; classroom.")],
  14: [("We filled the room with colorful balloons.", ["filled", "balloons"], "ملأنا الغرفة بالبالونات الملونة.",
        "Sara and Omar tying up dozens of bright balloons that fill a living room to the ceiling, both laughing; party setup."),
       ("There was a huge cake.", ["There was", "cake"], "كانت هناك كعكة ضخمة.",
        "Hamad carrying an enormous three-tier birthday cake with candles into a room of cheering friends; party.")],
  15: [("Today is my parents' wedding anniversary.", ["parents", "wedding anniversary"], "اليوم ذكرى زواج والديّ.",
        "Noor presenting a bouquet and a small gift box to her parents (adults in modest Gulf dress) who smile warmly at a decorated dinner table; family home."),
       ("We looked through the old photo album together.", ["photo album", "together"], "تصفّحنا ألبوم الصور القديم معاً.",
        "Omar and his grandfather (adult, white thobe, grey beard) on a sofa turning the pages of a thick photo album, both smiling; family living room.")],
  16: [("She was listening to music while studying.", ["was listening", "studying"], "كانت تستمع إلى الموسيقى أثناء الدراسة.",
        "Sara at her desk with headphones on, tapping her pencil to the beat, textbook open; teen bedroom."),
       ("He was daydreaming instead of listening to the lesson.", ["daydreaming", "lesson"], "كان يحلم أحلام يقظة بدلاً من الاستماع للدرس.",
        "Ziad at his desk staring out of the window with a dreamy smile, a thought-cloud showing a football stadium, while the teacher (back to camera) writes on the board; classroom.")],
  17: [("My hobby is collecting stamps.", ["hobby", "collecting stamps"], "هوايتي هي جمع الطوابع.",
        "Hamad showing Noor an open stamp album with colorful stamps (no readable text), a magnifying glass in hand; teen bedroom."),
       ("That match was the turning point of the season.", ["turning point", "season"], "كانت تلك المباراة نقطة التحول في الموسم.",
        "Omar telling the story with wide gestures to Sara at the cafeteria table, a small trophy and a team photo (no text) on the table between them.")],
  18: [("We shared popcorn.", ["shared", "popcorn"], "تقاسمنا الفشار.",
        "Noor and Sara on a sofa both reaching into one big bowl of popcorn, eyes on the TV glow; movie night living room."),
       ("Nobody expected that plot twist at the end.", ["plot twist", "end"], "لم يتوقع أحد تلك المفاجأة في النهاية.",
        "The five friends on a sofa all frozen with jaws dropped at the TV screen (screen shows only a dramatic glow), popcorn spilling; living room.")],
  19: [("I checked the lost and found for my jacket.", ["lost and found", "jacket"], "بحثت عن سترتي في قسم المفقودات.",
        "Ziad digging through a big lost-and-found box at the school office, holding up a blue jacket happily; school office counter."),
       ("My bag has a label with my name on it.", ["label", "name"], "حقيبتي عليها بطاقة باسمي.",
        "Sara pointing at a small blank name tag hanging from her backpack strap, showing Hamad; school hallway.")],
 },
 "level6": {
  1: [("She applied for a scholarship to study abroad.", ["applied", "scholarship"], "تقدّمت بطلب للحصول على منحة دراسية للدراسة في الخارج.",
       "Sara at a laptop clicking a big button on an application form (form shows only boxes, no text), a world map poster on the wall; teen bedroom."),
      ("They're going to move to a new city.", ["going to move", "new city"], "سينتقلون إلى مدينة جديدة.",
       "Hamad and his family (parents in modest Gulf dress) loading suitcases and boxes into a car, a city skyline on the horizon; street.")],
  2: [("The forecast says it will be sunny all weekend.", ["forecast", "sunny"], "تقول النشرة الجوية إن الطقس سيكون مشمساً طوال عطلة نهاية الأسبوع.",
       "Omar pointing at a TV weather map covered in sun icons (no text), Ziad already holding a beach ball; living room."),
      ("She will definitely win.", ["definitely", "win"], "ستفوز بالتأكيد.",
       "Noor sprinting far ahead of other runners on a track, Sara on the sideline pumping her fist confidently; sports field.")],
  3: [("We're hosting a party this weekend.", ["hosting", "party"], "سنستضيف حفلة في عطلة نهاية الأسبوع.",
       "Sara and Omar hanging bunting and balloons in a living room, a table of snacks half set up; party prep."),
      ("I already bought my ticket for the concert.", ["bought", "ticket"], "اشتريت تذكرتي للحفل بالفعل.",
       "Ziad proudly holding up a concert ticket (blank with a music-note icon) in front of a concert poster (shapes only, no text); school hallway.")],
  4: [("Call me as soon as you land.", ["as soon as", "land"], "اتصل بي بمجرد أن تهبط الطائرة.",
       "Noor hugging Sara goodbye at an airport departure gate, miming a phone with her hand, a plane visible through the window."),
      ("By the time we arrived, the movie had started.", ["By the time", "started"], "بحلول وقت وصولنا، كان الفيلم قد بدأ.",
       "Hamad and Omar tiptoeing into a dark cinema with popcorn, the screen already glowing, other viewers seated; cinema.")],
  5: [("Wearing a helmet is mandatory on this ride.", ["helmet", "mandatory"], "ارتداء الخوذة إلزامي في هذه اللعبة.",
       "Ziad strapping on a helmet at a go-kart track, a staff member (adult, back turned) pointing at a helmet sign showing only a helmet icon; outdoor track."),
      ("He decided to volunteer at the community center.", ["volunteer", "community center"], "قرر أن يتطوع في المركز المجتمعي.",
       "Hamad handing out food boxes at a community center table with other volunteers, warm smiles; indoor hall.")],
  6: [("Handle the eggs gently, they break easily.", ["gently", "break"], "تعامل مع البيض برفق، فهو ينكسر بسهولة.",
       "Omar carefully carrying a carton of eggs with both hands and a tense face, Sara gesturing 'slowly' beside him; home kitchen."),
      ("The teacher waited patiently.", ["waited patiently"], "انتظر المعلم بصبر.",
       "A teacher (adult, seen from the side) with a kind smile and folded hands while Noor thinks hard at the whiteboard, marker in hand; classroom.")],
  7: [("Grilled chicken is healthier than fried chicken.", ["healthier than"], "الدجاج المشوي أكثر صحة من الدجاج المقلي.",
       "Noor holding a plate of grilled chicken and salad on one side and Ziad holding a basket of fried chicken on the other, comparing; school cafeteria."),
      ("This is the best pizza in town.", ["the best", "pizza"], "هذه أفضل بيتزا في المدينة.",
       "Hamad and Omar at a pizzeria table with a huge steaming pizza, Hamad kissing his fingers like a chef; restaurant.")],
  8: [("Our family is planning a road trip this summer.", ["road trip", "summer"], "تخطط عائلتنا لرحلة برية هذا الصيف.",
       "Sara and her parents (adults, modest Gulf dress) around a kitchen table tracing a route on a big paper map, a toy car on the map; home kitchen."),
      ("Let's play a board game after dinner.", ["board game", "dinner"], "لنلعب لعبة لوحية بعد العشاء.",
       "The five friends around a coffee table with a colorful board game (abstract shapes, no text), Ziad rolling dice; living room.")],
  9: [("We will graduate next year.", ["graduate", "next year"], "سنتخرج في العام القادم.",
       "Omar, Sara, Noor, Ziad and Hamad throwing graduation caps in the air outside the school, big smiles; school entrance."),
      ("New technology is changing how we learn.", ["technology", "learn"], "التكنولوجيا الجديدة تغيّر طريقة تعلمنا.",
       "Noor wearing a VR headset reaching out at floating 3D shapes while Hamad watches on a tablet; modern classroom.")],
  10: [("Please knock first, I need some privacy.", ["knock", "privacy"], "من فضلك اطرق الباب أولاً، أحتاج بعض الخصوصية.",
        "Sara inside her bedroom holding the door half-closed and pointing at it politely, her little brother (boy about 7) outside with a hand raised to knock."),
       ("Feeding the dog is my responsibility.", ["Feeding", "responsibility"], "إطعام الكلب هو مسؤوليتي.",
        "Ziad pouring kibble into a bowl for an excited dog, a chores chart with sticker stars on the fridge (no text); home kitchen.")],
  11: [("Making eye contact shows you're listening.", ["eye contact", "listening"], "التواصل البصري يُظهر أنك تستمع.",
        "Omar and Hamad seated facing each other in conversation, Omar looking Hamad in the eye attentively and nodding; library."),
       ("His body language showed he was nervous.", ["body language", "nervous"], "أظهرت لغة جسده أنه كان متوتراً.",
        "Ziad at the front of the class with crossed arms, hunched shoulders and a shaky smile, classmates watching kindly; classroom.")],
  12: [("These shoes are durable enough for hiking.", ["durable", "hiking"], "هذا الحذاء متين بما يكفي للمشي في الجبال.",
        "Hamad on a rocky mountain trail lifting one boot to show its thick sole, Noor with a walking stick beside him; hiking trail."),
       ("This phone is affordable and works really well.", ["affordable", "works"], "هذا الهاتف بسعر معقول ويعمل بشكل ممتاز.",
        "Sara in a phone shop holding a simple phone with a small price tag (no digits) while Omar gives a thumbs up; electronics store.")],
  13: [("He was driving while talking on the phone.", ["was driving", "phone"], "كان يقود وهو يتحدث على الهاتف.",
        "An adult man (Omar's older cousin, thobe) at the wheel holding a phone to his ear while Omar in the passenger seat looks alarmed and points at the road; car interior. Show it as a 'don't do this' moment."),
       ("I set a timer for twenty minutes of reading.", ["timer", "reading"], "ضبطت مؤقتاً لعشرين دقيقة من القراءة.",
        "Noor placing a small kitchen timer on her desk next to an open book, phone face-down and far away; teen bedroom.")],
  14: [("I wrote my goal in my diary.", ["goal", "diary"], "كتبت هدفي في مذكراتي.",
        "Sara writing in a diary by lamplight with a determined smile, a vision-board of pictures on the wall (no text); teen bedroom."),
       ("Finishing the marathon was a big milestone for him.", ["marathon", "milestone"], "كان إنهاء الماراثون إنجازاً كبيراً بالنسبة له.",
        "Hamad crossing a marathon finish line exhausted but elated, a medal being placed around his neck; city street race.")],
  15: [("Do you have any evidence?", ["evidence"], "هل لديك أي دليل؟",
        "Omar at a debate podium raising an eyebrow while Noor at the opposite podium holds up a folder and a bar chart (shapes only); classroom debate."),
       ("In conclusion, both sides made good points.", ["In conclusion", "both sides"], "في الختام، قدّم الطرفان نقاطاً جيدة.",
        "Sara as moderator standing between two debate teams, hands open toward both, classmates applauding; classroom.")],
  16: [("I made a checklist for the exam.", ["checklist", "exam"], "أعددت قائمة تحقق للامتحان.",
        "Ziad ticking boxes on a checklist pinned to his wall (boxes and ticks only, no words), pencils and a calculator laid out; teen bedroom."),
       ("We have one more rehearsal before the show.", ["rehearsal", "show"], "لدينا بروفة واحدة أخرى قبل العرض.",
        "Noor, Sara and Hamad on a stage rehearsing a scene with scripts in hand, a drama teacher (adult, back turned) gesturing; school hall.")],
  17: [("Follow the instructions carefully.", ["instructions", "carefully"], "اتبع التعليمات بعناية.",
        "Omar and Ziad assembling a model robot kit, Omar reading a picture-only instruction sheet while Ziad holds a piece; teen bedroom."),
       ("Always double-check your answers before submitting.", ["double-check", "submitting"], "تحقق دائماً من إجاباتك مرتين قبل التسليم.",
        "Sara at her exam desk running her finger down her answer sheet with a magnifying-glass-focused look, clock on the wall; classroom.")],
  18: [("This festival celebrates our local heritage.", ["festival", "heritage"], "يحتفل هذا المهرجان بتراثنا المحلي.",
        "Hamad and Noor at a heritage festival with traditional Gulf tents, lanterns, a falcon display and folk dancers in the background; evening."),
       ("We were amazed by their hospitality.", ["amazed", "hospitality"], "أدهشتنا كرم ضيافتهم.",
        "A host family (adults in traditional dress) welcoming Omar and Sara with a tray of coffee and dates in a majlis with patterned cushions.")],
  19: [("The teacher did a headcount before we left.", ["headcount", "left"], "قام المعلم بعدّ الطلاب قبل أن نغادر.",
        "A teacher (adult, seen from behind) with a clipboard counting a line of students boarding a school bus, Ziad at the back waving; parking lot."),
       ("A parent volunteered to chaperone the trip.", ["chaperone", "trip"], "تطوّع أحد الآباء لمرافقة الرحلة.",
        "A friendly parent (adult, white thobe) walking at the front of a group of students including Omar and Noor through a museum entrance; museum.")],
 },
}
